//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef _SFPageLoadErrorControllerDelegate_Protocol_h
#define _SFPageLoadErrorControllerDelegate_Protocol_h
@import Foundation;

@protocol _SFPageLoadErrorControllerDelegate <NSObject>
/* instance methods */
- (BOOL)pageLoadErrorControllerShouldHandleCertificateError:(id)error;
- (void)pageLoadErrorController:(id)controller loadFailedRequestAfterError:(id)error;
- (void)pageLoadErrorControllerClosePage:(id)page;
- (void)pageLoadErrorController:(id)controller presentViewController:(id)controller;
- (BOOL)pageLoadErrorControllerShouldPermanentlyAcceptCertificate:(id)certificate;
- (id)pageLoadErrorControllerGetSecIdentityPreferencesController:(id)controller;
- (BOOL)pageLoadErrorControllerShouldReloadAfterError:(id)error;
- (BOOL)pageLoadErrorControllerIsInPreviewMode:(id)mode;
- (void)pageLoadErrorController:(id)controller allowLegacyTLSConnectionForURL:(id)url navigateToURL:(id)url;
@optional
/* instance methods */
- (void)pageLoadErrorControllerDidAddAlert:(id)alert;
@end

#endif /* _SFPageLoadErrorControllerDelegate_Protocol_h */
