//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef _SFSafariSharingExtensionController_h
#define _SFSafariSharingExtensionController_h
@import Foundation;

#include "SFSharingExtensionWebProcessController-Protocol.h"

@class WKWebView;

@interface _SFSafariSharingExtensionController : NSObject {
  /* instance variables */
  WKWebView *_webView;
  NSObject<SFSharingExtensionWebProcessController> *_extensionControllerProxy;
}

/* instance methods */
- (id)initWithWebView:(id)view;
- (id)_extensionControllerProxy;
- (void)prepareJavaScriptWorldForSharingExtension:(id)extension javaScript:(id)script;
- (void)runJavaScriptForSharingExtension:(id)extension extraArguments:(id)arguments completion:(id /* block */)completion;
- (void)finalizeJavaScriptForSharingExtension:(id)extension arguments:(id)arguments;
@end

#endif /* _SFSafariSharingExtensionController_h */
