//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef SFDismissButton_h
#define SFDismissButton_h
@import Foundation;

#include "UIButton.h"

@class UITraitCollection;

@interface SFDismissButton : UIButton {
  /* instance variables */
  long long _style;
  UITraitCollection *_preferredTraitCollection;
}

/* instance methods */
- (id)init;
@end

#endif /* SFDismissButton_h */
