//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef SFPasswordServiceViewController_h
#define SFPasswordServiceViewController_h
@import Foundation;

#include "UIViewController.h"

@class NSString;

@interface SFPasswordServiceViewController : UIViewController

@property (readonly, nonatomic) NSString *applicationIdentifier;

/* class methods */
+ (id)_remoteViewControllerInterface;

/* instance methods */
- (void)_willAppearInRemoteViewController;
@end

#endif /* SFPasswordServiceViewController_h */
