//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef UIViewController_AccountManagerExtras_h
#define UIViewController_AccountManagerExtras_h
@import Foundation;

@interface UIViewController (AccountManagerExtras)
/* instance methods */
- (BOOL)safari_checkForAbilityToOpenWebContentAndNotifyIfNecessary:(id)necessary;
@end

#endif /* UIViewController_AccountManagerExtras_h */
