//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1877.50.1.0.0
//
#ifndef MLComputeDeviceRegistryProtocol_Protocol_h
#define MLComputeDeviceRegistryProtocol_Protocol_h
@import Foundation;

@protocol MLComputeDeviceRegistryProtocol <NSObject>

@property (readonly, copy, nonatomic) NSArray *registeredComputeDevices;
@property (readonly, copy, nonatomic) NSArray *registeredAndAccessibleComputeDevices;

/* class methods */
+ (id)sharedRegistry;
@end

#endif /* MLComputeDeviceRegistryProtocol_Protocol_h */
