//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1877.50.1.0.0
//
#ifndef MLMetalDeviceObserver_h
#define MLMetalDeviceObserver_h
@import Foundation;

@interface MLMetalDeviceObserver : NSObject
/* instance methods */
- (id)startObservingWithBlock:(id /* block */)block deviceObserver:(id *)observer;
- (void)stopObserving:(id)observing;
@end

#endif /* MLMetalDeviceObserver_h */
