//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1877.50.1.0.0
//
#ifndef MLParameterUtils_h
#define MLParameterUtils_h
@import Foundation;

@interface MLParameterUtils : NSObject
/* class methods */
+ (id)objectForKey:(id)key class:(Class)class dictionary:(id)dictionary;
+ (id)stringForKey:(id)key inDictionary:(id)dictionary;
+ (id)numberForKey:(id)key inDictionary:(id)dictionary;
+ (id)deScopeParameters:(id)parameters byDeletingPrefixingScope:(id)scope;
+ (void)appendParameterDescriptions:(id)descriptions toModelDescription:(id)description;
@end

#endif /* MLParameterUtils_h */
