//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1877.50.1.0.0
//
#ifndef MLRegressor_Protocol_h
#define MLRegressor_Protocol_h
@import Foundation;

#include "MLModel.h"
#include "MLModelConfiguration.h"
#include "MLModelDescription.h"
#include "MLModelMetadata.h"
#include "MLRegressor-Protocol.h"

@class NSString;

@protocol MLRegressor <MLModeling>
/* instance methods */
- (id)regress:(id)regress options:(id)options error:(id *)error;
@end

#endif /* MLRegressor_Protocol_h */
