//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1490.0.4.0.0
//
#ifndef _NSCFSocksProxy_h
#define _NSCFSocksProxy_h
@import Foundation;

#include "NSProxyConnection.h"
#include "NSProxyConnectionDelegate-Protocol.h"
#include "__CFN_SocksHandshake.h"

@class NSDictionary, NSString;
@protocol OS_dispatch_queue;

@interface _NSCFSocksProxy : NSObject<NSProxyConnectionDelegate> {
  /* instance variables */
  NSObject<OS_dispatch_queue> *_queue;
  int _outPort;
  NSString *_outHost;
  __CFN_SocksHandshake *_socksHandshake;
  NSProxyConnection *_inbound;
  NSProxyConnection *_outbound;
  NSDictionary *_configuration;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)handleIncomingConnection:(id)connection queue:(id)queue configuration:(id)configuration;

/* instance methods */
- (void)connected:(int)connected;
- (void)cleanup;
- (void)dealloc;
- (void)outboundConnectionReceivedData:(id)data handler:(id /* block */)handler;
- (void)outboundConnectionCompleteWithError:(int)error;
@end

#endif /* _NSCFSocksProxy_h */
