//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1490.0.4.0.0
//
#ifndef NSURL_NSURLSession_Additions_h
#define NSURL_NSURLSession_Additions_h
@import Foundation;

@interface NSURL (NSURLSession_Additions)
/* instance methods */
- (BOOL)_isSafeFileForBackgroundUploadForMe;
- (BOOL)_isSafeDirectoryForDownloads:(int)downloads withToken:(struct { unsigned int x0[8] })token;
@end

#endif /* NSURL_NSURLSession_Additions_h */
