//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef _NSPersistenceUtilities_h
#define _NSPersistenceUtilities_h
@import Foundation;

@interface _NSPersistenceUtilities : NSObject
/* class methods */
+ (void)initialize;
+ (BOOL)_setURL:(id)url forPersistentStore:(id)store withCoordinator:(id)coordinator;
@end

#endif /* _NSPersistenceUtilities_h */
