//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef CDDCloudKitServer_h
#define CDDCloudKitServer_h
@import Foundation;

#include "CDDCloudKitServerConfiguration.h"
#include "CDDCloudKitServerProxy-Protocol.h"
#include "NSPersistentContainer.h"
#include "NSXPCListenerDelegate-Protocol.h"
#include "PFCloudKitContainerProvider.h"
#include "_PFCoreDataCloudKitServer-Protocol.h"

@class CKScheduler, NSError, NSString, NSXPCListener;
@protocol OS_dispatch_group;

@interface CDDCloudKitServer : NSObject<NSXPCListenerDelegate, CDDCloudKitServerProxy, _PFCoreDataCloudKitServer> {
  /* instance variables */
  BOOL _initialized;
  NSPersistentContainer *_metadataContainer;
  NSObject<OS_dispatch_group> *_initializationGroup;
  NSError *_lastInitializationError;
}

@property (readonly, nonatomic) NSXPCListener *listener;
@property (readonly, copy, nonatomic) CDDCloudKitServerConfiguration *configuration;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) PFCloudKitContainerProvider *containerProvider;
@property (readonly, nonatomic) CKScheduler *scheduler;

/* instance methods */
- (id)initWithListener:(id)listener configuration:(id)configuration;
- (void)dealloc;
- (void)setUp;
- (void)tearDown;
- (BOOL)listener:(id)listener shouldAcceptNewConnection:(id)connection;
- (void)handleMessage:(id)message reply:(id /* block */)reply;
- (void)finishedActivity:(id)activity withResult:(id)result inManagedObjectContext:(id)context;
@end

#endif /* CDDCloudKitServer_h */
