//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef NSBasicObjectID_h
#define NSBasicObjectID_h
@import Foundation;

#include "_NSCoreManagedObjectID.h"

@interface NSBasicObjectID : _NSCoreManagedObjectID {
  /* instance variables */
  int _cd_rc;
  id _referenceData;
}

/* class methods */
+ (char *)generatedNameSuffix;

/* instance methods */
- (id)initWithObject:(id)object;
- (void)dealloc;
- (id)_retainedURIString;
- (id)_referenceData;
@end

#endif /* NSBasicObjectID_h */
