//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef NSCloudKitMirroringDelegate_h
#define NSCloudKitMirroringDelegate_h
@import Foundation;

#include "CDDCloudKitClient.h"
#include "NSCloudKitMirroringActivityVoucherManager.h"
#include "NSCloudKitMirroringDelegateOptions.h"
#include "NSCloudKitMirroringDelegateProgressProvider-Protocol.h"
#include "NSCloudKitMirroringRequestManager.h"
#include "NSPersistentStoreCoordinator.h"
#include "NSPersistentStoreMirroringDelegate-Protocol.h"
#include "NSSQLCore.h"
#include "PFApplicationStateMonitor.h"
#include "PFApplicationStateMonitorDelegate-Protocol.h"
#include "PFCloudKitExporterDelegate-Protocol.h"
#include "PFCloudKitExporterOptions.h"
#include "PFCloudKitThrottledNotificationObserver.h"

@class CKContainer, CKDatabase, CKDatabaseSubscription, CKNotificationListener, CKRecordID, CKScheduler, NSError, NSObject, NSString;
@protocol OS_dispatch_queue, OS_dispatch_semaphore;

@interface NSCloudKitMirroringDelegate : NSObject<PFCloudKitExporterDelegate, PFApplicationStateMonitorDelegate, NSCloudKitMirroringDelegateProgressProvider, NSPersistentStoreMirroringDelegate> {
  /* instance variables */
  NSCloudKitMirroringDelegateOptions *_options;
  NSString *_ckDatabaseName;
  NSObject<OS_dispatch_semaphore> *_cloudKitQueueSemaphore;
  NSObject<OS_dispatch_queue> *_cloudKitQueue;
  CKDatabaseSubscription *_databaseSubscription;
  CKContainer *_container;
  CKDatabase *_database;
  CKScheduler *_scheduler;
  CKNotificationListener *_notificationListener;
  NSError *_lastInitializationError;
  BOOL _hadObservedStore;
  BOOL _successfullyInitialized;
  PFCloudKitExporterOptions *_exporterOptions;
  CDDCloudKitClient *_coredatadClient;
  BOOL _registeredForSubscription;
  BOOL _registeredForAccountChangeNotifications;
  BOOL _registeredForIdentityUpdateNotifications;
  NSSQLCore *_observedStore;
  NSPersistentStoreCoordinator *_observedCoordinator;
  PFCloudKitThrottledNotificationObserver *_accountChangeObserver;
  BOOL _setupFinishedMetadataInitialization;
  CKRecordID *_currentUserRecordID;
  NSCloudKitMirroringRequestManager *_requestManager;
  NSString *_observedStoreIdentifier;
  NSString *_importActivityIdentifier;
  NSString *_exportActivityIdentifier;
  NSString *_setupActivityIdentifier;
  NSString *_activityGroupName;
  NSObject *_sharingUIObserver;
  NSCloudKitMirroringActivityVoucherManager *_voucherManager;
}

@property (readonly, nonatomic) PFApplicationStateMonitor *applicationMonitor;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)printMetadataForStoreAtURL:(id)url withConfiguration:(id)configuration operateOnACopy:(BOOL)acopy;
+ (void)printRepresentativeSchemaForModelAtURL:(id)url orStoreAtURL:(id)url withConfiguration:(id)configuration;
+ (BOOL)checkAndCreateDirectoryAtURL:(id)url wipeIfExists:(BOOL)exists error:(id *)error;
+ (BOOL)checkIfContentsOfStore:(id)store matchContentsOfStore:(id)store error:(id *)error;
+ (BOOL)checkIfContentsOfStore:(id)store matchContentsOfStore:(id)store onlyCompareSharedZones:(BOOL)zones error:(id *)error;
+ (BOOL)traceObjectMatchingValue:(id)value atKeyPath:(id)path inStores:(id)stores startingAt:(id)at endingAt:(id)at error:(id *)error;
+ (BOOL)traceObjectMatchingRecordName:(id)name inStores:(id)stores startingAt:(id)at endingAt:(id)at error:(id *)error;
+ (BOOL)printEventsInStores:(id)stores startingAt:(id)at endingAt:(id)at error:(id *)error;
+ (BOOL)printSharedZoneWithName:(id)name inStoreAtURL:(id)url error:(id *)error;
+ (id)cloudKitMetadataTransformerName;
+ (id)cloudKitMachServiceName;
+ (id)createCloudKitServerWithMachServiceName:(id)name andStorageDirectoryPath:(id)path;
+ (void)initialize;
+ (id)stringForResetReason:(unsigned long long)reason;
+ (BOOL)isFirstPartyContainerIdentifier:(id)identifier;

/* instance methods */
- (id)initWithOptions:(id)options;
- (id)initWithCloudKitContainerOptions:(id)options;
- (void)dealloc;
- (BOOL)validateManagedObjectModel:(id)model forUseWithStoreWithDescription:(id)description error:(id *)error;
- (void)persistentStoreCoordinator:(id)coordinator didSuccessfullyAddPersistentStore:(id)store withDescription:(id)description;
- (void)coordinatorWillRemoveStore:(id)store;
- (void)storesDidChange:(id)change;
- (void)ckAccountOrIdentityChangedHandler:(id)handler;
- (void)logResetSyncNotification:(id)notification;
- (void)exporter:(id)exporter willScheduleOperations:(id)operations;
- (void)managedObjectContextSaved:(id)saved;
- (void)remoteStoreDidChange:(id)change;
- (void)eventUpdated:(id)updated;
- (void)addActivityVoucher:(id)voucher;
- (void)expireActivityVoucher:(id)voucher;
- (void)applicationStateMonitorEnteredBackground:(id)background;
- (void)applicationStateMonitorEnteredForeground:(id)foreground;
- (void)applicationStateMonitorExpiredBackgroundActivityTimeout:(id)timeout;
@end

#endif /* NSCloudKitMirroringDelegate_h */
