//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef NSSQLJoinIntermediate_h
#define NSSQLJoinIntermediate_h
@import Foundation;

#include "NSSQLIntermediate.h"
#include "NSSQLRelationship.h"

@class NSString;

@interface NSSQLJoinIntermediate : NSSQLIntermediate {
  /* instance variables */
  NSSQLRelationship *_relationship;
  NSString *_sourceAlias;
  NSString *_destinationAlias;
  NSString *_correlationAlias;
  unsigned long long _type;
  BOOL _direct;
}

/* instance methods */
- (void)dealloc;
- (id)description;
- (id)generateSQLStringInContext:(id)context;
@end

#endif /* NSSQLJoinIntermediate_h */
