//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 417.0.4.0.0
//
#ifndef NSString_XPCObject_h
#define NSString_XPCObject_h
@import Foundation;

@interface NSString (XPCObject)
/* instance methods */
- (id)_ni_initWithXPCObject:(id)xpcobject;
- (id)_ni_xpcObject;
@end

#endif /* NSString_XPCObject_h */
