//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2130.14.1.0.0
//
#ifndef CKAssetRepairOperationUtilities_h
#define CKAssetRepairOperationUtilities_h
@import Foundation;

@interface CKAssetRepairOperationUtilities : NSObject
/* class methods */
+ (id)createRepairOperationGroupWithName:(id)name;
+ (id)createRepairContainerFromContainer:(id)container;
+ (id)createRepairContainerFromContainer:(id)container withOverrides:(id)overrides;
+ (void)clearRepairZoneForDatabase:(id)database withRepairContainerOverrides:(id)overrides completionHandler:(id /* block */)handler;
+ (id)repairRecordFromRecord:(id)record field:(id)field listIndex:(long long)index repairZoneID:(id)id;
+ (id)uploadRequestMetadataFromRepairRecord:(id)record;
+ (BOOL)repairErrorShouldBeMarkedAsBroken:(id)broken;
+ (BOOL)errorIsRetriableInNearFuture:(id)future;
+ (BOOL)errorShouldTriggerNetworkReachabilityEvent:(id)event;
@end

#endif /* CKAssetRepairOperationUtilities_h */
