//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2130.14.1.0.0
//
#ifndef CKCompoundTypePredicateValidator_h
#define CKCompoundTypePredicateValidator_h
@import Foundation;

#include "CKPredicateValidatorInstance.h"

@interface CKCompoundTypePredicateValidator : CKPredicateValidatorInstance

@property (nonatomic) unsigned long long type;

/* instance methods */
- (id)initWithType:(unsigned long long)type;
- (BOOL)validate:(id)validate error:(id *)error;
- (id)CKPropertiesDescription;
@end

#endif /* CKCompoundTypePredicateValidator_h */
