//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2130.14.1.0.0
//
#ifndef CKObjCClass_h
#define CKObjCClass_h
@import Foundation;

@class NSArray, NSDictionary, NSString;

@interface CKObjCClass : NSObject {
  /* instance variables */
  NSDictionary *_propertiesByName;
  NSArray *_sortedProperties;
}

@property (readonly, nonatomic) Class handle;
@property (readonly, nonatomic) NSString *name;

/* class methods */
+ (id)classForHandle:(Class)handle;
+ (id)classForObject:(id)object;

/* instance methods */
- (id)initWithHandle:(Class)handle;
- (id)allProperties;
- (id)propertyForName:(id)name;
@end

#endif /* CKObjCClass_h */
