//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2130.14.1.0.0
//
#ifndef CKPackageUploadRequestMetadata_h
#define CKPackageUploadRequestMetadata_h
@import Foundation;

#include "CKUploadRequestMetadata.h"
#include "NSSecureCoding-Protocol.h"

@class NSArray;

@interface CKPackageUploadRequestMetadata : CKUploadRequestMetadata<NSSecureCoding>

@property (readonly, copy, nonatomic) NSArray *referenceSignatures;
@property (readonly, copy, nonatomic) NSArray *fileSignatures;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithRepairZoneRecordID:(id)id databaseScope:(long long)scope recordID:(id)id recordType:(id)type fieldName:(id)name;
- (id)initWithRepairZoneRecordID:(id)id databaseScope:(long long)scope recordID:(id)id recordType:(id)type fieldName:(id)name fileSignatures:(id)signatures referenceSignatures:(id)signatures;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)equal;
@end

#endif /* CKPackageUploadRequestMetadata_h */
