//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2130.14.1.0.0
//
#ifndef CKRecordChange_h
#define CKRecordChange_h
@import Foundation;

#include "CKPropertiesDescription-Protocol.h"
#include "CKRecord.h"
#include "CKRecordID.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSString;

@interface CKRecordChange : NSObject<CKPropertiesDescription, NSCopying, NSSecureCoding>

@property (readonly, nonatomic) long long changeType;
@property (readonly, copy, nonatomic) CKRecordID *recordID;
@property (readonly, copy, nonatomic) CKRecord *record;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithChangeType:(long long)type recordID:(id)id record:(id)record;
- (BOOL)isEqual:(id)equal;
- (void)CKDescribePropertiesUsing:(id)using;
- (id)redactedDescription;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
@end

#endif /* CKRecordChange_h */
