//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2130.14.1.0.0
//
#ifndef CKSyncEngineSentRecordZoneChangesEvent_h
#define CKSyncEngineSentRecordZoneChangesEvent_h
@import Foundation;

#include "CKSyncEngineEvent.h"

@class NSArray, NSDictionary;

@interface CKSyncEngineSentRecordZoneChangesEvent : CKSyncEngineEvent

@property (readonly, copy, nonatomic) NSArray *savedRecords;
@property (readonly, copy, nonatomic) NSArray *failedRecordSaves;
@property (readonly, copy, nonatomic) NSArray *deletedRecordIDs;
@property (readonly, copy, nonatomic) NSDictionary *failedRecordDeletes;

/* instance methods */
- (id)initWithSavedRecords:(id)records failedRecordSaves:(id)saves deletedRecordIDs:(id)ids failedRecordDeletes:(id)deletes;
- (long long)type;
- (void)CKDescribePropertiesUsing:(id)using;
@end

#endif /* CKSyncEngineSentRecordZoneChangesEvent_h */
