//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2130.14.1.0.0
//
#ifndef CKUploadRequestManager_h
#define CKUploadRequestManager_h
@import Foundation;

#include "CKContainer.h"
#include "CKSyncEngine.h"
#include "CKUploadRequestManagerInternals.h"
#include "CKUploadRequestManagerResponseActionThrottler.h"
#include "CKUploadRequestPersistentStore.h"

@class NSString;

@interface CKUploadRequestManager : NSObject

@property (readonly, nonatomic) CKUploadRequestManagerInternals *internals;
@property (readonly, nonatomic) CKSyncEngine *repairZoneSyncEngine;
@property (readonly, nonatomic) CKContainer *repairContainer;
@property (readonly, nonatomic) CKUploadRequestPersistentStore *database;
@property (readonly, nonatomic) CKUploadRequestManagerResponseActionThrottler *responseActionThrottler;
@property (copy) id /* block */ assetRequestCallback;
@property (copy) id /* block */ packageRequestCallback;
@property (copy) NSString *machServiceName;
@property (readonly, nonatomic) NSString *activityIdentifierForSchedulingRepairs;
@property (nonatomic) double recurringFetchPeriod;
@property (nonatomic) double tryAgainLaterRetryTime;
@property (nonatomic) double retryableErrorRetryTime;
@property (nonatomic) double cancelledErrorRetryTime;
@property (nonatomic) double retryableErrorMaxRetryCount;
@property (nonatomic) double notificationDebouncePeriod;
@property (nonatomic) long long assetRepairSchedulerRepairBatchCountLimit;
@property (nonatomic) double assetRepairSchedulerDefaultSuspensionTime;
@property (nonatomic) long long assetRepairSchedulerRepairRetryCount;

/* class methods */
+ (BOOL)ignoreUploadRequestPushNotifications;
+ (void)setIgnoreUploadRequestPushNotifications:(BOOL)notifications;
+ (id)activityIdentifierForSchedulingRepairsInContainer:(id)container;

/* instance methods */
- (void)dealloc;
- (id)initWithContainer:(id)container repairContainerOverrides:(id)overrides;
- (id)initWithContainer:(id)container repairContainerOverrides:(id)overrides ignoringSystemConditions:(BOOL)conditions;
- (void)registerForItemRequests;
- (void)unregister;
- (void)manuallyTriggerUploadRequests;
- (void)fetchServerChanges:(id /* block */)changes;
- (void)scheduleOrInvokeRepairsNow;
- (void)cancelAllOperations;
- (void)setCallback:(id /* block */)callback forOverridePoint:(long long)point;
@end

#endif /* CKUploadRequestManager_h */
