//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2130.14.1.0.0
//
#ifndef NSURL_CKUtilsAdditions_h
#define NSURL_CKUtilsAdditions_h
@import Foundation;

@interface NSURL (CKUtilsAdditions) <CKXPCSuitableString>
/* instance methods */
- (id)CKXPCSuitableString;
- (void)ck_bindInStatement:(id)statement atIndex:(unsigned long long)index;
- (id)CKShareURLSlugBasedApplicationName;
- (id)CKBladerunnerShareURLSlugBasedApplicationBundleID;
- (id)CKURLSlug;
- (id)CKURLThroughSlug;
- (id)CKPathAfterSlug;
- (id)CKSanitizedPath;
- (BOOL)CKMarkFilePurgeable:(id *)purgeable;
@end

#endif /* NSURL_CKUtilsAdditions_h */
