//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 5.2.12.0.0
//
#ifndef _TtC7SwiftUI28AccessibilityGeometryStorage_h
#define _TtC7SwiftUI28AccessibilityGeometryStorage_h
@import Foundation;

#include "_TtCs12_SwiftObject.h"

@interface SwiftUI.AccessibilityGeometryStorage : Swift._SwiftObject { // (Swift)
  /* instance variables */
   needsUpdatePath;
   needsUpdateFrame;
   transform;
   size;
   cachedFrame;
   viewResponders;
   observer;
   cachedPath;
   accessibilityNode;
}

@end

#endif /* _TtC7SwiftUI28AccessibilityGeometryStorage_h */
