//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 5.2.12.0.0
//
#ifndef _TtC7SwiftUIP33_9EE948773C43B4E002A1A22214C71CBE9FindClass_h
#define _TtC7SwiftUIP33_9EE948773C43B4E002A1A22214C71CBE9FindClass_h
@import Foundation;

@interface SwiftUI.(FindClass in _9EE948773C43B4E002A1A22214C71CBE) : NSObject // (Swift)
/* instance methods */
- (id)init;
@end

#endif /* _TtC7SwiftUIP33_9EE948773C43B4E002A1A22214C71CBE9FindClass_h */
