//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 5.2.12.0.0
//
#ifndef _TtC7SwiftUI16ScrollViewHelper_SwiftUI_h
#define _TtC7SwiftUI16ScrollViewHelper_SwiftUI_h
@import Foundation;

@interface SwiftUI.ScrollViewHelper (SwiftUI) <UIScrollViewDelegate, _UIUpdateCycleIdleObserver>
/* instance methods */
- (void)_updateCycleIdleUntil:(unsigned long long)until;
- (void)scrollViewWillBeginDragging:(id)dragging;
- (void)scrollViewWillEndDragging:(id)dragging withVelocity:(struct CGPoint { double x0; double x1; })velocity targetContentOffset:(struct CGPoint { double x0; double x1; } *)offset;
- (void)scrollViewDidEndDragging:(id)dragging willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(id)decelerating;
- (void)scrollViewDidEndScrollingAnimation:(id)animation;
- (BOOL)scrollViewShouldScrollToTop:(id)top;
@end

#endif /* _TtC7SwiftUI16ScrollViewHelper_SwiftUI_h */
