//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 290.153.3.50.1
//
#ifndef Core_Audio_Driver_Protocol_Protocol_h
#define Core_Audio_Driver_Protocol_Protocol_h
@import Foundation;

@protocol Core_Audio_Driver_Protocol 
/* instance methods */
- (void)initialize:(id)initialize reply:(id /* block */)reply;
- (void)perform_device_configuration_change:(unsigned int)perform_device_configuration_change action:(unsigned long long)action change:(unsigned long long)change reply:(id /* block */)reply;
- (void)abort_device_configuration_change:(unsigned int)abort_device_configuration_change action:(unsigned long long)action change:(unsigned long long)change reply:(id /* block */)reply;
- (void)add_device_client:(unsigned int)add_device_client client_info:(id)client_info reply:(id /* block */)reply;
- (void)remove_device_client:(unsigned int)remove_device_client client_info:(id)client_info reply:(id /* block */)reply;
- (void)create_device:(id)create_device client_info:(id)client_info reply:(id /* block */)reply;
- (void)destroy_device:(unsigned int)destroy_device reply:(id /* block */)reply;
- (void)object_was_destroyed:(unsigned int)object_was_destroyed reply:(id /* block */)reply;
- (void)start_io:(unsigned int)start_io client_id:(unsigned int)client_id reply:(id /* block */)reply;
- (void)stop_io:(unsigned int)stop_io client_id:(unsigned int)client_id reply:(id /* block */)reply;
- (void)start_synchronous_messenger:(unsigned int)start_synchronous_messenger client_id:(unsigned int)client_id nominal_sample_rate:(double)nominal_sample_rate io_buffer_frame_size:(unsigned int)io_buffer_frame_size work_group_port:(id)work_group_port io_messenger:(id)io_messenger reply:(id /* block */)reply;
- (void)stop_synchronous_messenger:(unsigned int)stop_synchronous_messenger client_id:(unsigned int)client_id reply:(id /* block */)reply;
- (void)register_io_buffer:(id)register_io_buffer reply:(id /* block */)reply;
- (void)unregister_io_buffer:(id)unregister_io_buffer reply:(id /* block */)reply;
- (void)retain_reply_for_process_boost:(id /* block */)retain_reply_for_process_boost;
- (void)has_property:(struct Driver_Property_Identity { unsigned int x0; int x1; struct AudioObjectPropertyAddress { unsigned int x0; unsigned int x1; unsigned int x2; } x2; })has_property reply:(id /* block */)reply;
- (void)is_property_settable:(struct Driver_Property_Identity { unsigned int x0; int x1; struct AudioObjectPropertyAddress { unsigned int x0; unsigned int x1; unsigned int x2; } x2; })is_property_settable reply:(id /* block */)reply;
- (void)get_property_data_size:(struct Driver_Property_Identity { unsigned int x0; int x1; struct AudioObjectPropertyAddress { unsigned int x0; unsigned int x1; unsigned int x2; } x2; })get_property_data_size qualifier:(id)qualifier reply:(id /* block */)reply;
- (void)get_property_data:(struct Driver_Property_Identity { unsigned int x0; int x1; struct AudioObjectPropertyAddress { unsigned int x0; unsigned int x1; unsigned int x2; } x2; })get_property_data qualifier:(id)qualifier data_size:(unsigned int)data_size reply:(id /* block */)reply;
- (void)set_property_data:(struct Driver_Property_Identity { unsigned int x0; int x1; struct AudioObjectPropertyAddress { unsigned int x0; unsigned int x1; unsigned int x2; } x2; })set_property_data qualifier:(id)qualifier data:(id)data reply:(id /* block */)reply;
@end

#endif /* Core_Audio_Driver_Protocol_Protocol_h */
