//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HKConceptStore_h
#define HKConceptStore_h
@import Foundation;

#include "HKConceptStoreClientInterface-Protocol.h"
#include "HKHealthStore.h"
#include "HKObserverSet.h"
#include "HKTaskServerProxyProvider.h"
#include "_HKXPCExportable-Protocol.h"

@class NSString, NSUUID;

@interface HKConceptStore : NSObject<_HKXPCExportable, HKConceptStoreClientInterface> {
  /* instance variables */
  HKObserverSet *_conceptObservers;
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _conceptIndexManagerStateLock;
  unsigned long long _lastKnownConceptIndexManagerState;
}

@property (retain, nonatomic) HKHealthStore *healthStore;
@property (retain, nonatomic) NSUUID *identifier;
@property (retain, nonatomic) HKTaskServerProxyProvider *proxyProvider;
@property (readonly, nonatomic) unsigned long long currentConceptIndexerState;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)taskServerIdentifier;
+ (id)serverInterface;
+ (id)clientInterface;

/* instance methods */
- (id)init;
- (id)initWithHealthStore:(id)store;
- (void)_startObservingConceptIndexManager;
- (void)startObservingConceptIndexManagerWithCompletion:(id /* block */)completion;
- (void)fetchConceptForIdentifier:(id)identifier loadRelationships:(BOOL)relationships completionHandler:(id /* block */)handler;
- (id)countOfConceptsAssociatedToUserRecordsWithError:(id *)error;
- (void)fetchConceptIndexerStateWithCompletion:(id /* block */)completion;
- (void)registerAsConceptObserver:(id)observer onQueue:(id)queue;
- (void)unregisterAsConceptObserver:(id)observer;
- (void)clientRemote_conceptIndexManagerDidChangeState:(unsigned long long)state;
- (id)exportedInterface;
- (id)remoteInterface;
- (void)connectionInvalidated;
@end

#endif /* HKConceptStore_h */
