//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HKFeatureAvailabilityRequirements_h
#define HKFeatureAvailabilityRequirements_h
@import Foundation;

@interface HKFeatureAvailabilityRequirements : NSObject
/* class methods */
+ (id)activeRemoteDeviceIsPresentWhenRequiredForRegionAvailabilityOrDeviceCapabilityForFeatureWithIdentifier:(id)identifier;
+ (id)bloodOxygenMeasurementsAreEnabled;
+ (id)capabilityIsSupportedOnActiveRemoteDeviceForFeatureWithIdentifier:(id)identifier;
+ (id)capabilityIsSupportedOnActiveWatchForFeatureWithIdentifier:(id)identifier supportedOnLocalDevice:(BOOL)device;
+ (id)capabilityIsSupportedOnAnyWatch:(id)watch supportedOnLocalDevice:(BOOL)device;
+ (id)countryCodeIsPresentForFeatureWithIdentifier:(id)identifier;
+ (id)countryIsSupportedOnActiveRemoteDeviceForFeatureWithIdentifier:(id)identifier isSupportedIfCountryListMissing:(BOOL)missing;
+ (id)countryIsSupportedOnLocalDeviceForFeatureWithIdentifier:(id)identifier;
+ (id)featureFlagIsEnabled:(BOOL)enabled;
+ (id)featureIsNotRemotelyDisabledWithIdentifier:(id)identifier;
+ (id)featureIsOnWithIdentifier:(id)identifier isOnIfSettingIsAbsent:(BOOL)absent;
+ (id)featureIsOnWithIdentifier:(id)identifier settingsKey:(id)key isOnIfSettingIsAbsent:(BOOL)absent;
+ (id)healthAppIsNotHidden;
+ (id)heartRateIsEnabledInPrivacy;
+ (id)localDeviceIsCapableOfPairingWithWatch;
+ (id)localDeviceIsCapableOfWatchPairing;
+ (id)mutuallyExclusiveFeatureIsOffWithIdentifier:(id)identifier;
+ (id)notAgeGatedForUserDefaultsKey:(id)key;
+ (id)notInStoreDemoMode;
+ (id)onboardedAtLeastDaysAgo:(long long)ago featureIdentifier:(id)identifier;
+ (id)onboardingRecordsArePresentForPrerequisiteFeaturesWithIdentifiers:(id)identifiers;
+ (id)onboardingRecordIsNotPresentForFeatureWithIdentifier:(id)identifier;
+ (id)onboardingRecordIsNotPresentForMutuallyExclusiveFeatureWithIdentifier:(id)identifier;
+ (id)onboardingRecordIsPresentForFeatureWithIdentifier:(id)identifier;
+ (id)prerequisiteFeaturesAreOnWithFeatureSettings:(id)settings;
+ (id)profileIsNotFamilySetupPairingProfile;
+ (id)seedIsNotExpiredForFeatureWithIdentifier:(id)identifier;
+ (id)watchAppIsInstalledForBundleIdentifier:(id)identifier;
+ (id)watchLowPowerModeIsOff;
+ (id)wristDetectionIsEnabledForActiveWatch;
+ (id)countryIsSupportedOnWatchForFeatureWithIdentifier:(id)identifier isSupportedIfCountryListMissing:(BOOL)missing;
+ (id)countryIsSupportedOnLocalDeviceAndPhoneForFeatureWithIdentifier:(id)identifier isSupportedIfCountryListMissing:(BOOL)missing;
+ (id)defaultOnboardingEligibilityRequirementsForFeatureIdentifier:(id)identifier;
+ (id)defaultHelpTileRequirementsForBackgroundDeliveredFeatureWithFeatureIdentifier:(id)identifier isAgeGatedUserDefaultsKey:(id)key;
+ (id)defaultTipsAppVisibilityRequirementsForBackgroundDeliveredFeatureWithFeatureIdentifier:(id)identifier isAgeGatedUserDefaultsKey:(id)key;
@end

#endif /* HKFeatureAvailabilityRequirements_h */
