//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HKGlassesLensSpecification_h
#define HKGlassesLensSpecification_h
@import Foundation;

#include "HKLensSpecification.h"
#include "HKQuantity.h"
#include "HKVisionPrism.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@interface HKGlassesLensSpecification : HKLensSpecification<NSSecureCoding, NSCopying>

@property (readonly, copy, nonatomic) HKQuantity *vertexDistance;
@property (readonly, copy, nonatomic) HKVisionPrism *prism;
@property (readonly, copy, nonatomic) HKQuantity *farPupillaryDistance;
@property (readonly, copy, nonatomic) HKQuantity *nearPupillaryDistance;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithSphere:(id)sphere cylinder:(id)cylinder axis:(id)axis addPower:(id)power vertexDistance:(id)distance prism:(id)prism farPupillaryDistance:(id)distance nearPupillaryDistance:(id)distance;
- (id)description;
- (BOOL)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
@end

#endif /* HKGlassesLensSpecification_h */
