//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HKProfileStore_h
#define HKProfileStore_h
@import Foundation;

#include "HKProfileStoreClient-Protocol.h"
#include "HKProxyProvider.h"
#include "_HKXPCExportable-Protocol.h"

@class NSString;
@protocol HKObserverSet<HKProfileStoreObserver;

@interface HKProfileStore : NSObject<_HKXPCExportable, HKProfileStoreClient> {
  /* instance variables */
  HKProxyProvider *_proxyProvider;
  HKObserverSet<HKProfileStoreObserver> *_observers;
  BOOL _startedObserving;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)taskIdentifier;

/* instance methods */
- (id)initWithHealthStore:(id)store;
- (void)createProfileOfType:(long long)type displayName:(id)name completion:(id /* block */)completion;
- (void)deleteProfile:(id)profile completion:(id /* block */)completion;
- (void)fetchAllProfilesWithCompletion:(id /* block */)completion;
- (void)fetchProfileIdentifierForNRDeviceUUID:(id)uuid completion:(id /* block */)completion;
- (void)fetchProfileIdentifierForNRDeviceUUID:(id)uuid ownerAppleID:(id)id completion:(id /* block */)completion;
- (id)synchronouslyFetchFirstName;
- (void)fetchDisplayName:(id /* block */)name;
- (void)setDisplayFirstName:(id)name lastName:(id)name completion:(id /* block */)completion;
- (void)fetchDisplayImageData:(id /* block */)data;
- (void)setDisplayImageData:(id)data completion:(id /* block */)completion;
- (void)_getSynchronousProxyWithHandler:(id /* block */)handler errorHandler:(id /* block */)handler;
- (void)_fetchProxyWithHandler:(id /* block */)handler errorHandler:(id /* block */)handler;
- (void)fetchSharingInformationForProfileIdentifier:(id)identifier completion:(id /* block */)completion;
- (void)startObservingWithCompletion:(id /* block */)completion;
- (void)addObserver:(id)observer completion:(id /* block */)completion;
- (void)removeObserver:(id)observer;
- (void)client_remoteDidUpdateProfileList;
- (void)dispatchProfileListDidUpdate;
- (void)connectionInvalidated;
- (id)exportedInterface;
- (id)remoteInterface;
@end

#endif /* HKProfileStore_h */
