//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HKQuantitySample_h
#define HKQuantitySample_h
@import Foundation;

#include "HKSample.h"
#include "HKQuantity.h"
#include "HKQuantityType.h"

@class HDCodableQuantitySample;

@interface HKQuantitySample : HKSample {
  /* instance variables */
  long long _freezeState;
}

@property (nonatomic) BOOL frozen;
@property (retain, nonatomic) HDCodableQuantitySample *codableQuantitySample;
@property (readonly, copy) HKQuantityType *quantityType;
@property (readonly, copy) HKQuantity *quantity;
@property (readonly) long long count;

/* class methods */
+ (id)quantitySampleWithType:(id)type quantity:(id)quantity startDate:(id)date endDate:(id)date device:(id)device metadata:(id)metadata;
+ (id)quantitySampleWithType:(id)type quantity:(id)quantity startDate:(id)date endDate:(id)date metadata:(id)metadata;
+ (id)quantitySampleWithType:(id)type quantity:(id)quantity startDate:(id)date endDate:(id)date;
+ (id)_unfrozenQuantitySampleWithQuantityType:(id)type quantity:(id)quantity startDate:(id)date device:(id)device;
+ (BOOL)_isConcreteObjectClass;
+ (id)_quantitySamplesEnforcingDurationWithType:(id)type quantity:(id)quantity startDate:(id)date endDate:(id)date device:(id)device metadata:(id)metadata;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)asJSONObject;
- (id)_init;
- (BOOL)_shouldNotifyOnInsert;
- (id)_validateWithConfiguration:(struct HKObjectValidationConfiguration { unsigned long long x0; unsigned int x1; })configuration;
- (id)_valueDescription;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (void)_setQuantity:(id)quantity;
- (BOOL)_frozen;
- (void)_setFrozen:(BOOL)frozen;
- (void)_setFreezing;
- (void)_setCount:(long long)count;
- (long long)_compareFreezeStateWithSample:(id)sample;
- (void)_setCodableQuantitySample:(id)sample;
@end

#endif /* HKQuantitySample_h */
