//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HKSampleIteratorQuery_h
#define HKSampleIteratorQuery_h
@import Foundation;

#include "HKQuery.h"
#include "HKSampleIteratorQueryClientInterface-Protocol.h"
#include "HKSampleIteratorQueryCursor.h"

@class NSMutableArray, NSString;

@interface HKSampleIteratorQuery : HKQuery<HKSampleIteratorQueryClientInterface> {
  /* instance variables */
  NSMutableArray *_samplesPendingDelivery;
}

@property (copy, nonatomic) HKSampleIteratorQueryCursor *queryCursor;
@property (nonatomic) unsigned long long limit;
@property (readonly, copy, nonatomic) id /* block */ resultsHandler;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (Class)configurationClass;
+ (id)clientInterfaceProtocol;
+ (void)configureClientInterface:(id)interface;

/* instance methods */
- (id)init;
- (id)initWithQueryDescriptors:(id)descriptors sortDescriptors:(id)descriptors followingAnchor:(id)anchor upToAndIncludingAnchor:(id)anchor distinctByKeyPaths:(id)paths limit:(unsigned long long)limit resultsHandler:(id /* block */)handler;
- (id)initWithQueryCursor:(id)cursor limit:(unsigned long long)limit resultsHandler:(id /* block */)handler;
- (void)client_deliverSampleObjects:(id)objects queryCursor:(id)cursor deliverResults:(BOOL)results query:(id)query;
- (void)queue_populateConfiguration:(id)configuration;
- (void)queue_queryDidDeactivate:(id)deactivate;
- (void)queue_validate;
- (void)queue_deliverError:(id)error;
@end

#endif /* HKSampleIteratorQuery_h */
