//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HKSourceQuery_h
#define HKSourceQuery_h
@import Foundation;

#include "HKQuery.h"
#include "HKQueryServerInterface-Protocol.h"
#include "HKSourceQueryClientInterface-Protocol.h"

@class NSString;

@interface HKSourceQuery : HKQuery<HKSourceQueryClientInterface> {
  /* instance variables */
  BOOL _hasDeliveredInitialResults;
  NSObject<HKQueryServerInterface> *_serverProxy;
}

@property (readonly, nonatomic) id /* block */ completionHandler;
@property (copy, nonatomic) id /* block */ updateHandler;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)clientInterfaceProtocol;
+ (void)configureClientInterface:(id)interface;
+ (void)configureServerInterface:(id)interface;

/* instance methods */
- (id)initWithSampleType:(id)type samplePredicate:(id)predicate completionHandler:(id /* block */)handler;
- (void)queue_deliverError:(id)error;
- (void)queue_validate;
- (void)queue_queryDidDeactivate:(id)deactivate;
- (BOOL)queue_shouldDeactivateAfterInitialResults;
- (void)client_deliverSources:(id)sources forQuery:(id)query;
- (void)client_deliverUpdatedSources:(id)sources added:(id)added forQuery:(id)query;
@end

#endif /* HKSourceQuery_h */
