//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef NSDateComponents_HKDayIndex_h
#define NSDateComponents_HKDayIndex_h
@import Foundation;

@interface NSDateComponents (HKDayIndex)
/* class methods */
+ (id)hk_componentsWithHour:(long long)hour minute:(long long)minute;
+ (id)hk_oneDay;
+ (id)hk_oneWeek;
+ (id)hk_componentsWithDays:(long long)days;
+ (id)hk_dateComponentsForCalendarUnit:(unsigned long long)unit;
+ (id)hk_componentsWithDayIndex:(long long)index calendar:(id)calendar;

/* instance methods */
- (id)hk_hourNumber;
- (id)hk_minuteNumber;
- (id)hk_dateOptionalDescription;
- (double)hk_approximateDuration;
- (id)hk_dateByAddingInterval:(long long)interval toDate:(id)date;
- (id)_hk_dateByAddingFilteredInterval:(long long)interval toDate:(id)date;
- (id)_hk_dateComponentsMultipliedByCount:(long long)count;
- (long long)hk_maxComponentValue;
- (id)hk_populatedCalendarGregorianCalendarDefault;
- (id)hk_translateDateComponentsToCalendar:(id)calendar calendarUnits:(unsigned long long)units;
- (id)hk_negativeComponents;
- (long long)hk_ageWithCurrentDate:(id)date;
- (id)hk_dateIntervalForDate:(id)date anchorDate:(id)date outIndex:(long long *)index;
- (long long)hk_indexForDate:(id)date anchorDate:(id)date;
- (long long)hk_dayIndex;
- (id)hk_dayIndexDateDescription;
@end

#endif /* NSDateComponents_HKDayIndex_h */
