//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef NSKeyedUnarchiver_HealthKit_h
#define NSKeyedUnarchiver_HealthKit_h
@import Foundation;

@interface NSKeyedUnarchiver (HealthKit)
/* class methods */
+ (id)hk_unarchivedObjectOfClass:(Class)class forKey:(id)key data:(id)data error:(id *)error;
+ (id)hk_unarchivedObjectOfClasses:(id)classes forKey:(id)key data:(id)data error:(id *)error;
+ (BOOL)_hk_performUnarchivingWithData:(id)data error:(id *)error handler:(id /* block */)handler;
@end

#endif /* NSKeyedUnarchiver_HealthKit_h */
