//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INUIExtensionRequestInfo_h
#define INUIExtensionRequestInfo_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class INInteraction;

@interface INUIExtensionRequestInfo : NSObject<NSSecureCoding, NSCopying>

@property (readonly, nonatomic) INInteraction *interaction;
@property (nonatomic) BOOL requiresUserConsent;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithInteraction:(id)interaction;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* INUIExtensionRequestInfo_h */
