//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INUIVoiceShortcutHostContext_h
#define INUIVoiceShortcutHostContext_h
@import Foundation;

#include "NSExtensionContext.h"
#include "INUIVoiceShortcutRemoteHostingInterface-Protocol.h"

@class NSString;

@interface INUIVoiceShortcutHostContext : NSExtensionContext<INUIVoiceShortcutRemoteHostingInterface>

@property (weak, nonatomic) NSObject<INUIVoiceShortcutRemoteHostingInterface> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)_extensionAuxiliaryVendorProtocol;
+ (id)_extensionAuxiliaryHostProtocol;
+ (id)_allowedItemPayloadClasses;

/* instance methods */
- (void)remoteViewControllerDidCancel;
- (void)remoteViewControllerDidCreateVoiceShortcut:(id)shortcut error:(id)error;
- (void)remoteViewControllerDidUpdateVoiceShortcut:(id)shortcut error:(id)error;
- (void)remoteViewControllerDidDeleteVoiceShortcutWithIdentifier:(id)identifier;
@end

#endif /* INUIVoiceShortcutHostContext_h */
