//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 161.0.0.0.0
//
#ifndef MTKTextureIOBufferMap_h
#define MTKTextureIOBufferMap_h
@import Foundation;

#include "TXRBufferMap-Protocol.h"

@class NSString;

@interface MTKTextureIOBufferMap : NSObject<TXRBufferMap>

@property (readonly, nonatomic) void * bytes;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithContents:(void *)contents;
@end

#endif /* MTKTextureIOBufferMap_h */
