//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1228.300.81.0.0
//
#ifndef CXCallObserverDataSource_Protocol_h
#define CXCallObserverDataSource_Protocol_h
@import Foundation;

@protocol CXCallObserverDataSource <NSObject>

@property (readonly, copy, nonatomic) NSDictionary *callUUIDToCallMap;

/* instance methods */
- (void)addDelegate:(id)delegate;
- (void)removeDelegate:(id)delegate;
- (void)requestTransaction:(id)transaction completion:(id /* block */)completion;
- (void)invalidate;
@end

#endif /* CXCallObserverDataSource_Protocol_h */
