//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1228.300.81.0.0
//
#ifndef CXVoicemailObserver_h
#define CXVoicemailObserver_h
@import Foundation;

#include "CXVoicemailObserverDataSource-Protocol.h"
#include "CXVoicemailObserverDataSourceDelegate-Protocol.h"

@class NSArray, NSString;
@protocol CXVoicemailObserverDelegate, OS_dispatch_queue;

@interface CXVoicemailObserver : NSObject<CXVoicemailObserverDataSourceDelegate>

@property (weak, nonatomic) NSObject<CXVoicemailObserverDelegate> *delegate;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *delegateQueue;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (readonly, nonatomic) NSObject<CXVoicemailObserverDataSource> *dataSource;
@property (readonly, copy, nonatomic) NSArray *voicemails;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (id)initWithDataSource:(id)source queue:(id)queue;
- (void)dealloc;
- (void)setDelegate:(id)delegate queue:(id)queue;
- (void)_performDelegateCallback:(id /* block */)callback;
- (void)dataSourceVoicemailsChanged:(id)changed;
@end

#endif /* CXVoicemailObserver_h */
