//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1420.3.0.0.0
//
#ifndef CIBurstImageSet_h
#define CIBurstImageSet_h
@import Foundation;

#include "CIBurstImageSetInternal.h"

@interface CIBurstImageSet : NSObject {
  /* instance variables */
  CIBurstImageSetInternal *_priv;
}

/* class methods */
+ (id)burstImageSet;
+ (id)burstImageSetWithOptions:(id)options;
+ (id)defaultVersionString;

/* instance methods */
- (void)dealloc;
- (id)init;
- (id)initWithOptions:(id)options;
- (id)burstId;
- (void)addImageFromIOSurface:(struct __IOSurface *)iosurface properties:(id)properties identifier:(id)identifier completionBlock:(id /* block */)block;
- (id)bestImageIdentifiers;
- (id)coverImageIdentifier;
- (id)imageClusterForIdentifier:(id)identifier;
- (unsigned long long)imageClusterCount;
- (id)imageClusterForIndex:(unsigned long long)index;
- (id)allImageIdentifiers;
- (id)statsForImageWithIdentifier:(id)identifier;
- (double)secondsSinceStart;
- (void)setLoggingListener:(void *)listener withUserInfo:(void *)info;
- (BOOL)isPortrait;
- (BOOL)isAction;
@end

#endif /* CIBurstImageSet_h */
