//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1420.3.0.0.0
//
#ifndef CIDepthEffectApplyBlurMap_h
#define CIDepthEffectApplyBlurMap_h
@import Foundation;

#include "CIFilter.h"
#include "CIImage.h"

@class NSNumber, NSString;

@interface CIDepthEffectApplyBlurMap : CIFilter

@property (retain) CIImage *inputImage;
@property (retain) CIImage *inputBlurMap;
@property (retain) CIImage *inputMatteImage;
@property (retain) CIImage *inputGainMap;
@property (copy, nonatomic) NSNumber *inputAperture;
@property (copy, nonatomic) NSNumber *inputLumaNoiseScale;
@property (retain, nonatomic) NSNumber *inputScale;
@property (retain, nonatomic) id inputAuxDataMetadata;
@property (retain, nonatomic) NSString *inputShape;
@property (retain, nonatomic) NSNumber *inputDraftMode;
@property (retain, nonatomic) NSNumber *inputBestHairQuality;
@property (retain, nonatomic) NSString *inputCaptureFolderMiscPath;

/* class methods */
+ (id)customAttributes;

/* instance methods */
- (id)alterBlurmap;
- (id)unifiedRenderingOutputImage:(struct CGImageMetadata *)image;
- (id)outputImage;
@end

#endif /* CIDepthEffectApplyBlurMap_h */
