//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1420.3.0.0.0
//
#ifndef CIDocumentEnhancer_h
#define CIDocumentEnhancer_h
@import Foundation;

#include "CIFilter.h"
#include "CIImage.h"

@class NSNumber;

@interface CIDocumentEnhancer : CIFilter

@property (retain, nonatomic) CIImage *inputImage;
@property (copy, nonatomic) NSNumber *inputAmount;

/* class methods */
+ (id)customAttributes;

/* instance methods */
- (id)outputImage;
@end

#endif /* CIDocumentEnhancer_h */
