//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 599.201.0.0.0
//
#ifndef _SCNExportOperation_h
#define _SCNExportOperation_h
@import Foundation;

#include "SCNExportOperation.h"
#include "SCNNode.h"
#include "SCNRenderer.h"
#include "SCNScene.h"

@class NSDictionary, NSError, NSURL;

@interface _SCNExportOperation : SCNExportOperation {
  /* instance variables */
  double _systemTime;
}

@property (nonatomic) id delegate;
@property (nonatomic) void * userInfo;
@property (nonatomic) SEL didEndSelector;
@property (retain, nonatomic) SCNScene *scene;
@property (nonatomic) struct CGSize { double x0; double x1; } size;
@property (nonatomic) double startTime;
@property (nonatomic) double endTime;
@property (nonatomic) double progress;
@property (nonatomic) BOOL canceled;
@property (nonatomic) BOOL succeded;
@property (retain, nonatomic) NSDictionary *attributes;
@property (retain, nonatomic) NSURL *outputURL;
@property (retain, nonatomic) SCNNode *pointOfView;
@property (retain, nonatomic) NSError *error;
@property (nonatomic) unsigned long long antialiasingMode;
@property (retain, nonatomic) SCNRenderer *renderer;

/* instance methods */
- (void)dealloc;
- (void)cancel;
@end

#endif /* _SCNExportOperation_h */
