//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 599.201.0.0.0
//
#ifndef SCNCommonProfileProgramGenerator_h
#define SCNCommonProfileProgramGenerator_h
@import Foundation;

@interface SCNCommonProfileProgramGenerator : NSObject {
  /* instance variables */
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _programMutex;
  struct __CFDictionary * _shaders;
  struct __CFDictionary * _trackedResourcesToHashcode;
}

@property (readonly, nonatomic) int profile;

/* class methods */
+ (id)generatorWithProfile:(int)profile allowingHotReload:(BOOL)reload;

/* instance methods */
- (id)init;
- (void)dealloc;
- (void)emptyShaderCache;
- (struct __C3DFXProgram *)programWithHashCode:(struct __C3DProgramHashCode *)code engineContext:(struct __C3DEngineContext *)context trackedResource:(id)resource introspectionDataPtr:(void *)ptr;
- (void)releaseProgramForResource:(id)resource;
@end

#endif /* SCNCommonProfileProgramGenerator_h */
