//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 599.201.0.0.0
//
#ifndef SCNIKJoint_h
#define SCNIKJoint_h
@import Foundation;

#include "SCNNode.h"

@interface SCNIKJoint : NSObject

@property (nonatomic) SCNNode *joint;
@property (nonatomic) double maxAllowedRotationAngle;

@end

#endif /* SCNIKJoint_h */
