//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 599.201.0.0.0
//
#ifndef SCNPhysicsBallSocketJointJSExport_Protocol_h
#define SCNPhysicsBallSocketJointJSExport_Protocol_h
@import Foundation;

@protocol SCNPhysicsBallSocketJointJSExport <JSExport>

@property (readonly, nonatomic) SCNPhysicsBody *bodyA;
@property (nonatomic) struct SCNVector3 { float x0; float x1; float x2; } anchorA;
@property (readonly, nonatomic) SCNPhysicsBody *bodyB;
@property (nonatomic) struct SCNVector3 { float x0; float x1; float x2; } anchorB;

/* class methods */
+ (id)jointWithBodyA:(id)a anchorA:(struct SCNVector3 { float x0; float x1; float x2; })a bodyB:(id)b anchorB:(struct SCNVector3 { float x0; float x1; float x2; })b;
+ (id)jointWithBody:(id)body anchor:(struct SCNVector3 { float x0; float x1; float x2; })anchor;
@end

#endif /* SCNPhysicsBallSocketJointJSExport_Protocol_h */
