//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2274.8.0.0.0
//
#ifndef _CSMultiQuery_h
#define _CSMultiQuery_h
@import Foundation;

@class NSArray, NSMutableArray;
@protocol OS_dispatch_group, OS_dispatch_queue;

@interface _CSMultiQuery : NSObject {
  /* instance variables */
  BOOL _started;
}

@property (retain, nonatomic) NSObject<OS_dispatch_group> *group;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) id completionHandler;
@property (nonatomic) BOOL simple;
@property (retain, nonatomic) NSMutableArray *simpleQueryTokens;
@property (retain, nonatomic) NSArray *queries;
@property (retain, nonatomic) NSMutableArray *results;

/* class methods */
+ (void)initialize;
+ (id)countingQueryWithStrings:(id)strings contexts:(id)contexts completionHandler:(id /* block */)handler;
+ (id)countingQueryWithStrings:(id)strings context:(id)context completionHandler:(id /* block */)handler;
+ (id)countingQueryWithSuggestions:(id)suggestions context:(id)context completionHandler:(id /* block */)handler;
+ (id)countingQueryForEmailsArrays:(id)arrays scope:(unsigned long long)scope context:(id)context contextualFilterQueries:(id)queries includeSecondaryRecipients:(BOOL)recipients completionHandler:(id /* block */)handler;
+ (id)countingQueryWithPeopleSuggestions:(id)suggestions filterQuery:(id)query context:(id)context completionHandler:(id /* block */)handler;

/* instance methods */
- (id)initWithSimpleQueries:(id)queries completionHandler:(id /* block */)handler;
- (id)initWithQueries:(id)queries completionHandler:(id /* block */)handler;
- (void)start;
- (void)startSimpleQueryAtIndex:(unsigned long long)index;
- (void)cancel;
@end

#endif /* _CSMultiQuery_h */
