//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2274.8.0.0.0
//
#ifndef CSDataWrapper_h
#define CSDataWrapper_h
@import Foundation;

@class NSData;
@protocol OS_xpc_object;

@interface CSDataWrapper : NSObject

@property (readonly, nonatomic) NSData *data;
@property (readonly, nonatomic) NSObject<OS_xpc_object> *xpcData;
@property (readonly, nonatomic) const void * dataPtr;
@property (nonatomic) unsigned long long dataSize;
@property (readonly, nonatomic) unsigned long long mapSize;
@property (readonly, nonatomic) BOOL mapped;

/* instance methods */
- (id)initWithXPCValue:(id)xpcvalue allowWritableSharedMemory:(BOOL)memory;
- (id)initWithXPCValue:(id)xpcvalue;
- (id)initWithData:(id)data;
- (void)dealloc;
@end

#endif /* CSDataWrapper_h */
