//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2274.8.0.0.0
//
#ifndef MDSearchQuery_h
#define MDSearchQuery_h
@import Foundation;

#include "CSSearchQuery.h"

@class NSDictionary, NSPredicate, NSString;
@protocol MDSearchQueryDelegate, OS_dispatch_queue;

@interface MDSearchQuery : NSObject

@property (copy) NSPredicate *predicate;
@property unsigned long long status;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) CSSearchQuery *query;
@property (retain) NSString *clientBundleID;
@property (readonly, copy) NSDictionary *options;
@property (weak) NSObject<MDSearchQueryDelegate> *delegate;

/* instance methods */
- (id)initWithPredicate:(id)predicate options:(id)options;
- (id)initWithQueryString:(id)string options:(id)options;
- (id)queryString;
- (void)start;
- (void)cancel;
- (void)_didReturnItems:(id)items;
- (void)_didFinishWithError:(id)error;
@end

#endif /* MDSearchQuery_h */
