//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef ASPublicKeyCredentialBase_h
#define ASPublicKeyCredentialBase_h
@import Foundation;

#include "ASPublicKeyCredential-Protocol.h"

@class NSData, NSString;

@interface ASPublicKeyCredentialBase : NSObject<ASPublicKeyCredential>

@property (nonatomic) long long attachment;
@property (readonly, copy, nonatomic) NSData *rawClientDataJSON;
@property (readonly, copy, nonatomic) NSData *credentialID;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithCredentialID:(id)id rawClientDataJSON:(id)json attachment:(long long)attachment;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
@end

#endif /* ASPublicKeyCredentialBase_h */
