//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 491.7.0.0.0
//
#ifndef NSString_UserNotificationsInternal_h
#define NSString_UserNotificationsInternal_h
@import Foundation;

@interface NSString (UserNotificationsInternal)
/* class methods */
+ (id)localizedUserNotificationStringForKey:(id)key arguments:(id)arguments;

/* instance methods */
- (id)un_logDigest;
- (BOOL)un_isFirstPartyIdentifier;
- (id)un_localizedStringArguments;
- (id)un_localizedStringKey;
- (id)un_localizedStringValue;
- (unsigned long long)un_unsignedLongLongValue;
- (id)un_stringWithMaxLength:(unsigned long long)length;
@end

#endif /* NSString_UserNotificationsInternal_h */
