//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 491.7.0.0.0
//
#ifndef UNNotificationContent_h
#define UNNotificationContent_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSMutableCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "UNNotificationIcon.h"
#include "UNNotificationSecurityScopeProviding-Protocol.h"
#include "UNNotificationSound.h"
#include "_UNNotificationCommunicationContext.h"

@class NSArray, NSDate, NSDictionary, NSNumber, NSSet, NSString, NSURL;

@interface UNNotificationContent : NSObject<UNNotificationSecurityScopeProviding, NSCopying, NSMutableCopying, NSSecureCoding>

@property (retain, nonatomic) NSString *markedMutableCopyMessage;
@property (readonly, copy, nonatomic) NSString *contentType;
@property (readonly, copy, nonatomic) _UNNotificationCommunicationContext *communicationContext;
@property (readonly, copy, nonatomic) NSString *header;
@property (readonly, copy, nonatomic) NSString *footer;
@property (readonly, nonatomic) BOOL shouldIgnoreDoNotDisturb;
@property (readonly, nonatomic) BOOL shouldIgnoreDowntime;
@property (readonly, nonatomic) BOOL shouldSuppressScreenLightUp;
@property (readonly, nonatomic) BOOL shouldHideDate;
@property (readonly, copy, nonatomic) NSDate *date;
@property (readonly, copy, nonatomic) NSDate *expirationDate;
@property (readonly, nonatomic) BOOL shouldAuthenticateDefaultAction;
@property (readonly, nonatomic) BOOL shouldBackgroundDefaultAction;
@property (readonly, nonatomic) BOOL shouldPreventNotificationDismissalAfterDefaultAction;
@property (readonly, nonatomic) BOOL shouldSuppressDefaultAction;
@property (readonly, copy, nonatomic) NSURL *defaultActionURL;
@property (readonly, copy, nonatomic) NSString *defaultActionBundleIdentifier;
@property (readonly, nonatomic) BOOL shouldDisplayActionsInline;
@property (readonly, copy, nonatomic) UNNotificationIcon *icon;
@property (readonly, nonatomic) BOOL shouldShowSubordinateIcon;
@property (readonly, copy, nonatomic) NSSet *topicIdentifiers;
@property (readonly, nonatomic) unsigned long long realertCount;
@property (readonly, nonatomic) BOOL screenCaptureProhibited;
@property (readonly, copy, nonatomic) NSString *speechLanguage;
@property (readonly, nonatomic) BOOL shouldUseRequestIdentifierForDismissalSync;
@property (readonly, nonatomic) BOOL shouldSuppressSyncDismissalWhenRemoved;
@property (readonly, nonatomic) NSString *accessoryImageName;
@property (readonly, copy, nonatomic) NSArray *peopleIdentifiers;
@property (readonly, nonatomic) BOOL shouldPreemptPresentedNotification;
@property (readonly, nonatomic) BOOL shouldHideTime;
@property (readonly, nonatomic) BOOL hasDefaultAction;
@property (readonly, copy, nonatomic) NSString *defaultActionTitle;
@property (readonly, copy, nonatomic) NSArray *attachments;
@property (readonly, copy, nonatomic) NSNumber *badge;
@property (readonly, copy, nonatomic) NSString *body;
@property (readonly, copy, nonatomic) NSString *categoryIdentifier;
@property (readonly, copy, nonatomic) NSString *launchImageName;
@property (readonly, copy, nonatomic) UNNotificationSound *sound;
@property (readonly, copy, nonatomic) NSString *subtitle;
@property (readonly, copy, nonatomic) NSString *threadIdentifier;
@property (readonly, copy, nonatomic) NSString *title;
@property (readonly, copy, nonatomic) NSDictionary *userInfo;
@property (readonly, copy, nonatomic) NSString *summaryArgument;
@property (readonly, nonatomic) unsigned long long summaryArgumentCount;
@property (readonly, copy, nonatomic) NSString *targetContentIdentifier;
@property (readonly, nonatomic) unsigned long long interruptionLevel;
@property (readonly, nonatomic) double relevanceScore;
@property (readonly, copy, nonatomic) NSString *filterCriteria;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)contentByUpdatingWithReadAnnouncementIntent:(id)intent error:(out id *)error;
- (id)contentByUpdatingWithStartCallIntent:(id)intent error:(out id *)error;
- (id)contentByUpdatingWithSendMessageIntent:(id)intent error:(out id *)error;
- (id)contentByUpdatingWithProvider:(id)provider error:(out id *)error;
- (id)_initWithContentType:(id)type communicationContext:(id)context accessoryImageName:(id)name attachments:(id)attachments badge:(id)badge body:(id)body categoryIdentifier:(id)identifier date:(id)date icon:(id)icon defaultActionTitle:(id)title defaultActionURL:(id)url defaultActionBundleIdentifier:(id)identifier expirationDate:(id)date header:(id)header footer:(id)footer launchImageName:(id)name peopleIdentifiers:(id)identifiers shouldHideDate:(BOOL)date shouldHideTime:(BOOL)time shouldIgnoreDoNotDisturb:(BOOL)disturb shouldIgnoreDowntime:(BOOL)downtime shouldSuppressScreenLightUp:(BOOL)up shouldAuthenticateDefaultAction:(BOOL)action shouldBackgroundDefaultAction:(BOOL)action shouldPreventNotificationDismissalAfterDefaultAction:(BOOL)action shouldShowSubordinateIcon:(BOOL)icon shouldSuppressDefaultAction:(BOOL)action shouldSuppressSyncDismissalWhenRemoved:(BOOL)removed shouldUseRequestIdentifierForDismissalSync:(BOOL)sync shouldPreemptPresentedNotification:(BOOL)notification shouldDisplayActionsInline:(BOOL)inline sound:(id)sound subtitle:(id)subtitle threadIdentifier:(id)identifier title:(id)title topicIdentifiers:(id)identifiers realertCount:(unsigned long long)count summaryArgument:(id)argument summaryArgumentCount:(unsigned long long)count targetContentIdentifier:(id)identifier interruptionLevel:(unsigned long long)level relevanceScore:(double)score filterCriteria:(id)criteria screenCaptureProhibited:(BOOL)prohibited speechLanguage:(id)language userInfo:(id)info;
- (BOOL)isEqual:(id)equal;
- (id)_descriptionForDebug:(BOOL)debug;
- (id)_safeStringForString:(id)string debug:(BOOL)debug;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)markedMutableCopyWithMessage:(id)message;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)init;
- (void)addSecurityScope:(id)scope;
- (void)removeSecurityScope;
- (void)enterSecurityScope;
- (void)leaveSecurityScope;
@end

#endif /* UNNotificationContent_h */
