//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2202.0.0.0.0
//
#ifndef _NSConcreteObservation_h
#define _NSConcreteObservation_h
@import Foundation;

#include ".h"
#include "NSObservable-Protocol.h"
#include "NSObserver-Protocol.h"

@interface _NSConcreteObservation :  {
  /* instance variables */
  NSObject<NSObservable> *_LHSobservable;
  NSObject<NSObserver> *_RHSobserver;
  id _observers[4];
}

/* instance methods */
- (BOOL)isEqual:(id)equal;
- (id)debugDescription;
- (id)initWithObservable:(id)observable observer:(id)observer;
- (void *)_observerStorageOfSize:(unsigned long long)size;
- (void)remove;
- (void)finishObserving;
- (void)_receiveBox:(id)box;
- (void)dealloc;
@end

#endif /* _NSConcreteObservation_h */
