//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2202.0.0.0.0
//
#ifndef _NSURLAttributeDescriptor_h
#define _NSURLAttributeDescriptor_h
@import Foundation;

#include "_NSAttributeDescriptor.h"

@interface _NSURLAttributeDescriptor : _NSAttributeDescriptor
/* instance methods */
- (id)retain;
- (void)release;
- (unsigned long long)retainCount;
- (void)dealloc;
- (id)attributeValueFromValue:(id)value;
@end

#endif /* _NSURLAttributeDescriptor_h */
