//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2202.0.0.0.0
//
#ifndef NSDirInfoDeserializer_h
#define NSDirInfoDeserializer_h
@import Foundation;

#include "NSAKDeserializer.h"

@interface NSDirInfoDeserializer : NSAKDeserializer
/* instance methods */
- (id)deserializePListValueIn:(id)in key:(id)key length:(unsigned long long)length;
@end

#endif /* NSDirInfoDeserializer_h */
