//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2202.0.0.0.0
//
#ifndef NSDocInfo_h
#define NSDocInfo_h
@import Foundation;

#include "NSCopying-Protocol.h"

@interface NSDocInfo : NSObject<NSCopying> {
  /* instance variables */
  long long time;
  unsigned short mode;
  struct { unsigned int x :1 isDir; unsigned int x :1 isSingleFile; unsigned int x :1 isSoftLink; unsigned int x :13 _pad; } flags;
}

/* instance methods */
- (id)initFromInfo:(struct stat { int x0; unsigned short x1; unsigned short x2; unsigned long long x3; unsigned int x4; unsigned int x5; int x6; struct timespec { long long x0; long long x1; } x7; struct timespec { long long x0; long long x1; } x8; struct timespec { long long x0; long long x1; } x9; struct timespec { long long x0; long long x1; } x10; long long x11; long long x12; int x13; unsigned int x14; unsigned int x15; int x16; long long x17[2] } *)info;
- (void)setFileAttributes:(id)attributes;
- (id)initWithFileAttributes:(id)attributes;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)copy;
@end

#endif /* NSDocInfo_h */
