//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2202.0.0.0.0
//
#ifndef NSKeyValueNotifyingMutableCollectionGetter_h
#define NSKeyValueNotifyingMutableCollectionGetter_h
@import Foundation;

#include "NSKeyValueProxyGetter.h"
#include "NSKeyValueProxyGetter.h"

@interface NSKeyValueNotifyingMutableCollectionGetter : NSKeyValueProxyGetter {
  /* instance variables */
  NSKeyValueProxyGetter *_mutableCollectionGetter;
}

/* instance methods */
- (id)initWithContainerClassID:(id)id key:(id)key mutableCollectionGetter:(id)getter proxyClass:(Class)class;
- (void)dealloc;
- (id)mutableCollectionGetter;
@end

#endif /* NSKeyValueNotifyingMutableCollectionGetter_h */
