//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2202.0.0.0.0
//
#ifndef NSKeyValueFastMutableArray_h
#define NSKeyValueFastMutableArray_h
@import Foundation;

#include "NSKeyValueMutableArray.h"
#include "NSKeyValueMutatingArrayMethodSet.h"

@interface NSKeyValueFastMutableArray : NSKeyValueMutableArray {
  /* instance variables */
  NSKeyValueMutatingArrayMethodSet *_mutatingMethods;
}

/* instance methods */
- (id)_proxyInitWithContainer:(id)container getter:(id)getter;
- (void)_proxyNonGCFinalize;
- (void)addObject:(id)object;
- (void)insertObject:(id)object atIndex:(unsigned long long)index;
- (void)insertObjects:(id)objects atIndexes:(id)indexes;
- (void)removeLastObject;
- (void)removeObjectAtIndex:(unsigned long long)index;
- (void)removeObjectsAtIndexes:(id)indexes;
- (void)replaceObjectAtIndex:(unsigned long long)index withObject:(id)object;
- (void)replaceObjectsAtIndexes:(id)indexes withObjects:(id)objects;
@end

#endif /* NSKeyValueFastMutableArray_h */
