//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 83.0.0.0.0
//
#ifndef TUCall_SafetyKit_h
#define TUCall_SafetyKit_h
@import Foundation;

@interface TUCall (SafetyKit)
/* instance methods */
- (BOOL)sa_hasFailed;
@end

#endif /* TUCall_SafetyKit_h */
