//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.2.3.0.0
//
#ifndef CGRemotePDFPageProxy_h
#define CGRemotePDFPageProxy_h
@import Foundation;

#include "CGRemotePDFPageProtocol-Protocol.h"

@class NSString, NSUUID;

@interface CGRemotePDFPageProxy : NSObject {
  /* instance variables */
  NSObject<CGRemotePDFPageProtocol> *_asyncProxy;
  NSObject<CGRemotePDFPageProtocol> *_syncProxy;
}

@property (readonly) NSUUID *identifier;
@property (readonly) long long rotation;
@property (readonly) NSString *pageText;

/* instance methods */
- (id)initWithRemotePage:(id)page;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rectForBox:(int)box;
- (void)drawWithBox:(int)box size:(struct CGSize { double x0; double x1; })size colorSpace:(id)space options:(id)options completion:(id /* block */)completion;
@end

#endif /* CGRemotePDFPageProxy_h */
