//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.2.3.0.0
//
#ifndef CPImage_h
#define CPImage_h
@import Foundation;

#include "CPGraphicObject.h"

@interface CPImage : CPGraphicObject {
  /* instance variables */
  struct CPPDFImage { struct CPPDFObject { struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } x0; struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } x1; unsigned int x2; unsigned int x3; } x0; unsigned int x1; struct CGPDFStream * x2; int x3; struct CGImage * x4; struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; } x5; struct CGPDFDictionary * x6; double x7; struct CGColor * x8; long long x9; } * imageData;
  BOOL renderedBoundsComputed;
}

/* instance methods */
- (id)initWithPDFImage:(struct CPPDFImage { struct CPPDFObject { struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } x0; struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } x1; unsigned int x2; unsigned int x3; } x0; unsigned int x1; struct CGPDFStream * x2; int x3; struct CGImage * x4; struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; } x5; struct CGPDFDictionary * x6; double x7; struct CGColor * x8; long long x9; } *)pdfimage;
- (id)initWithBounds:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })bounds;
- (struct CPPDFImage { struct CPPDFObject { struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } x0; struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } x1; unsigned int x2; unsigned int x3; } x0; unsigned int x1; struct CGPDFStream * x2; int x3; struct CGImage * x4; struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; } x5; struct CGPDFDictionary * x6; double x7; struct CGColor * x8; long long x9; } *)imageData;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })renderedBounds;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })bounds;
- (void)recomputeRenderedBounds;
- (void)accept:(id)accept;
- (long long)zOrder;
- (BOOL)isVisible;
@end

#endif /* CPImage_h */
