//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2417.42.9.28.9
//
#ifndef _MKAnimationStackViewDelegate_Protocol_h
#define _MKAnimationStackViewDelegate_Protocol_h
@import Foundation;

@protocol _MKAnimationStackViewDelegate <NSObject>
/* instance methods */
- (void)stackViewNeedsLayout:(id)layout;
@end

#endif /* _MKAnimationStackViewDelegate_Protocol_h */
