//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2417.42.9.28.9
//
#ifndef MKAutocompleteAnalyticsProvider_Protocol_h
#define MKAutocompleteAnalyticsProvider_Protocol_h
@import Foundation;

#include "MKAutocompleteAnalyticsProvider-Protocol.h"
#include "MKAutocompleteAnalyticsState-Protocol.h"
#include "MKAutocompleteAnalyticsState.h"

@protocol OS_dispatch_queue;

@protocol MKAutocompleteAnalyticsProvider 
/* instance methods */
- (id)captureNewMetrics;
@end

#endif /* MKAutocompleteAnalyticsProvider_Protocol_h */
