//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2417.42.9.28.9
//
#ifndef MKCompassView_h
#define MKCompassView_h
@import Foundation;

#include "UIView.h"
#include "MKCompassView-Protocol.h"

@class NSArray, NSString, UIImageView;

@interface MKCompassView : UIView<MKCompassView> {
  /* instance variables */
  UIImageView *_containerImageView;
  UIImageView *_assetImageView;
  NSArray *_compassPointLocalizedAbbreviations;
  int _lastDrawnCompassDirection;
}

@property (nonatomic) double mapHeading;
@property (readonly, nonatomic) long long compassViewSize;
@property (readonly, nonatomic) long long compassViewStyle;
@property (nonatomic) double yaw;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)_parameterForSize:(long long)size;
+ (id)_parameterForStyle:(long long)style;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithCoder:(id)coder;
- (void)_commonInit;
- (void)movedToWindow:(id)window;
- (void)dealloc;
- (void)updateLocale:(id)locale;
- (void)layoutSubviews;
- (void)_setupImageView:(id)view;
- (void)_updateStyle;
- (void)setCompassViewSize:(long long)size style:(long long)style;
- (void)_updateLayerForCurrentSizeAndStyle;
- (void)_updateImageForCompassDirection:(int)direction;
- (id)_compassDirectionImageForKey:(id)key sizeParams:(id)params styleParams:(id)params scale:(double)scale;
- (struct CGSize { double x0; double x1; })intrinsicContentSize;
- (BOOL)isPointInNorthEastHalf:(struct CGPoint { double x0; double x1; })half;
- (id)stringForCompassPoint:(int)point;
- (void)_populateCompassPointLocalizedAbbreviationsArray;
@end

#endif /* MKCompassView_h */
