//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1454.2.1.0.0
//
#ifndef CalendarModel_h
#define CalendarModel_h
@import Foundation;

#include "CUIKCalendarModel.h"

@interface CalendarModel : CUIKCalendarModel
/* class methods */
+ (id)calendarModelWithEventStore:(id)store;
+ (id)calendarModelWithDataPath:(id)path;
+ (id)new;

/* instance methods */
- (id)init;
- (id)initWithEventStore:(id)store;
- (id)initWithDataPath:(id)path;
- (id)persistedSceneState;
- (id)occurrencesForStartDate:(id)date endDate:(id)date preSorted:(BOOL)sorted waitForLoad:(BOOL)load;
- (id)occurrencesForStartDay:(id)day endDay:(id)day preSorted:(BOOL)sorted waitForLoad:(BOOL)load;
- (id)occurrencesForDay:(id)day waitForLoad:(BOOL)load;
- (id)cachedSpecialDayDataForSection:(long long)section;
@end

#endif /* CalendarModel_h */
