//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1454.2.1.0.0
//
#ifndef CUIKOccurrencesCollection_CalendarOccurrencesCollection_h
#define CUIKOccurrencesCollection_CalendarOccurrencesCollection_h
@import Foundation;

#include "CUIKOccurrencesCollection.h"

@interface CUIKOccurrencesCollection (CalendarOccurrencesCollection)
/* instance methods */
- (id)asCalendarOccurrencesCollection;
@end

#endif /* CUIKOccurrencesCollection_CalendarOccurrencesCollection_h */
