//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1454.2.1.0.0
//
#ifndef EKCalendarSubscriptionDetailsEditItem_h
#define EKCalendarSubscriptionDetailsEditItem_h
@import Foundation;

#include "EKCalendarEditItem.h"

@interface EKCalendarSubscriptionDetailsEditItem : EKCalendarEditItem
/* instance methods */
- (unsigned long long)numberOfSubitems;
- (BOOL)configureWithCalendar:(id)calendar;
- (id)cellForSubitemAtIndex:(unsigned long long)index;
- (void)calendarEditor:(id)editor didSelectSubitem:(unsigned long long)subitem;
@end

#endif /* EKCalendarSubscriptionDetailsEditItem_h */
