//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1454.2.1.0.0
//
#ifndef EKCalendarItemRecurrenceEditItem_h
#define EKCalendarItemRecurrenceEditItem_h
@import Foundation;

#include "EKCalendarItemEditItem.h"
#include "EKDateTimeCell.h"
#include "EKDateTimeCellDelegate-Protocol.h"
#include "EKUITableViewCell.h"

@class NSDate, NSString, UIDatePicker, UITableViewCell;

@interface EKCalendarItemRecurrenceEditItem : EKCalendarItemEditItem<EKDateTimeCellDelegate> {
  /* instance variables */
  long long _repeatType;
  long long _originalRepeatType;
  NSDate *_repeatEnd;
  NSDate *_originalRepeatEnd;
  NSString *_customRepeatDescription;
  UITableViewCell *_customCell;
  EKDateTimeCell *_endDateCell;
  EKUITableViewCell *_endDatePickerCell;
  UIDatePicker *_endDatePicker;
  BOOL _showingDatePicker;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)_neverLocalizedString;

/* instance methods */
- (id)init;
- (void)dealloc;
- (void)_contentSizeCategoryChanged:(id)changed;
- (BOOL)canBeConfiguredForCalendarConstraints:(id)constraints;
- (void)refreshFromCalendarItemAndStore;
- (BOOL)saveAndDismissWithForce:(BOOL)force;
- (unsigned long long)subitemAtIndex:(unsigned long long)index;
- (unsigned long long)indexForSubitem:(unsigned long long)subitem;
- (unsigned long long)numberOfSubitems;
- (id)cellForSubitemAtIndex:(unsigned long long)index;
- (id)repeatPopupMenu;
- (id)endRepeatPopupMenu;
- (id)_newDatePicker;
- (id)recurrenceRuleFromRepeatType:(long long)type;
- (void)_datePickerChanged:(id)changed;
- (void)saveNewRepeatEndDate:(id)date;
- (void)_updateMinRecurrenceEndDate;
- (BOOL)_validateRecurrenceType:(id)type;
- (void)presentCustomRecurrenceVC;
- (void)editor:(id)editor didSelectSubitem:(unsigned long long)subitem;
- (id)recurrenceDate;
- (id)recurrenceTimeZone;
- (id)stringForDate:(id)date;
- (id)minRecurrenceEndDate;
- (id)bestInitialEndDate;
- (BOOL)forceRefreshStartAndEndDatesOnSave;
- (void)dateTimeCellDateTapped:(id)tapped;
- (void)dateTimeCellTimeTapped:(id)tapped;
- (void)dateTimeCell:(id)cell dateChanged:(id)changed;
- (void)dateTimeCellBeganEditing:(id)editing;
- (void)dateTimeCellEndedEditing:(id)editing;
@end

#endif /* EKCalendarItemRecurrenceEditItem_h */
