//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1454.2.1.0.0
//
#ifndef EKCalendarSubscriptionSpamCheckEditItemDelegate_Protocol_h
#define EKCalendarSubscriptionSpamCheckEditItemDelegate_Protocol_h
@import Foundation;

@protocol EKCalendarSubscriptionSpamCheckEditItemDelegate <NSObject>
/* instance methods */
- (void)calendarSubscriptionSpamCheckEditItem:(id)item didDetermineThatURL:(id)url isSpam:(BOOL)spam;
@end

#endif /* EKCalendarSubscriptionSpamCheckEditItemDelegate_Protocol_h */
