//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1454.2.1.0.0
//
#ifndef EKLocationEditItemViewController_h
#define EKLocationEditItemViewController_h
@import Foundation;

#include "EKEditItemViewController.h"
#include "EKLocationVirtualConferenceSearchFieldsDelegate-Protocol.h"
#include "EKLocationVirtualConferenceSearchFieldsView.h"
#include "EKStructuredLocationWithImage.h"
#include "EKUIConferenceRoom.h"
#include "EKUILocationRowModel.h"
#include "EKUILocationSearchModel.h"
#include "EKUILocationSearchModelDelegate-Protocol.h"
#include "EKUIManagedViewController-Protocol.h"
#include "UISearchBarDelegate-Protocol.h"
#include "UITableViewDataSource-Protocol.h"
#include "UITableViewDelegate-Protocol.h"
#include "VirtualConferenceRoomTypeSelectionDelegate-Protocol.h"

@class EKCalendarItem, EKStructuredLocation, EKVirtualConference, EKVirtualConferenceRoomType, NSArray, NSError, NSMutableDictionary, NSString, UISearchBar, UITableView, _UINavigationControllerPalette;

@interface EKLocationEditItemViewController : EKEditItemViewController<UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate, EKLocationVirtualConferenceSearchFieldsDelegate, EKUILocationSearchModelDelegate, VirtualConferenceRoomTypeSelectionDelegate, EKUIManagedViewController> {
  /* instance variables */
  UITableView *_tableView;
  _UINavigationControllerPalette *_palette;
  UISearchBar *_searchBar;
  EKLocationVirtualConferenceSearchFieldsView *_searchFieldsView;
  EKUILocationSearchModel *_searchModel;
  EKCalendarItem *_calendarItem;
  EKVirtualConferenceRoomType *_checkedRoomType;
  BOOL _shouldShowCheckedVirtualConference;
  NSMutableDictionary *_cachedConferenceRooms;
  struct CGSize { double width; double height; } _preferredContentSize;
  BOOL _supportsStructuredLocations;
  BOOL _tableConstraintsInstalled;
  BOOL _rotating;
  BOOL _wasFirstResponder;
  EKStructuredLocation *_searchModelCurrentLocation;
  EKStructuredLocationWithImage *_searchModelLocationFromMapsURL;
  NSArray *_searchModelMapCompletionSearchResults;
  NSArray *_searchModelContactsSearchResults;
  NSArray *_searchModelRecentsSearchResults;
  NSArray *_searchModelFrequentsSearchResults;
  NSArray *_searchModelEventsSearchResults;
  NSArray *_searchModelTextualSearchResults;
  NSArray *_searchModelConferenceRoomSearchResults;
  NSArray *_searchModelVirtualConferenceRoomSearchResults;
  NSArray *_searchModelVirtualConferenceCustomSearchResults;
}

@property (retain, nonatomic) EKStructuredLocation *selectedLocation;
@property (retain, nonatomic) EKUIConferenceRoom *selectedConferenceRoom;
@property (retain, nonatomic) EKVirtualConference *selectedVirtualConference;
@property (nonatomic) BOOL pendingVirtualConference;
@property (retain, nonatomic) NSError *pendingVirtualConferenceError;
@property (copy, nonatomic) id /* block */ viewDidAppearBlock;
@property (nonatomic) BOOL needsSave;
@property (nonatomic) unsigned long long supportedSearchTypes;
@property (nonatomic) BOOL autoFillSelectedTextField;
@property (nonatomic) BOOL forceSingleTextField;
@property (nonatomic) BOOL conferenceTextFieldSelected;
@property (nonatomic) BOOL disableConferenceTextField;
@property (retain, nonatomic) EKUILocationRowModel *locationViewModel;
@property (readonly) BOOL locationViewModelRemoved;
@property (retain, nonatomic) EKUILocationRowModel *conferenceViewModel;
@property (readonly) BOOL conferenceViewModelRemoved;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)_boldTitleFont;
+ (id)_sectionNameForSection:(unsigned long long)section;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame styleProvider:(id)provider;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame styleProvider:(id)provider calendarItem:(id)item eventStore:(id)store;
- (void)setViewAppearedBlock:(id /* block */)block;
- (id)title;
- (void)viewDidLoad;
- (void)setPreferredContentSize:(struct CGSize { double x0; double x1; })size;
- (struct CGSize { double x0; double x1; })preferredContentSize;
- (void)viewDidAppear:(BOOL)appear;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })size withTransitionCoordinator:(id)coordinator;
- (void)_setupViewsAndConstraints;
- (BOOL)presentModally;
- (BOOL)showingTextRow;
- (BOOL)showingCurrentLocationRow;
- (BOOL)showAvailableConferenceTypesAsRows;
- (void)useAsString:(id)string;
- (id)itemAtIndexPath:(id)path;
- (id)conferenceRoomForRecent:(id)recent;
- (long long)numberOfSectionsInTableView:(id)view;
- (long long)tableView:(id)view numberOfRowsInSection:(long long)section;
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)path;
- (BOOL)tableView:(id)view wantsHeaderForSection:(long long)section;
- (id)tableView:(id)view titleForHeaderInSection:(long long)section;
- (double)tableView:(id)view heightForHeaderInSection:(long long)section;
- (id)tableView:(id)view cellForRowAtIndexPath:(id)path;
- (void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)path;
- (long long)_accessoryTypeForSection:(unsigned long long)section;
- (long long)tableView:(id)view editingStyleForRowAtIndexPath:(id)path;
- (void)tableView:(id)view commitEditingStyle:(long long)style forRowAtIndexPath:(id)path;
- (id)locationArrowImage;
- (id)contactsImage;
- (void)locationSearchModel:(id)model selectedLocation:(id)location withError:(id)error;
- (id)calendarItemForSearchModel:(id)model;
- (BOOL)shouldIncludeConferenceRoom:(id)room;
- (void)locationSearchModel:(id)model updatedSearchTypes:(unsigned long long)types;
- (id)_rowNameForIndexPath:(id)path;
- (id)_cellForConferenceRoom:(id)room atIndexPath:(id)path;
- (BOOL)wantsManagement;
- (BOOL)canManagePresentationStyle;
- (BOOL)_singleSearchBar;
- (id)_focusedTextField;
- (void)setSearchText:(id)text;
- (id)searchText;
- (BOOL)searchIsFirstResponder;
- (void)searchResignFirstResponder;
- (void)searchBecomeFirstResponder;
- (void)searchTextChanged:(id)changed;
- (void)searchDoneTapped;
- (void)searchBar:(id)bar textDidChange:(id)change;
- (void)searchBarSearchButtonClicked:(id)clicked;
- (void)textField:(id)field didChange:(id)change;
- (void)textFieldDoneTapped:(id)tapped;
- (void)selectedTextFieldChanged:(id)changed;
- (void)selectedRoomType:(id)type;
- (void)pendingVideoConferenceUpdated:(id)updated;
@end

#endif /* EKLocationEditItemViewController_h */
