//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1454.2.1.0.0
//
#ifndef EKUIConstrainedFontUtilities_h
#define EKUIConstrainedFontUtilities_h
@import Foundation;

@interface EKUIConstrainedFontUtilities : NSObject
/* class methods */
+ (void)initialize;
+ (void)clearFontCaches;
+ (id)constrainedBodyTextLabelFont;
+ (id)constrainedCaption1TextLabelFont;
+ (id)constrainedBodyBoldTextLabelFont;
+ (id)constrainedFontForTextStyle:(id)style maximumContentSizeCategory:(id)category traitCollection:(id)collection;
+ (id)constrainedFontForTextStyle:(id)style minimumContentSizeCategory:(id)category traitCollection:(id)collection;
+ (id)constrainedFontForTextStyle:(id)style minimumContentSizeCategory:(id)category maximumContentSizeCategory:(id)category traitCollection:(id)collection;
+ (id)constrainedFontForTextStyle:(id)style maximumContentSizeCategory:(id)category addingSymbolicTraits:(unsigned int)traits traitCollection:(id)collection;
+ (long long)tableViewCellCappedSymbolImageScaleWithScale:(long long)scale traitCollection:(id)collection;
@end

#endif /* EKUIConstrainedFontUtilities_h */
