//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1454.2.1.0.0
//
#ifndef EKUIInviteesViewAvailabilityCell_h
#define EKUIInviteesViewAvailabilityCell_h
@import Foundation;

#include "EKUIInviteesViewSimpleCell.h"

@interface EKUIInviteesViewAvailabilityCell : EKUIInviteesViewSimpleCell
/* class methods */
+ (id)labelText;
+ (long long)accessoryType;
@end

#endif /* EKUIInviteesViewAvailabilityCell_h */
