//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1454.2.1.0.0
//
#ifndef EKUIDiscoverabilityUtilities_h
#define EKUIDiscoverabilityUtilities_h
@import Foundation;

@interface EKUIDiscoverabilityUtilities : NSObject
/* class methods */
+ (void)sendDiscoverabilitySignalForConference:(id)conference;
+ (void)scanEventsForDiscoveredConferencesIfNeeded:(id)needed;
@end

#endif /* EKUIDiscoverabilityUtilities_h */
