//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1454.2.1.0.0
//
#ifndef NSTimeZone_EventKitUI_h
#define NSTimeZone_EventKitUI_h
@import Foundation;

@interface NSTimeZone (EventKitUI)
/* instance methods */
- (id)cityName;
- (void)setCityName:(id)name;
- (void)_cleanupDisallowedTimezonesIfNeeded;
@end

#endif /* NSTimeZone_EventKitUI_h */
