//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 61040.64.1.0.0
//
#ifndef OTControlArguments_h
#define OTControlArguments_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"

@class NSString;

@interface OTControlArguments : NSObject<NSSecureCoding>

@property (retain) NSString *contextID;
@property (retain) NSString *containerName;
@property (retain) NSString *altDSID;
@property (retain) NSString *flowID;
@property (retain) NSString *deviceSessionID;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)init;
- (id)initWithConfiguration:(id)configuration;
- (id)initWithAltDSID:(id)dsid;
- (id)initWithAltDSID:(id)dsid flowID:(id)id deviceSessionID:(id)id;
- (id)initWithContainerName:(id)name contextID:(id)id altDSID:(id)dsid;
- (id)initWithContainerName:(id)name contextID:(id)id altDSID:(id)dsid flowID:(id)id deviceSessionID:(id)id;
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)makeConfigurationContext;
@end

#endif /* OTControlArguments_h */
