//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 61040.64.1.0.0
//
#ifndef SecConcrete_sec_array_h
#define SecConcrete_sec_array_h
@import Foundation;

#include "OS_sec_array-Protocol.h"

@class NSString;
@protocol OS_xpc_object;

@interface SecConcrete_sec_array : NSObject<OS_sec_array> {
  /* instance variables */
  NSObject<OS_xpc_object> *xpc_array;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)dealloc;
@end

#endif /* SecConcrete_sec_array_h */
