//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 61040.64.1.0.0
//
#ifndef SecKeyProxyTarget_h
#define SecKeyProxyTarget_h
@import Foundation;

#include "SecKeyProxy.h"
#include "SecKeyProxyProtocol-Protocol.h"

@class NSData;

@interface SecKeyProxyTarget : NSObject<SecKeyProxyProtocol> {
  /* instance variables */
  NSData *_certificate;
  SecKeyProxy *_publicKeyProxy;
}

@property (readonly, nonatomic) struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; atomic  x1; unsigned long long x2; } x0; struct __SecKeyDescriptor * x1; void * x2; } * key;

/* instance methods */
- (id)initWithKey:(id)key certificate:(id)certificate;
- (void)initializeWithReply:(id /* block */)reply;
- (void)getBlockSizeWithReply:(id /* block */)reply;
- (void)getAttributesWithReply:(id /* block */)reply;
- (void)getExternalRepresentationWithReply:(id /* block */)reply;
- (void)getDescriptionWithReply:(id /* block */)reply;
- (void)getAlgorithmIDWithReply:(id /* block */)reply;
- (void)getPublicKey:(id /* block */)key;
- (void)performOperation:(long long)operation mode:(long long)mode algorithm:(id)algorithm parameters:(id)parameters reply:(id /* block */)reply;
@end

#endif /* SecKeyProxyTarget_h */
