//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 129.0.0.0.0
//
#ifndef NLGazetteer_h
#define NLGazetteer_h
@import Foundation;

#include "NLModel.h"

@class NSData, NSString;

@interface NLGazetteer : NSObject {
  /* instance variables */
  void * _gazetteer;
  NLModel *_nlModel;
}

@property (readonly, copy) NSString *language;
@property (readonly, copy) NSData *data;

/* class methods */
+ (id)gazetteerWithContentsOfURL:(id)url error:(id *)error;
+ (id)gazetteerWithData:(id)data error:(id *)error;
+ (id)gazetteerWithMLModel:(id)mlmodel error:(id *)error;
+ (BOOL)writeGazetteerForDictionary:(id)dictionary language:(id)language toURL:(id)url error:(id *)error;
+ (BOOL)writeGazetteerMLModelForDictionary:(id)dictionary language:(id)language toURL:(id)url options:(id)options error:(id *)error;

/* instance methods */
- (id)initWithContentsOfURL:(id)url error:(id *)error;
- (id)initWithData:(id)data error:(id *)error;
- (void *)_gazetteerRef;
- (id)initWithNLModel:(id)nlmodel error:(id *)error;
- (id)initWithMLModel:(id)mlmodel error:(id *)error;
- (id)initWithDictionary:(id)dictionary language:(id)language error:(id *)error;
- (void)dealloc;
- (id)labelForString:(id)string;
- (id)labels;
- (id)modelDescription;
- (BOOL)writeMLModelToURL:(id)url options:(id)options error:(id *)error;
- (void)_addImplementationToArray:(struct __CFArray *)array;
@end

#endif /* NLGazetteer_h */
