//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 129.0.0.0.0
//
#ifndef NLModelImplM_h
#define NLModelImplM_h
@import Foundation;

#include "NLModelImpl.h"
#include "NLModelConfiguration.h"

@class NSDictionary;

@interface NLModelImplM : NLModelImpl {
  /* instance variables */
  const void * _mrlModel;
  NLModelConfiguration *_configuration;
  NSDictionary *_labelMap;
  NSDictionary *_vocabularyMap;
  unsigned long long _numberOfTrainingInstances;
}

/* instance methods */
- (id)initWithOwnedModelObject:(const void *)object configuration:(id)configuration labelMap:(id)map vocabularyMap:(id)map numberOfTrainingInstances:(unsigned long long)instances;
- (id)initWithModelData:(id)data configuration:(id)configuration labelMap:(id)map vocabularyMap:(id)map documentFrequencyMap:(id)map customEmbeddingData:(id)data trainingInfo:(id)info error:(id *)error;
- (id)initWithModelTrainer:(id)trainer error:(id *)error;
- (void)dealloc;
- (id)modelData;
- (id)configuration;
- (id)labelMap;
- (id)vocabularyMap;
- (unsigned long long)numberOfTrainingInstances;
- (id)predictedLabelForString:(id)string;
- (id)predictedLabelsForTokens:(id)tokens;
- (id)predictedLabelHypothesesForString:(id)string maximumCount:(unsigned long long)count;
- (id)predictedLabelHypothesesForTokens:(id)tokens maximumCount:(unsigned long long)count;
@end

#endif /* NLModelImplM_h */
