//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2.2.1.0.0
//
#ifndef _TtC6Charts21AxisMarkLayoutContext_h
#define _TtC6Charts21AxisMarkLayoutContext_h
@import Foundation;

#include "_TtC6Charts15AxisMarkContext.h"

@interface Charts.AxisMarkLayoutContext : Charts.AxisMarkContext { // (Swift)
  /* instance variables */
   layout;
}

@end

#endif /* _TtC6Charts21AxisMarkLayoutContext_h */
