//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2.2.1.0.0
//
#ifndef _TtCV6Charts23InteractionHandlingView10UIViewType_h
#define _TtCV6Charts23InteractionHandlingView10UIViewType_h
@import Foundation;

#include "UIView.h"
#include "UIGestureRecognizerDelegate-Protocol.h"

@interface Charts.InteractionHandlingView.UIViewType : UIView<UIGestureRecognizerDelegate> { // (Swift)
  /* instance variables */
   onChanged;
   onEnd;
   panDelegate;
}

/* instance methods */
- (void)handleDragGesture:(id)gesture;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithCoder:(id)coder;
@end

#endif /* _TtCV6Charts23InteractionHandlingView10UIViewType_h */
