//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.3.0.0
//
#ifndef _MPSSILImplementation_h
#define _MPSSILImplementation_h
@import Foundation;

#include "MPSectionedIdentifierList.h"
#include "MPRandomDistribution.h"
#include "_MPSSILDelegate-Protocol.h"

@class NSMutableArray;

@interface _MPSSILImplementation : MPSectionedIdentifierList

@property (weak, @dynamic, nonatomic) NSObject<_MPSSILDelegate> *delegate;
@property (readonly, nonatomic) MPRandomDistribution *randomDistribution;
@property (retain, nonatomic) NSMutableArray *candidateItems;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithSectionedIdentifierList:(id)list randomSource:(id)source startingItemEntry:(id)entry withExclusiveAccessToken:(id)token;
- (id)initWithCoder:(id)coder;
- (void)_beforeInitWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder withExclusiveAccessToken:(id)token;
- (void)dequeueCandidatesWithQuota:(long long)quota;
- (void)safelyReshuffleAfterItem:(id)item inSection:(id)section;
- (void)addDataSourceAtStart:(id)start section:(id)section sequentially:(BOOL)sequentially;
- (void)addDataSource:(id)source section:(id)section sequentially:(BOOL)sequentially afterItem:(id)item inSection:(id)section;
- (void)addDataSource:(id)source section:(id)section sequentially:(BOOL)sequentially afterTailOfSection:(id)section;
- (void)addDataSource:(id)source section:(id)section sequentially:(BOOL)sequentially beforeTailOfSection:(id)section;
- (void)addDataSourceAtEnd:(id)end section:(id)section sequentially:(BOOL)sequentially;
- (void)dataSourceInsertItemsAtHead:(id)head inSection:(id)section;
- (void)dataSourceInsertItems:(id)items afterItem:(id)item inSection:(id)section;
- (void)dataSourceInsertItemsAtTail:(id)tail inSection:(id)section;
- (void)dataSourceRemoveItems:(id)items fromSection:(id)section;
- (void)dataSourceReloadItems:(id)items inSection:(id)section;
- (long long)itemCount;
- (void)_enumerator:(id)_enumerator didEncounterEntry:(id)entry withExclusiveAccessToken:(id)token;
- (BOOL)_isSequentialSection:(id)section withExclusiveAccessToken:(id)token;
- (void)_reverseEnumeratorWillStartAtEnd:(id)end withExclusiveAccessToken:(id)token;
- (void)_addShuffleSection:(id)section dataSource:(id)source withExclusiveAccessToken:(id)token;
- (void)_appendShuffledItems:(id)items withExclusiveAccessToken:(id)token;
- (id)_createShuffleCloneForItem:(id)item inSection:(id)section withExclusiveAccessToken:(id)token;
- (void)_dequeueCandidatesWithQuota:(long long)quota withExclusiveAccessToken:(id)token;
@end

#endif /* _MPSSILImplementation_h */
