//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.3.0.0
//
#ifndef MPChangeShuffleModeCommand_h
#define MPChangeShuffleModeCommand_h
@import Foundation;

#include "MPRemoteCommand.h"

@class NSArray;

@interface MPChangeShuffleModeCommand : MPRemoteCommand {
  /* instance variables */
  NSArray *_supportedShuffleTypes;
}

@property (nonatomic) long long currentShuffleType;

/* instance methods */
- (void)setSupportedShuffleTypes:(id)types;
- (id)_mediaRemoteCommandInfoOptions;
- (id)newCommandEventWithType:(long long)type;
- (id)newCommandEventWithType:(long long)type preservesShuffleMode:(BOOL)mode;
@end

#endif /* MPChangeShuffleModeCommand_h */
