//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.3.0.0
//
#ifndef MPMediaItemCollection_h
#define MPMediaItemCollection_h
@import Foundation;

#include "MPMediaEntity.h"
#include "MPMediaItem.h"
#include "MPMediaQuery.h"

@class NSArray;

@interface MPMediaItemCollection : MPMediaEntity {
  /* instance variables */
  unsigned long long _containedMediaTypes;
  BOOL _initializedContainedMediaTypes;
  unsigned long long _itemsCount;
  MPMediaQuery *_itemsQuery;
}

@property (readonly, nonatomic) long long groupingType;
@property (readonly, nonatomic) NSArray *items;
@property (readonly, nonatomic) MPMediaItem *representativeItem;
@property (readonly, nonatomic) unsigned long long count;
@property (readonly, nonatomic) unsigned long long mediaTypes;

/* class methods */
+ (id)artworkCatalogCachePropertiesForGroupingType:(long long)type;
+ (id)collectionWithItems:(id)items;
+ (BOOL)supportsSecureCoding;
+ (id)titlePropertyForGroupingType:(long long)type;
+ (id)sortTitlePropertyForGroupingType:(long long)type;
+ (id)representativePersistentIDPropertyForGroupingType:(long long)type;

/* instance methods */
- (BOOL)MPSD_hasDownloadingItem;
- (id)artworkCatalog;
- (id)albumArtistArtworkCatalog;
- (id)artistArtworkCatalog;
- (id)_artworkCatalogRepresentativeItem;
- (id)initWithItems:(id)items;
- (id)initWithItemsQuery:(id)query;
- (id)initWithMultiverseIdentifier:(id)identifier library:(id)library;
- (id)init;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)equal;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)itemsQuery;
- (id)multiverseIdentifier;
- (BOOL)setValue:(id)value forProperty:(id)property;
- (void)setValue:(id)value forProperty:(id)property withCompletionBlock:(id /* block */)block;
- (void)_enumerateItemPersistentIDsUsingBlock:(id /* block */)block;
@end

#endif /* MPMediaItemCollection_h */
