//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.3.0.0
//
#ifndef MPModelForYouRecommendationMusicKitItemBuilder_h
#define MPModelForYouRecommendationMusicKitItemBuilder_h
@import Foundation;

#include "MPModelForYouRecommendationMusicKitGroupBuilder.h"
#include "MPModelStoreBrowseContentItemBuilder.h"
#include "MPMutableSectionedCollection.h"
#include "MPPropertySet.h"

@class ICURLBag, NSDictionary;

@interface MPModelForYouRecommendationMusicKitItemBuilder : NSObject {
  /* instance variables */
  struct { BOOL isInitialized; BOOL itemType; BOOL url; BOOL reason; BOOL utterance; BOOL backedByStoreItemMetadata; BOOL album; BOOL playlist; BOOL radioStation; BOOL subgroup; } _requestedItemProperties;
  MPModelStoreBrowseContentItemBuilder *_contentItemBuilder;
  MPModelForYouRecommendationMusicKitGroupBuilder *_subgroupBuilder;
  ICURLBag *_storeURLBag;
  BOOL _isListenNow;
}

@property (readonly, nonatomic) MPPropertySet *requestedPropertySet;
@property (readonly, nonatomic) NSDictionary *storeItemMetadataResults;
@property (readonly, nonatomic) MPMutableSectionedCollection *flatSectionedItems;

/* class methods */
+ (id)allSupportedProperties;

/* instance methods */
- (id)initWithRequestedPropertySet:(id)set storeItemMetadataResults:(id)results flatSectionedItems:(id)items storeURLBag:(id)urlbag isListenNow:(BOOL)now;
- (id)modelObjectForRecommendationChildDictionary:(id)dictionary parentGroup:(id)group subgroupsAccumulator:(id)accumulator userIdentity:(id)identity;
- (id)storeItemMetadataWithMusicAPIMetadataDictionary:(id)dictionary;
- (id)convertToStoreItemMetadataDictionary:(id)dictionary;
@end

#endif /* MPModelForYouRecommendationMusicKitItemBuilder_h */
