//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.3.0.0
//
#ifndef MPModelObject_h
#define MPModelObject_h
@import Foundation;

#include "MPIdentifierSet.h"
#include "NSCopying-Protocol.h"
#include "NSObject-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSMutableDictionary, NSString;

@interface MPModelObject : NSObject<NSCopying, NSSecureCoding, NSObject> {
  /* instance variables */
  NSMutableDictionary *_storage;
  BOOL _isFinalized;
}

@property (readonly, nonatomic) struct MPLibraryAddStatusObserverConfiguration { BOOL x0; BOOL x1; BOOL x2; BOOL x3; BOOL x4; } libraryAddStatusObserverConfiguration;
@property (readonly, nonatomic) long long libraryRemovalSupportedOptions;
@property (readonly, nonatomic) MPIdentifierSet *originalIdentifierSet;
@property (readonly, nonatomic) NSString *humanDescription;
@property (readonly, copy, nonatomic) MPIdentifierSet *identifiers;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (long long)genericObjectType;
+ (id)requiredKeepLocalStatusObservationProperties;
+ (BOOL)supportsKeepLocalStatusObservation;
+ (id)requiredLibraryRemovalProperties;
+ (BOOL)supportsLibraryRemoval;
+ (BOOL)supportsLibraryAddStatusObservation;
+ (id)requiredLibraryAddStatusObservationProperties;
+ (void)initialize;
+ (BOOL)resolveInstanceMethod:(SEL)method;
+ (void)performWithoutEnforcement:(id /* block */)enforcement;
+ (id)classesForSecureCoding;
+ (BOOL)supportsSecureCoding;
+ (void)_indexProperties;
+ (BOOL)_lookupPropertyForSelector:(SEL)selector result:(id /* block */)result;
+ (id)_modelKeyForPropertySelector:(SEL)selector;

/* instance methods */
- (id)newKeepLocalStatusObserverConfiguration;
- (id)mediaItemPropertyValues;
- (id)contentItemCollectionInfo;
- (id)initWithIdentifiers:(id)identifiers;
- (id)initWithIdentifiers:(id)identifiers block:(id /* block */)block;
- (id)valueForUndefinedKey:(id)key;
- (void)setValue:(id)value forUndefinedKey:(id)key;
- (BOOL)isEqual:(id)equal;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)copyWithIdentifiers:(id)identifiers;
- (id)copyWithIdentifiers:(id)identifiers block:(id /* block */)block;
- (id)copyWithPropertySet:(id)set;
- (id)copyWithIdentifiers:(id)identifiers propertySet:(id)set;
- (BOOL)hasLoadedValueForKey:(id)key;
- (BOOL)hasLoadedValuesForPropertySet:(id)set;
- (id)mergeWithObject:(id)object;
- (id)valueForModelKey:(id)key;
- (void)setValue:(id)value forModelKey:(id)key;
- (id)_stateDumpObject;
- (BOOL)_isModelKey:(id)key;
- (id)_sanitizedStorage;
@end

#endif /* MPModelObject_h */
