//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.3.0.0
//
#ifndef MPModelLibraryPlaylistEditChangeRequest_h
#define MPModelLibraryPlaylistEditChangeRequest_h
@import Foundation;

#include "MPChangeDetails.h"
#include "MPMediaLibrary.h"
#include "MPModelPlaylist.h"
#include "MPSectionedCollection.h"
#include "NSCopying-Protocol.h"

@class NSDictionary, NSNumber, NSString, UIImage;

@interface MPModelLibraryPlaylistEditChangeRequest : NSObject<NSCopying>

@property (readonly, nonatomic) BOOL didSetPlaylistUserImage;
@property (retain, nonatomic) MPMediaLibrary *mediaLibrary;
@property (copy, nonatomic) MPSectionedCollection *playlistEntries;
@property (copy, nonatomic) NSString *playlistDescription;
@property (copy, nonatomic) NSString *playlistName;
@property (retain, nonatomic) UIImage *playlistUserImage;
@property (copy, nonatomic) NSNumber *publicPlaylist;
@property (copy, nonatomic) NSNumber *visiblePlaylist;
@property (copy, nonatomic) NSNumber *curatorPlaylist;
@property (copy, nonatomic) NSNumber *isOwner;
@property (copy, nonatomic) NSString *authorStoreIdentifier;
@property (copy, nonatomic) NSString *authorDisplayName;
@property (copy, nonatomic) NSString *coverArtworkRecipe;
@property (retain, nonatomic) MPChangeDetails *trackListChanges;
@property (copy, nonatomic) NSDictionary *deletedEntryUUIDs;
@property (retain, nonatomic) MPModelPlaylist *parentPlaylist;
@property (nonatomic) BOOL shouldCreatePlaylist;
@property (retain, nonatomic) MPModelPlaylist *playlist;
@property (copy, nonatomic) MPSectionedCollection *musicKitPlaylistEntries;

/* class methods */
+ (id)requiredPlaylistEntryProperties;

/* instance methods */
- (id)init;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)newOperationWithLocalPersistenceResponseHandler:(id /* block */)handler completeResponseHandler:(id /* block */)handler;
- (id)newSDKOperationWithLocalPersistenceResponseHandler:(id /* block */)handler completeResponseHandler:(id /* block */)handler;
- (id)isPublicPlaylist;
- (id)isVisiblePlaylist;
- (id)isCuratorPlaylist;
@end

#endif /* MPModelLibraryPlaylistEditChangeRequest_h */
