//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.3.0.0
//
#ifndef MPModelStoreBrowseContentItemBuilder_h
#define MPModelStoreBrowseContentItemBuilder_h
@import Foundation;

#include "MPStoreModelObjectBuilder.h"
#include "MPStoreModelAlbumBuilder.h"
#include "MPStoreModelArtistBuilder.h"
#include "MPStoreModelCreditsArtistBuilder.h"
#include "MPStoreModelCuratorBuilder.h"
#include "MPStoreModelMovieBuilder.h"
#include "MPStoreModelPlaylistBuilder.h"
#include "MPStoreModelRadioStationBuilder.h"
#include "MPStoreModelRecordLabelBuilder.h"
#include "MPStoreModelSocialPersonBuilder.h"
#include "MPStoreModelSongBuilder.h"
#include "MPStoreModelTVEpisodeBuilder.h"
#include "MPStoreModelTVSeasonBuilder.h"
#include "MPStoreModelTVShowBuilder.h"
#include "MPStoreModelTVShowCreatorBuilder.h"

@interface MPModelStoreBrowseContentItemBuilder : MPStoreModelObjectBuilder {
  /* instance variables */
  struct { unsigned int x :1 initialized; unsigned int x :1 itemType; unsigned int x :1 detailedItemType; unsigned int x :1 artist; unsigned int x :1 album; unsigned int x :1 curator; unsigned int x :1 episode; unsigned int x :1 movie; unsigned int x :1 playlist; unsigned int x :1 radioStation; unsigned int x :1 socialPerson; unsigned int x :1 song; unsigned int x :1 season; unsigned int x :1 show; unsigned int x :1 showCreator; unsigned int x :1 aucType; unsigned int x :1 recordLabel; unsigned int x :1 creditsArtist; } _requestedBrowseContentItemProperties;
  MPStoreModelAlbumBuilder *_albumBuilder;
  MPStoreModelArtistBuilder *_artistBuilder;
  MPStoreModelCuratorBuilder *_curatorBuilder;
  MPStoreModelTVEpisodeBuilder *_episodeBuilder;
  MPStoreModelMovieBuilder *_movieBuilder;
  MPStoreModelRadioStationBuilder *_radioStationBuilder;
  MPStoreModelSocialPersonBuilder *_socialPersonBuilder;
  MPStoreModelPlaylistBuilder *_playlistBuilder;
  MPStoreModelTVSeasonBuilder *_seasonBuilder;
  MPStoreModelSongBuilder *_songBuilder;
  MPStoreModelTVShowBuilder *_showBuilder;
  MPStoreModelTVShowCreatorBuilder *_showCreatorBuilder;
  MPStoreModelRecordLabelBuilder *_recordLabelBuilder;
  MPStoreModelCreditsArtistBuilder *_creditsArtistBuilder;
  BOOL _shouldFakeEpisodes;
}

@property (nonatomic) BOOL allowsRadioStations;
@property (nonatomic) BOOL allowsVideoContent;

/* class methods */
+ (id)allSupportedProperties;

/* instance methods */
- (id)initWithRequestedPropertySet:(id)set;
- (void)setPreventStoreItemMetadataCaching:(BOOL)caching;
- (long long)contentItemTypeForRawResponseKindIdentifierValue:(long long)value;
- (long long)contentItemTypeForRawResponseKindIdentifiers:(id)identifiers;
- (long long)contentItemTypeForStoreItemMetadata:(id)metadata;
- (long long)contentItemTypeForMusicAPIType:(id)apitype;
- (id)modelObjectWithStoreItemMetadata:(id)metadata sourceModelObject:(id)object userIdentity:(id)identity;
@end

#endif /* MPModelStoreBrowseContentItemBuilder_h */
