//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.3.0.0
//
#ifndef MPPlaybackUserDefaults_h
#define MPPlaybackUserDefaults_h
@import Foundation;

#include "MPPlaybackEQSetting.h"

@class NSDictionary, NSNumber, NSString, NSUserDefaults;
@protocol OS_dispatch_queue;

@interface MPPlaybackUserDefaults : NSObject {
  /* instance variables */
  NSUserDefaults *_iPodUserDefaults;
  NSUserDefaults *_videoUserDefaults;
  NSUserDefaults *_mediaPlaybackCoreUserDefaults;
  NSUserDefaults *_airplayUserDefaults;
  NSObject<OS_dispatch_queue> *_accountsQueue;
  struct { int mobileiPodPrefsChanged; int mobileiPodPlaybackPrefsChangedAllowCellularData; int videoPrefsChanged; int airplayPrefsChanged; } _notifyTokens;
}

@property (readonly, nonatomic) MPPlaybackEQSetting *musicEQSetting;
@property (nonatomic) long long musicRepeatType;
@property (nonatomic) long long musicShuffleType;
@property (nonatomic) BOOL soundCheckEnabled;
@property (nonatomic) BOOL crossFadeEnabled;
@property (nonatomic) double crossFadeDuration;
@property (nonatomic) float playbackRate;
@property (copy, nonatomic) NSNumber *privateListeningEnabled;
@property (readonly, copy, nonatomic) NSNumber *devicePrivateListeningEnabled;
@property (copy, nonatomic) NSNumber *focusModePrivateListeningEnabled;
@property (nonatomic) long long preferredMusicLowBandwidthResolution;
@property (nonatomic) long long preferredMusicHighBandwidthResolution;
@property (nonatomic) long long preferredMusicDownloadResolution;
@property (nonatomic) long long spatialAudioPreference;
@property (nonatomic) BOOL prefersSpatialAudio;
@property (nonatomic) BOOL prefersSpatialDownloads;
@property (nonatomic) BOOL showLosslessAudio;
@property (readonly, nonatomic) long long preferredVideoLowBandwidthResolution;
@property (readonly, nonatomic) long long preferredVideoHighBandwidthResolution;
@property (readonly, nonatomic) long long preferredVideoDownloadResolution;
@property (readonly, nonatomic) BOOL allowsHighQualityMusicStreamingOnCellular;
@property (readonly, nonatomic) float defaultVocalLevel;
@property (readonly, nonatomic) float minVocalLevel;
@property (readonly, nonatomic) BOOL allowScreenRecording;
@property (readonly, nonatomic) BOOL disableAssetCaching;
@property (readonly, nonatomic) BOOL disableHLSAssetCaching;
@property (readonly, nonatomic) NSNumber *progressiveDownloadAssetRatio;
@property (readonly, nonatomic) BOOL disableAudioAnalysis;
@property (readonly, nonatomic) BOOL disableAudioProcessing;
@property (readonly, nonatomic) BOOL disableMiniSINF;
@property (readonly, nonatomic) BOOL disablePeriodicStateRestore;
@property (readonly, nonatomic) BOOL disableQHO;
@property (readonly, nonatomic) BOOL enableProcessTap;
@property (readonly, nonatomic) unsigned long long audioAnalysisRefreshRate;
@property (readonly, nonatomic) BOOL forceMusicResolution;
@property (readonly, nonatomic) long long forcedMusicResolution;
@property (readonly, nonatomic) BOOL forceMusicStreaming;
@property (readonly, nonatomic) BOOL forceLibrarySupplementalContexts;
@property (readonly, nonatomic) BOOL includeContentItemDebugFields;
@property (readonly, nonatomic) long long maximumQueueHandOffSize;
@property (readonly, nonatomic) BOOL showDebugUI;
@property (readonly, nonatomic) BOOL speakerRouteEnabled;
@property (readonly, nonatomic) double assetURLExpirationDuration;
@property (readonly, nonatomic) double playbackAuthorizationTokenHalfLifeDuration;
@property (readonly, nonatomic) double activationDelay;
@property (readonly, nonatomic) double forwardBufferDuration;
@property (readonly, nonatomic) BOOL prerollEnabled;
@property (readonly, nonatomic) BOOL archiveSessionArtwork;
@property (readonly, nonatomic) BOOL shouldPurgeSideLoadedVocalAttenuationModels;
@property (readonly, nonatomic) BOOL shouldRecordVocalAttenuationStatistics;
@property (readonly, copy, nonatomic) NSString *vocalAttenuationStatisticsName;
@property (readonly, nonatomic) BOOL shouldBypassVocalAttenuationDenoising;
@property (readonly, nonatomic) BOOL shouldBypassVocalAttenuationSupportFlag;
@property (readonly, nonatomic) BOOL shouldUseRemoteVocalAttenuationModel;
@property (readonly, nonatomic) BOOL shouldUseSideLoadedVocalAttenuationModel;
@property (readonly, nonatomic) float audioTapTimeOutRatioForFailureDetection;
@property (readonly, nonatomic) double vocalAttenuationGracePeriodAfterPause;
@property (readonly, nonatomic) BOOL vocalAttenuationLogInputAndOuputRMSValues;
@property (readonly, copy, nonatomic) NSNumber *forcedIntentDestination;
@property (readonly, copy, nonatomic) NSNumber *delayQueueLoadDuration;
@property (readonly, copy, nonatomic) NSNumber *delayAssetLoadDuration;
@property (readonly, nonatomic) BOOL forceDisableUpNext;
@property (readonly, nonatomic) BOOL ignoreDisableUpNext;
@property (readonly, nonatomic) double HomePodPFSQForcedLeaseRenewThreshold;
@property (readonly, nonatomic) double unloadingPlaybackAssetsOnIdleDuration;
@property (readonly, nonatomic) long long artworkCacheLimit;
@property (readonly, nonatomic) long long exportableArtworkCacheLimit;
@property (readonly, copy, nonatomic) NSDictionary *rewrittenAssetInfo;
@property (readonly, nonatomic) BOOL shouldSkipNextStateRestoration;

/* class methods */
+ (id)standardUserDefaults;

/* instance methods */
- (id)_init;
- (void)dealloc;
- (BOOL)autoPlayEnabledForUserIdentity:(id)identity;
- (void)setAutoPlayEnabled:(BOOL)enabled forUserIdentity:(id)identity;
- (BOOL)isCrossFadeEnabled;
- (id)isPrivateListeningEnabled;
- (id)isDevicePrivateListeningEnabled;
- (id)isFocusModePrivateListeningEnabled;
- (BOOL)isProcessTapEnabled;
- (void)clearShouldSkipNextStateRestoration;
- (void)resetAllInternalSettings;
- (void)_migrateUserDefaults;
- (void)_loadAccountProperties;
- (void)_accountStoreChangedNotification:(id)notification;
@end

#endif /* MPPlaybackUserDefaults_h */
