//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.3.0.0
//
#ifndef MPSubscriptionStatusPlaybackInformation_h
#define MPSubscriptionStatusPlaybackInformation_h
@import Foundation;

@class ICMusicSubscriptionStatus;

@interface MPSubscriptionStatusPlaybackInformation : NSObject {
  /* instance variables */
  ICMusicSubscriptionStatus *_subscriptionStatusObject;
}

@property (readonly, nonatomic) BOOL definitiveInformation;
@property (readonly, nonatomic) BOOL hasPlaybackCapability;
@property (readonly, nonatomic) BOOL requiresCarrierManualVerification;
@property (readonly, nonatomic) BOOL shouldUseLease;
@property (readonly, nonatomic) BOOL shouldUseAccountLessStreaming;
@property (readonly, nonatomic) BOOL shouldRequirePlaybackAuthorizationTokensForPlayback;

/* instance methods */
- (id)initWithICSubscriptionStatus:(id)status;
- (id)description;
- (BOOL)isDefinitiveInformation;
@end

#endif /* MPSubscriptionStatusPlaybackInformation_h */
