//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 685.60.2.0.0
//
#ifndef TKSmartCardATRInterfaceGroup_h
#define TKSmartCardATRInterfaceGroup_h
@import Foundation;

@class NSNumber;

@interface TKSmartCardATRInterfaceGroup : NSObject {
  /* instance variables */
  NSNumber * _ABC[3];
}

@property (readonly, nonatomic) NSNumber *TA;
@property (readonly, nonatomic) NSNumber *TB;
@property (readonly, nonatomic) NSNumber *TC;
@property (readonly, nonatomic) NSNumber *protocol;

/* instance methods */
- (id)initWithProtocol:(id)protocol;
- (id)parseWithY:(char *)y toProtocol:(id *)protocol fromSource:(id /* block */)source hasNext:(BOOL *)next;
- (id)description;
@end

#endif /* TKSmartCardATRInterfaceGroup_h */
