//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 207.0.0.0.0
//
#ifndef WatchConnectivity_h
#define WatchConnectivity_h

#import "WCActiveDeviceSwitchTask.h"
#import "WCComplicationManager.h"
#import "WCContentIndex.h"
#import "WCDProtoUserInfoTransfer.h"
#import "WCDataMessageRecord.h"
#import "WCDictionaryMessageRecord.h"
#import "WCFileStorage.h"
#import "WCMessage.h"
#import "WCMessageRecord.h"
#import "WCMessageRequest.h"
#import "WCMessageResponse.h"
#import "WCPrivateXPCManager.h"
#import "WCQueueManager.h"
#import "WCQueuedMessage.h"
#import "WCSession.h"
#import "WCSessionFile.h"
#import "WCSessionFileTransfer.h"
#import "WCSessionState.h"
#import "WCSessionUserInfoTransfer.h"
#import "WCUserInfo.h"
#import "WCXPCManager.h"
#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSFastEnumeration-Protocol.h"
#import "NSFilePresenter-Protocol.h"
#import "NSObject-Protocol.h"
#import "NSSecureCoding-Protocol.h"
#import "NSXPCConnectionDelegate-Protocol.h"
#import "WCPrivateXPCManagerDelegate-Protocol.h"
#import "WCXPCManagerClientProtocol-Protocol.h"
#import "WCXPCManagerDaemonProtocol-Protocol.h"
#import "WCXPCManagerDelegate-Protocol.h"
#import "WCXPCManagerSharedProtocol-Protocol.h"
#import "WCXPCPrivateManagerClientProtocol-Protocol.h"
#import "WCXPCPrivateManagerDaemonProtocol-Protocol.h"
#import "NSError+WCError.h"

#endif /* WatchConnectivity_h */
