//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 207.0.0.0.0
//
#ifndef WCSessionUserInfoTransfer_h
#define WCSessionUserInfoTransfer_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"
#include "WCUserInfo.h"

@class NSData, NSDate, NSDictionary, NSError, NSString;

@interface WCSessionUserInfoTransfer : NSObject<NSSecureCoding>

@property (retain, nonatomic) WCUserInfo *userInfoStorage;
@property (retain, nonatomic) NSDate *creationDate;
@property (retain) NSError *transferError;
@property (copy) NSString *transferIdentifier;
@property (readonly, copy) NSData *userInfoData;
@property (copy) NSString *complicationTransferIdentifier;
@property (nonatomic) BOOL currentComplicationInfo;
@property (nonatomic) BOOL transferring;
@property (readonly, copy, nonatomic) NSDictionary *userInfo;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithComplicationTransferIdentifier:(id)identifier;
- (id)initWithTranferIdentifier:(id)identifier complicationTransferIdentifier:(id)identifier currentComplication:(BOOL)complication;
- (id)initWithProtoBufFileURL:(id)url;
- (id)init;
- (BOOL)updateUserInfo:(id)info error:(id *)error;
- (BOOL)updateUserInfoData:(id)data error:(id *)error;
- (BOOL)verifyUserInfo;
- (void)cancel;
- (long long)compare:(id)compare;
- (id)description;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)protobufData;
- (BOOL)isCurrentComplicationInfo;
- (BOOL)isTransferring;
@end

#endif /* WCSessionUserInfoTransfer_h */
