//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3090.15.3.1.0
//
#ifndef FigKVCInspectable_h
#define FigKVCInspectable_h
@import Foundation;

@interface FigKVCInspectable : NSObject
/* instance methods */
- (id)valueForUndefinedKey:(id)key;
- (BOOL)validateValue:(inout id *)value forKey:(id)key error:(id *)error;
- (BOOL)validateValue:(inout id *)value forKeyPath:(id)path error:(id *)error;
@end

#endif /* FigKVCInspectable_h */
