//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1387.3.4.0.0
//
#ifndef SSCoreHapticsInfo_h
#define SSCoreHapticsInfo_h
@import Foundation;

@interface SSCoreHapticsInfo : NSObject
/* class methods */
+ (id)instance;

/* instance methods */
- (unsigned long long)generateNewSSIDForPlayer:(id)player;
- (id)getPlayerForSSID:(unsigned long long)ssid;
- (void)disposeSSID:(unsigned long long)ssid;
@end

#endif /* SSCoreHapticsInfo_h */
