//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 800.2.0.3.0
//
#ifndef _CTFontFallbacksArray_h
#define _CTFontFallbacksArray_h
@import Foundation;

#include "NSArray.h"

@class NSMutableArray;

@interface _CTFontFallbacksArray : NSArray {
  /* instance variables */
  struct TUnfairLock { struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } fLock; } _lock;
  const void * _baseFont;
  const struct TTraitsValues { unsigned int x0; double x1; double x2; double x3; } * _refTraits;
  unsigned long long _count;
  NSMutableArray *_cascade;
  NSMutableArray *_fallbacks;
  unsigned long long _hash;
  int _uiUse;
}

/* instance methods */
- (void)dealloc;
- (unsigned long long)count;
- (id)objectAtIndex:(unsigned long long)index;
- (void)getObjects:(id *)objects range:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (unsigned long long)countByEnumeratingWithState:(struct { unsigned long long x0; id * x1; unsigned long long * x2; unsigned long long x3[5] } *)state objects:(id *)objects count:(unsigned long long)count;
@end

#endif /* _CTFontFallbacksArray_h */
