//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 956.0.0.0.0
//
#ifndef ACNotifyWriting_Protocol_h
#define ACNotifyWriting_Protocol_h
@import Foundation;

@protocol ACNotifyWriting <NSObject>
/* instance methods */
- (id)initWithKey:(id)key;
- (void)write:(unsigned long long)write;
@end

#endif /* ACNotifyWriting_Protocol_h */
