//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 956.0.0.0.0
//
#ifndef ACPluginLoader_h
#define ACPluginLoader_h
@import Foundation;

@interface ACPluginLoader : NSObject
/* class methods */
+ (id)_accountsPluginDirectoryURLs:(id)urls inAppleInternal:(BOOL)internal;
+ (id)_validatedBundleAtURL:(id)url;
+ (void)_populatePluginBundles:(id)bundles atSubpath:(id)subpath inAppleInternal:(BOOL)internal;
+ (id)pluginBundlesAtSubpath:(id)subpath;
+ (id)_pluginWithName:(id)name inSubpath:(id)subpath inAppleInternal:(BOOL)internal;
+ (id)pluginWithName:(id)name inSubpath:(id)subpath;
@end

#endif /* ACPluginLoader_h */
