//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1110.5.0.0.0
//
#ifndef CAMetalDisplayLink_h
#define CAMetalDisplayLink_h
@import Foundation;

@protocol CAMetalDisplayLinkDelegate;

@interface CAMetalDisplayLink : NSObject {
  /* instance variables */
  void * _impl;
}

@property (weak, nonatomic) NSObject<CAMetalDisplayLinkDelegate> *delegate;
@property (nonatomic) float preferredFrameLatency;
@property (nonatomic) struct CAFrameRateRange { float x0; float x1; float x2; } preferredFrameRateRange;
@property (nonatomic) BOOL paused;

/* instance methods */
- (id)_initWithMetalLinkItem:(void *)item;
- (id)initWithMetalLayer:(id)layer;
- (void)dealloc;
- (void)addToRunLoop:(id)loop forMode:(id)mode;
- (void)removeFromRunLoop:(id)loop forMode:(id)mode;
- (void)invalidate;
- (BOOL)isPaused;
@end

#endif /* CAMetalDisplayLink_h */
