//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1110.5.0.0.0
//
#ifndef CAMeshInterpolator_h
#define CAMeshInterpolator_h
@import Foundation;

#include "CAMeshTransform.h"

@interface CAMeshInterpolator : CAMeshTransform {
  /* instance variables */
  void * _interp;
}

/* instance methods */
- (void)dealloc;
- (id)meshTransformForLayer:(id)layer;
@end

#endif /* CAMeshInterpolator_h */
