//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBSearchForBillsIntent_h
#define _INPBSearchForBillsIntent_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBBillPayeeValue.h"
#include "_INPBDateTimeRange.h"
#include "_INPBIntentMetadata.h"
#include "_INPBSearchForBillsIntent-Protocol.h"

@class NSString;

@interface _INPBSearchForBillsIntent : PBCodable<_INPBSearchForBillsIntent, NSSecureCoding, NSCopying> {
  /* instance variables */
  struct { unsigned int x :1 billType; unsigned int x :1 status; } _has;
}

@property (retain, nonatomic) _INPBBillPayeeValue *billPayee;
@property (readonly, nonatomic) BOOL hasBillPayee;
@property (nonatomic) int billType;
@property (nonatomic) BOOL hasBillType;
@property (retain, nonatomic) _INPBDateTimeRange *dueDateRange;
@property (readonly, nonatomic) BOOL hasDueDateRange;
@property (retain, nonatomic) _INPBIntentMetadata *intentMetadata;
@property (readonly, nonatomic) BOOL hasIntentMetadata;
@property (retain, nonatomic) _INPBDateTimeRange *paymentDateRange;
@property (readonly, nonatomic) BOOL hasPaymentDateRange;
@property (nonatomic) int status;
@property (nonatomic) BOOL hasStatus;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)billTypeAsString:(int)string;
- (int)StringAsBillType:(id)type;
- (id)statusAsString:(int)string;
- (int)StringAsStatus:(id)status;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (id)dictionaryRepresentation;
@end

#endif /* _INPBSearchForBillsIntent_h */
