//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBSetNumericSettingIntent_Protocol_h
#define _INPBSetNumericSettingIntent_Protocol_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBIntentMetadata.h"
#include "_INPBNumericSettingValue.h"
#include "_INPBSetNumericSettingIntent-Protocol.h"
#include "_INPBSettingMetadata.h"
#include "_INPBTemporalEventTrigger.h"

@class NSString;

@protocol _INPBSetNumericSettingIntent <NSObject>

@property (nonatomic) int action;
@property (nonatomic) BOOL hasAction;
@property (nonatomic) int boundedValue;
@property (nonatomic) BOOL hasBoundedValue;
@property (retain, nonatomic) _INPBIntentMetadata *intentMetadata;
@property (readonly, nonatomic) BOOL hasIntentMetadata;
@property (retain, nonatomic) _INPBNumericSettingValue *numericValue;
@property (readonly, nonatomic) BOOL hasNumericValue;
@property (retain, nonatomic) _INPBSettingMetadata *settingMetadata;
@property (readonly, nonatomic) BOOL hasSettingMetadata;
@property (retain, nonatomic) _INPBTemporalEventTrigger *temporalEventTrigger;
@property (readonly, nonatomic) BOOL hasTemporalEventTrigger;

/* instance methods */
- (id)actionAsString:(int)string;
- (int)StringAsAction:(id)action;
- (id)boundedValueAsString:(int)string;
- (int)StringAsBoundedValue:(id)value;
@end

#endif /* _INPBSetNumericSettingIntent_Protocol_h */
