//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBStartWorkoutIntent_Protocol_h
#define _INPBStartWorkoutIntent_Protocol_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBDataString.h"
#include "_INPBDouble.h"
#include "_INPBIntentMetadata.h"
#include "_INPBStartWorkoutIntent-Protocol.h"
#include "_INPBWorkoutCustomization.h"

@class NSArray, NSString;

@protocol _INPBStartWorkoutIntent <NSObject>

@property (copy, nonatomic) NSArray *associatedItems;
@property (readonly, nonatomic) unsigned long long associatedItemsCount;
@property (retain, nonatomic) _INPBWorkoutCustomization *customization;
@property (readonly, nonatomic) BOOL hasCustomization;
@property (retain, nonatomic) _INPBDouble *goalValue;
@property (readonly, nonatomic) BOOL hasGoalValue;
@property (retain, nonatomic) _INPBIntentMetadata *intentMetadata;
@property (readonly, nonatomic) BOOL hasIntentMetadata;
@property (nonatomic) BOOL isBuiltInWorkoutType;
@property (nonatomic) BOOL hasIsBuiltInWorkoutType;
@property (nonatomic) BOOL isOpenEnded;
@property (nonatomic) BOOL hasIsOpenEnded;
@property (nonatomic) BOOL isVoiceOnly;
@property (nonatomic) BOOL hasIsVoiceOnly;
@property (nonatomic) int sequenceLabel;
@property (nonatomic) BOOL hasSequenceLabel;
@property (nonatomic) int workoutGoalUnitType;
@property (nonatomic) BOOL hasWorkoutGoalUnitType;
@property (nonatomic) int workoutLocationType;
@property (nonatomic) BOOL hasWorkoutLocationType;
@property (retain, nonatomic) _INPBDataString *workoutName;
@property (readonly, nonatomic) BOOL hasWorkoutName;

/* class methods */
+ (Class)associatedItemsType;
/* instance methods */
- (void)clearAssociatedItems;
- (void)addAssociatedItems:(id)items;
- (id)associatedItemsAtIndex:(unsigned long long)index;
- (id)sequenceLabelAsString:(int)string;
- (int)StringAsSequenceLabel:(id)label;
- (id)workoutGoalUnitTypeAsString:(int)string;
- (int)StringAsWorkoutGoalUnitType:(id)type;
- (id)workoutLocationTypeAsString:(int)string;
- (int)StringAsWorkoutLocationType:(id)type;
@end

#endif /* _INPBStartWorkoutIntent_Protocol_h */
