//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBLodgingReservation_Protocol_h
#define _INPBLodgingReservation_Protocol_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBDateTimeRange.h"
#include "_INPBInteger.h"
#include "_INPBLocation.h"
#include "_INPBLodgingReservation-Protocol.h"
#include "_INPBReservation.h"

@class NSString;

@protocol _INPBLodgingReservation <NSObject>

@property (retain, nonatomic) _INPBLocation *lodgingBusinessLocation;
@property (readonly, nonatomic) BOOL hasLodgingBusinessLocation;
@property (retain, nonatomic) _INPBInteger *numberOfAdults;
@property (readonly, nonatomic) BOOL hasNumberOfAdults;
@property (retain, nonatomic) _INPBInteger *numberOfChildren;
@property (readonly, nonatomic) BOOL hasNumberOfChildren;
@property (retain, nonatomic) _INPBReservation *reservation;
@property (readonly, nonatomic) BOOL hasReservation;
@property (retain, nonatomic) _INPBDateTimeRange *reservationDuration;
@property (readonly, nonatomic) BOOL hasReservationDuration;

@end

#endif /* _INPBLodgingReservation_Protocol_h */
