//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBGetReservationDetailsIntent_h
#define _INPBGetReservationDetailsIntent_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBDataString.h"
#include "_INPBGetReservationDetailsIntent-Protocol.h"
#include "_INPBIntentMetadata.h"

@class NSArray, NSString;

@interface _INPBGetReservationDetailsIntent : PBCodable<_INPBGetReservationDetailsIntent, NSSecureCoding, NSCopying> {
  /* instance variables */
  struct  _has;
}

@property (retain, nonatomic) _INPBIntentMetadata *intentMetadata;
@property (readonly, nonatomic) BOOL hasIntentMetadata;
@property (retain, nonatomic) _INPBDataString *reservationContainerReference;
@property (readonly, nonatomic) BOOL hasReservationContainerReference;
@property (copy, nonatomic) NSArray *reservationItemReferences;
@property (readonly, nonatomic) unsigned long long reservationItemReferencesCount;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (Class)reservationItemReferencesType;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (void)clearReservationItemReferences;
- (void)addReservationItemReferences:(id)references;
- (id)reservationItemReferencesAtIndex:(unsigned long long)index;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (id)dictionaryRepresentation;
@end

#endif /* _INPBGetReservationDetailsIntent_h */
