//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBRideVehicle_Protocol_h
#define _INPBRideVehicle_Protocol_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBImageValue.h"
#include "_INPBRideVehicle-Protocol.h"

@class GEOLocation, NSString;

@protocol _INPBRideVehicle <NSObject>

@property (retain, nonatomic) GEOLocation *location;
@property (readonly, nonatomic) BOOL hasLocation;
@property (copy, nonatomic) NSString *manufacturer;
@property (readonly, nonatomic) BOOL hasManufacturer;
@property (retain, nonatomic) _INPBImageValue *mapAnnotationImage;
@property (readonly, nonatomic) BOOL hasMapAnnotationImage;
@property (copy, nonatomic) NSString *model;
@property (readonly, nonatomic) BOOL hasModel;
@property (copy, nonatomic) NSString *registrationPlate;
@property (readonly, nonatomic) BOOL hasRegistrationPlate;

@end

#endif /* _INPBRideVehicle_Protocol_h */
