//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBSetBinarySettingIntentResponse_Protocol_h
#define _INPBSetBinarySettingIntentResponse_Protocol_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBSetBinarySettingIntentResponse-Protocol.h"

@class NSString;

@protocol _INPBSetBinarySettingIntentResponse <NSObject>

@property (copy, nonatomic) NSString *errorDetail;
@property (readonly, nonatomic) BOOL hasErrorDetail;
@property (nonatomic) int oldValue;
@property (nonatomic) BOOL hasOldValue;
@property (nonatomic) int updatedValue;
@property (nonatomic) BOOL hasUpdatedValue;

/* instance methods */
- (id)oldValueAsString:(int)string;
- (int)StringAsOldValue:(id)value;
- (id)updatedValueAsString:(int)string;
- (int)StringAsUpdatedValue:(id)value;
@end

#endif /* _INPBSetBinarySettingIntentResponse_Protocol_h */
