//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBQueryHealthSampleIntent_Protocol_h
#define _INPBQueryHealthSampleIntent_Protocol_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBIntentMetadata.h"
#include "_INPBQueryHealthSampleIntent-Protocol.h"
#include "_INPBWellnessUnitType.h"

@class NSArray, NSString;

@protocol _INPBQueryHealthSampleIntent <NSObject>

@property (nonatomic) int expectedResultType;
@property (nonatomic) BOOL hasExpectedResultType;
@property (retain, nonatomic) _INPBIntentMetadata *intentMetadata;
@property (readonly, nonatomic) BOOL hasIntentMetadata;
@property (nonatomic) int objectType;
@property (nonatomic) BOOL hasObjectType;
@property (nonatomic) int questionType;
@property (nonatomic) BOOL hasQuestionType;
@property (copy, nonatomic) NSArray *recordDates;
@property (readonly, nonatomic) unsigned long long recordDatesCount;
@property (copy, nonatomic) NSArray *thresholdValues;
@property (readonly, nonatomic) unsigned long long thresholdValuesCount;
@property (retain, nonatomic) _INPBWellnessUnitType *unit;
@property (readonly, nonatomic) BOOL hasUnit;

/* class methods */
+ (Class)recordDateType;
+ (Class)thresholdValuesType;
/* instance methods */
- (id)expectedResultTypeAsString:(int)string;
- (int)StringAsExpectedResultType:(id)type;
- (id)objectTypeAsString:(int)string;
- (int)StringAsObjectType:(id)type;
- (id)questionTypeAsString:(int)string;
- (int)StringAsQuestionType:(id)type;
- (void)clearRecordDates;
- (void)addRecordDate:(id)date;
- (id)recordDateAtIndex:(unsigned long long)index;
- (void)clearThresholdValues;
- (void)addThresholdValues:(id)values;
- (id)thresholdValuesAtIndex:(unsigned long long)index;
@end

#endif /* _INPBQueryHealthSampleIntent_Protocol_h */
