//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBCallGroupConversationFilter_h
#define _INPBCallGroupConversationFilter_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBCallGroup.h"
#include "_INPBCallGroupConversationFilter-Protocol.h"
#include "_INPBContact.h"

@class NSArray, NSString;

@interface _INPBCallGroupConversationFilter : PBCodable<_INPBCallGroupConversationFilter, NSSecureCoding, NSCopying> {
  /* instance variables */
  struct { unsigned int x :1 matchCallerAndParticipantsExactly; } _has;
}

@property (retain, nonatomic) _INPBCallGroup *callGroup;
@property (readonly, nonatomic) BOOL hasCallGroup;
@property (retain, nonatomic) _INPBContact *caller;
@property (readonly, nonatomic) BOOL hasCaller;
@property (nonatomic) BOOL matchCallerAndParticipantsExactly;
@property (nonatomic) BOOL hasMatchCallerAndParticipantsExactly;
@property (copy, nonatomic) NSArray *participants;
@property (readonly, nonatomic) unsigned long long participantsCount;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (Class)participantsType;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (void)clearParticipants;
- (void)addParticipants:(id)participants;
- (id)participantsAtIndex:(unsigned long long)index;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (id)dictionaryRepresentation;
@end

#endif /* _INPBCallGroupConversationFilter_h */
