//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBUnsendMessagesIntent_Protocol_h
#define _INPBUnsendMessagesIntent_Protocol_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBIntentMetadata.h"
#include "_INPBUnsendMessagesIntent-Protocol.h"

@class NSArray, NSString;

@protocol _INPBUnsendMessagesIntent <NSObject>

@property (retain, nonatomic) _INPBIntentMetadata *intentMetadata;
@property (readonly, nonatomic) BOOL hasIntentMetadata;
@property (copy, nonatomic) NSArray *messageIdentifiers;
@property (readonly, nonatomic) unsigned long long messageIdentifiersCount;

/* instance methods */
- (void)clearMessageIdentifiers;
- (void)addMessageIdentifiers:(id)identifiers;
- (id)messageIdentifiersAtIndex:(unsigned long long)index;
@end

#endif /* _INPBUnsendMessagesIntent_Protocol_h */
