//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBRentalCar_h
#define _INPBRentalCar_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBRentalCar-Protocol.h"

@class NSString;

@interface _INPBRentalCar : PBCodable<_INPBRentalCar, NSSecureCoding, NSCopying> {
  /* instance variables */
  struct  _has;
}

@property (copy, nonatomic) NSString *make;
@property (readonly, nonatomic) BOOL hasMake;
@property (copy, nonatomic) NSString *model;
@property (readonly, nonatomic) BOOL hasModel;
@property (copy, nonatomic) NSString *rentalCarDescription;
@property (readonly, nonatomic) BOOL hasRentalCarDescription;
@property (copy, nonatomic) NSString *rentalCompanyName;
@property (readonly, nonatomic) BOOL hasRentalCompanyName;
@property (copy, nonatomic) NSString *type;
@property (readonly, nonatomic) BOOL hasType;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (id)dictionaryRepresentation;
@end

#endif /* _INPBRentalCar_h */
