//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBDeleteTasksIntentResponse_Protocol_h
#define _INPBDeleteTasksIntentResponse_Protocol_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBDeleteTasksIntentResponse-Protocol.h"

@class NSArray, NSString;

@protocol _INPBDeleteTasksIntentResponse <NSObject>

@property (copy, nonatomic) NSArray *deletedTasks;
@property (readonly, nonatomic) unsigned long long deletedTasksCount;

/* class methods */
+ (Class)deletedTasksType;
/* instance methods */
- (void)clearDeletedTasks;
- (void)addDeletedTasks:(id)tasks;
- (id)deletedTasksAtIndex:(unsigned long long)index;
@end

#endif /* _INPBDeleteTasksIntentResponse_Protocol_h */
