//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBDeleteHealthSampleIntent_Protocol_h
#define _INPBDeleteHealthSampleIntent_Protocol_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBDeleteHealthSampleIntent-Protocol.h"
#include "_INPBIntentMetadata.h"

@class NSArray, NSString;

@protocol _INPBDeleteHealthSampleIntent <NSObject>

@property (retain, nonatomic) _INPBIntentMetadata *intentMetadata;
@property (readonly, nonatomic) BOOL hasIntentMetadata;
@property (copy, nonatomic) NSArray *sampleUuids;
@property (readonly, nonatomic) unsigned long long sampleUuidsCount;

/* class methods */
+ (Class)sampleUuidsType;
/* instance methods */
- (void)clearSampleUuids;
- (void)addSampleUuids:(id)uuids;
- (id)sampleUuidsAtIndex:(unsigned long long)index;
@end

#endif /* _INPBDeleteHealthSampleIntent_Protocol_h */
