//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBProperty_Protocol_h
#define _INPBProperty_Protocol_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBIntentSlotValue.h"
#include "_INPBProperty-Protocol.h"

@class NSString;

@protocol _INPBProperty <NSObject>

@property (retain, nonatomic) _INPBIntentSlotValue *payload;
@property (readonly, nonatomic) BOOL hasPayload;
@property (copy, nonatomic) NSString *role;
@property (readonly, nonatomic) BOOL hasRole;

@end

#endif /* _INPBProperty_Protocol_h */
