//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef _INPBActivateCarSignalIntentResponse_Protocol_h
#define _INPBActivateCarSignalIntentResponse_Protocol_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "_INPBActivateCarSignalIntentResponse-Protocol.h"

@class NSString;

@protocol _INPBActivateCarSignalIntentResponse <NSObject>

@property (readonly, nonatomic) int * signals;
@property (readonly, nonatomic) unsigned long long signalsCount;

/* instance methods */
- (void)clearSignals;
- (void)addSignals:(int)signals;
- (int)signalsAtIndex:(unsigned long long)index;
- (void)setSignals:(int *)signals count:(unsigned long long)count;
- (id)signalsAsString:(int)string;
- (int)StringAsSignals:(id)signals;
@end

#endif /* _INPBActivateCarSignalIntentResponse_Protocol_h */
