//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INBooleanResolutionResult_h
#define INBooleanResolutionResult_h
@import Foundation;

#include "INIntentResolutionResult.h"
#include "INBooleanResolutionResultExport-Protocol.h"

@class NSString;

@interface INBooleanResolutionResult : INIntentResolutionResult<INBooleanResolutionResultExport>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)successWithResolvedValue:(BOOL)value;
+ (id)confirmationRequiredWithValueToConfirm:(id)confirm;

/* instance methods */
- (id)_intentSlotValueForObject:(id)object slotDescription:(id)description;
- (id)_vocabularyValueForObject:(id)object slotDescription:(id)description;
@end

#endif /* INBooleanResolutionResult_h */
