//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INCreateNoteIntentExport_Protocol_h
#define INCreateNoteIntentExport_Protocol_h
@import Foundation;

@protocol INCreateNoteIntentExport <NSObject, JSExport>

@property (copy, nonatomic) INSpeakableString *title;
@property (copy, nonatomic) INNoteContent *content;
@property (copy, nonatomic) INSpeakableString *groupName;

/* instance methods */
- (id)init;
@end

#endif /* INCreateNoteIntentExport_Protocol_h */
