//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INExecutionInfoResolver_h
#define INExecutionInfoResolver_h
@import Foundation;

#include "INExecutionCounterpartMapper.h"
#include "INExecutionFrameworkMapper.h"

@class NSDictionary;

@interface INExecutionInfoResolver : NSObject {
  /* instance variables */
  INExecutionCounterpartMapper *_counterpartMapper;
  INExecutionFrameworkMapper *_frameworkMapper;
}

@property (readonly, copy, nonatomic) NSDictionary *_counterpartMapping;
@property (readonly, nonatomic) INExecutionCounterpartMapper *_counterpartMapper;
@property (readonly, nonatomic) INExecutionFrameworkMapper *_frameworkMapper;

/* class methods */
+ (void)initialize;
+ (id)defaultResolver;

/* instance methods */
- (id)resolveIntentExecutionInfo:(id)info;
- (id)resolveUserActivityExecutionInfo:(id)info;
- (id)localIdentifiersForCounterpartIdentifier:(id)identifier;
- (id)counterpartIdentifiersForLocalIdentifier:(id)identifier;
- (id)counterpartBundleIdentifiersForBundleIdentifier:(id)identifier;
- (id)_resolveExecutionInfo:(id)info;
- (id)_resolveExecutionInfoBySwappingIdentifiers:(id)identifiers;
- (id)_resolveExecutionInfoByLinkingExtensionToApp:(id)app;
- (id)_resolveIntentExecutionInfoBySwappingIdentifiers:(id)identifiers;
- (id)_resolveIntentExecutionInfoByLinkingExtensionToApp:(id)app;
- (id)_resolveIntentExecutionInfoUsingCounterparts:(id)counterparts;
- (id)_resolveUserActivityExecutionInfoBySwappingIdentifiers:(id)identifiers;
- (id)_resolveUserActivityExecutionInfoByLinkingFileProvidersToFilesApp:(id)app;
- (id)_resolveUserActivityExecutionInfoUsingCounterparts:(id)counterparts;
@end

#endif /* INExecutionInfoResolver_h */
