//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INFile_h
#define INFile_h
@import Foundation;

#include "INEnumerable-Protocol.h"
#include "INJSONSerializable-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSData, NSNumber, NSString, NSURL;

@interface INFile : NSObject<INEnumerable, INJSONSerializable, NSSecureCoding> {
  /* instance variables */
  NSData *_memoryMappedFileData;
  BOOL _deletesFileOnDeallocationIfNeeded;
  NSData *_bookmarkData;
  NSNumber *_removedOnCompletionValue;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy, nonatomic) NSData *_bookmarkData;
@property (readonly, nonatomic) BOOL _hasAssociatedAuditToken;
@property (nonatomic) BOOL _markedForDeletionOnDeallocation;
@property (nonatomic) BOOL _deletesFileOnDeallocationIfNeeded;
@property (nonatomic) struct { unsigned int x0[8] } _associatedAuditToken;
@property (readonly, nonatomic) BOOL _isFileURLBased;
@property (copy, nonatomic) NSNumber *_removedOnCompletionValue;
@property (readonly, copy, nonatomic) NSData *data;
@property (copy, nonatomic) NSString *filename;
@property (readonly, copy, nonatomic) NSString *typeIdentifier;
@property (readonly, nonatomic) NSURL *fileURL;
@property (nonatomic) BOOL removedOnCompletion;

/* class methods */
+ (id)_intents_decodeWithJSONDecoder:(id)jsondecoder codableDescription:(id)description from:(id)from;
+ (void)initialize;
+ (id)fileWithData:(id)data filename:(id)filename typeIdentifier:(id)identifier;
+ (id)fileWithFileURL:(id)url filename:(id)filename typeIdentifier:(id)identifier;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)_intents_encodeWithJSONEncoder:(id)jsonencoder codableDescription:(id)description;
- (BOOL)_intents_enumerateObjectsOfClass:(Class)class withBlock:(id /* block */)block;
- (id)_intents_readableTitleWithLocalizer:(id)localizer metadata:(id)metadata;
- (id)_initWithData:(id)data filename:(id)filename fileURL:(id)url typeIdentifier:(id)identifier removedOnCompletion:(id)completion;
- (id)_initWithBookmarkData:(id)data filename:(id)filename typeIdentifier:(id)identifier removedOnCompletion:(id)completion;
- (void)dealloc;
- (BOOL)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)_dictionaryRepresentation;
- (BOOL)_isMarkedForDeletionOnDeallocation;
- (void)_setMarkedForDeletionOnDeallocation:(BOOL)deallocation;
- (BOOL)_associatedAuditTokenIsEqualToAuditToken:(struct { unsigned int x0[8] })token;
- (void)_setAssociatedAuditToken:(struct { unsigned int x0[8] })token;
- (void)_setDeletesFileOnDeallocationIfNeeded:(BOOL)needed;
- (void)_setRemovedOnCompletionValue:(id)value;
@end

#endif /* INFile_h */
