//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INIntentAirportSlotValueTransformer_h
#define INIntentAirportSlotValueTransformer_h
@import Foundation;

#include "NSValueTransformer.h"

@interface INIntentAirportSlotValueTransformer : NSValueTransformer
/* class methods */
+ (Class)transformedValueClass;
+ (Class)reverseTransformedValueClass;
+ (BOOL)allowsReverseTransformation;
+ (long long)_intents_valueType;

/* instance methods */
- (id)transformedValue:(id)value;
- (id)reverseTransformedValue:(id)value;
@end

#endif /* INIntentAirportSlotValueTransformer_h */
