//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INMessageExport_Protocol_h
#define INMessageExport_Protocol_h
@import Foundation;

@protocol INMessageExport <NSObject, JSExport>

@property (copy, nonatomic) NSString *identifier;
@property (copy, nonatomic) NSString *conversationIdentifier;
@property (copy, nonatomic) NSString *content;
@property (copy, nonatomic) NSDate *dateSent;
@property (copy, nonatomic) INPerson *sender;
@property (copy, nonatomic) NSArray *recipients;
@property (copy, nonatomic) NSDate *dateMessageWasLastRead;
@property (copy, nonatomic) NSNumber *numberOfAttachments;
@property (nonatomic) long long messageType;
@property (nonatomic) long long messageEffectType;

/* instance methods */
- (id)init;
@end

#endif /* INMessageExport_Protocol_h */
