//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INParameterContexts_h
#define INParameterContexts_h
@import Foundation;

#include "INJSONSerializable-Protocol.h"

@class NSDictionary, NSString;

@interface INParameterContexts : NSObject<INJSONSerializable> {
  /* instance variables */
  NSDictionary *_suggestedValuesDictionary;
  NSDictionary *_typedSuggestedValuesDictionary;
  NSDictionary *_operatorsDictionary;
}

@property (retain, nonatomic) NSDictionary *_suggestedValuesDictionary;
@property (retain, nonatomic) NSDictionary *_typedSuggestedValuesDictionary;
@property (retain, nonatomic) NSDictionary *_operatorsDictionary;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)_intents_decodeWithJSONDecoder:(id)jsondecoder codableDescription:(id)description from:(id)from;

/* instance methods */
- (id)_initWithIntent:(id)intent decoder:(id)decoder JSONDictionary:(id)jsondictionary;
- (void)_updateOperatorsForIntent:(id)intent JSONDictionary:(id)jsondictionary;
- (void)_updateSuggestedValuesForIntent:(id)intent decoder:(id)decoder JSONDictionary:(id)jsondictionary;
- (BOOL)_isEmpty;
- (id)valueForUndefinedKey:(id)key;
- (id)_intents_encodeWithJSONEncoder:(id)jsonencoder codableDescription:(id)description;
- (void)_intents_decodeWithJSONDecoder:(id)jsondecoder codableDescription:(id)description from:(id)from;
- (void)_setSuggestedValuesDictionary:(id)dictionary;
- (void)_setTypedSuggestedValuesDictionary:(id)dictionary;
- (void)_setOperatorsDictionary:(id)dictionary;
@end

#endif /* INParameterContexts_h */
