//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INPriceRange_h
#define INPriceRange_h
@import Foundation;

#include "INPriceRangeExport-Protocol.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSDecimalNumber, NSString;

@interface INPriceRange : NSObject<INPriceRangeExport, NSCopying, NSSecureCoding>

@property (readonly, nonatomic) NSDecimalNumber *minimumPrice;
@property (readonly, nonatomic) NSDecimalNumber *maximumPrice;
@property (readonly, nonatomic) NSString *currencyCode;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)_priceWithPriceRangeValue:(id)value;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithRangeBetweenPrice:(id)price andPrice:(id)price currencyCode:(id)code;
- (id)initWithMaximumPrice:(id)price currencyCode:(id)code;
- (id)initWithMinimumPrice:(id)price currencyCode:(id)code;
- (id)initWithPrice:(id)price currencyCode:(id)code;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)_formattedStringWithLocale:(id)locale componentsFormatString:(id)string;
- (BOOL)isEqual:(id)equal;
- (id)descriptionAtIndent:(unsigned long long)indent;
- (id)_dictionaryRepresentation;
@end

#endif /* INPriceRange_h */
