//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INReportIncidentIntent_h
#define INReportIncidentIntent_h
@import Foundation;

#include "INIntent.h"
#include "INReportIncidentIntentExport-Protocol.h"
#include "INSupportedTrafficIncidentType.h"

@class CLPlacemark, NSNumber, NSString;

@interface INReportIncidentIntent : INIntent<INReportIncidentIntentExport>

@property (copy, nonatomic) NSString *incidentType;
@property (readonly, copy, nonatomic) INSupportedTrafficIncidentType *incidentType;
@property (readonly, copy, nonatomic) NSNumber *startTime;
@property (readonly, copy, nonatomic) NSNumber *isClear;
@property (readonly, copy, nonatomic) CLPlacemark *userLocation;
@property (readonly, copy, nonatomic) NSString *additionalDetails;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithIncidentType:(id)type startTime:(id)time additionalDetails:(id)details isClear:(id)clear;
- (id)_typedBackingStore;
- (id)_metadata;
- (void)_setMetadata:(id)metadata;
- (id)initWithIncidentType:(id)type startTime:(id)time isClear:(id)clear userLocation:(id)location additionalDetails:(id)details;
- (id)_dictionaryRepresentation;
- (void)_redactForMissingPrivacyEntitlementOptions:(unsigned long long)options containingAppBundleId:(id)id;
- (id)domain;
- (void)setDomain:(id)domain;
- (id)verb;
- (void)setVerb:(id)verb;
- (id)parametersByName;
- (void)setParametersByName:(id)name;
@end

#endif /* INReportIncidentIntent_h */
