//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INRequestRideIntentExport_Protocol_h
#define INRequestRideIntentExport_Protocol_h
@import Foundation;

@protocol INRequestRideIntentExport <NSObject, JSExport>

@property (copy, nonatomic) CLPlacemark *pickupLocation;
@property (copy, nonatomic) CLPlacemark *dropOffLocation;
@property (copy, nonatomic) INSpeakableString *rideOptionName;
@property (copy, nonatomic) NSNumber *partySize;
@property (copy, nonatomic) INPaymentMethod *paymentMethod;
@property (copy, nonatomic) INDateComponentsRange *scheduledPickupTime;

/* instance methods */
- (id)init;
@end

#endif /* INRequestRideIntentExport_Protocol_h */
