//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INTemperatureResolutionResultExport_Protocol_h
#define INTemperatureResolutionResultExport_Protocol_h
@import Foundation;

@protocol INTemperatureResolutionResultExport <NSObject, JSExport>
/* class methods */
+ (id)successWithResolvedTemperature:(id)temperature;
+ (id)disambiguationWithTemperaturesToDisambiguate:(id)disambiguate;
+ (id)confirmationRequiredWithTemperatureToConfirm:(id)confirm;
/* instance methods */
- (id)init;
@end

#endif /* INTemperatureResolutionResultExport_Protocol_h */
