//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INUserContextStore_h
#define INUserContextStore_h
@import Foundation;

@class CKKnowledgeStore;

@interface INUserContextStore : NSObject {
  /* instance variables */
  CKKnowledgeStore *_knowledgeStore;
}

/* class methods */
+ (id)sharedStore;
+ (id)findDataInValue:(id)value;
+ (id)keyPrefixForType:(long long)type;
+ (id)keyForBundleIdentifier:(id)identifier andType:(long long)type;

/* instance methods */
- (void)storeUserContext:(id)context forBundleIdentifier:(id)identifier;
- (void)removeUserContextOfClass:(Class)class forBundleIdentifier:(id)identifier;
- (void)storeUserContextViaHelper:(id)helper forBundleIdentifier:(id)identifier;
- (void)userContextOfClass:(Class)class forBundleIdentifiers:(id)identifiers withCompletion:(id /* block */)completion;
- (void)userContextOfClass:(Class)class withCompletion:(id /* block */)completion;
- (id)_init;
- (id)_initWithKnowledgeStore:(id)store;
@end

#endif /* INUserContextStore_h */
