//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2201.0.2.0.0
//
#ifndef INWorkoutAssociatedItem_h
#define INWorkoutAssociatedItem_h
@import Foundation;

#include "INJSONSerializable-Protocol.h"
#include "INSpeakableString.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSString;

@interface INWorkoutAssociatedItem : NSObject<INJSONSerializable, NSCopying, NSSecureCoding>

@property (readonly, nonatomic) long long itemLabel;
@property (readonly, copy, nonatomic) NSString *itemID;
@property (readonly, nonatomic) long long contentRating;
@property (readonly, copy, nonatomic) INSpeakableString *itemName;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (BOOL)supportsSecureCoding;
+ (id)_intents_decodeWithJSONDecoder:(id)jsondecoder codableDescription:(id)description from:(id)from;

/* instance methods */
- (id)initWithItemLabel:(long long)label itemID:(id)id contentRating:(long long)rating itemName:(id)name;
- (BOOL)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)_intents_encodeWithJSONEncoder:(id)jsonencoder codableDescription:(id)description;
- (id)descriptionAtIndent:(unsigned long long)indent;
- (id)_dictionaryRepresentation;
@end

#endif /* INWorkoutAssociatedItem_h */
