//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 146.60.7.1.1
//
#ifndef _TtC17_AppIntents_UIKit14AppUIKitBridge_h
#define _TtC17_AppIntents_UIKit14AppUIKitBridge_h
@import Foundation;

#include "_TtCs12_SwiftObject.h"

@interface _AppIntents_UIKit.AppUIKitBridge : Swift._SwiftObject { // (Swift)
  /* instance variables */
   host;
   lock;
   entityInteractionsTable;
   interactionIdToEntityIdentifierTable;
   intentInteractionsTable;
}

@end

#endif /* _TtC17_AppIntents_UIKit14AppUIKitBridge_h */
