//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 629.3.4.0.0
//
#ifndef AVAudioPCMBuffer_h
#define AVAudioPCMBuffer_h
@import Foundation;

#include "AVAudioBuffer.h"

@class NSArray;

@interface AVAudioPCMBuffer : AVAudioBuffer

@property (readonly, nonatomic) NSArray *peakPowerPerChannel;
@property (readonly, nonatomic) NSArray *averagePowerPerChannel;
@property (readonly, nonatomic) unsigned int frameCapacity;
@property (nonatomic) unsigned int frameLength;
@property (readonly, nonatomic) unsigned long long stride;
@property (readonly, nonatomic) float * * floatChannelData;
@property (readonly, nonatomic) short * * int16ChannelData;
@property (readonly, nonatomic) int * * int32ChannelData;

/* instance methods */
- (id)initWithPCMFormat:(id)pcmformat frameCapacity:(unsigned int)capacity;
- (id)initWithPCMFormat:(id)pcmformat bufferListNoCopy:(const struct AudioBufferList { unsigned int x0; struct AudioBuffer { unsigned int x10; unsigned int x1; void * x2; } x[1] } *)copy deallocator:(id /* block */)deallocator;
- (void)setByteLength:(unsigned int)length;
- (void)_initChannelPtrs;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (BOOL)appendDataFromBuffer:(id)buffer;
- (BOOL)appendDataFromBuffer:(id)buffer channel:(long long)channel;
- (id)splitIntoSingleChannelBuffers;
- (id)calculatePower:(unsigned long long)power;
- (float)calculatePower:(unsigned long long)power forFloatData:(float *)data stride:(long long)stride frameLength:(unsigned int)length;
@end

#endif /* AVAudioPCMBuffer_h */
