//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 629.3.4.0.0
//
#ifndef AVAudioPlayerNode_h
#define AVAudioPlayerNode_h
@import Foundation;

#include "AVAudioNode.h"
#include "AVAudioMixing-Protocol.h"

@class NSString;

@interface AVAudioPlayerNode : AVAudioNode<AVAudioMixing>

@property (readonly, nonatomic) BOOL playing;
@property (@dynamic, nonatomic) float volume;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)callLegacyCompletionHandlerForType:(long long)type legacyHandler:(id /* block */)handler;
- (void)scheduleBuffer:(id)buffer completionHandler:(id /* block */)handler;
- (void)scheduleBuffer:(id)buffer completionCallbackType:(long long)type completionHandler:(id /* block */)handler;
- (void)scheduleBuffer:(id)buffer atTime:(id)time options:(unsigned long long)options completionHandler:(id /* block */)handler;
- (void)scheduleBuffer:(id)buffer atTime:(id)time options:(unsigned long long)options completionCallbackType:(long long)type completionHandler:(id /* block */)handler;
- (void)scheduleFile:(id)file atTime:(id)time completionHandler:(id /* block */)handler;
- (void)scheduleFile:(id)file atTime:(id)time completionCallbackType:(long long)type completionHandler:(id /* block */)handler;
- (void)scheduleSegment:(id)segment startingFrame:(long long)frame frameCount:(unsigned int)count atTime:(id)time completionHandler:(id /* block */)handler;
- (void)scheduleSegment:(id)segment startingFrame:(long long)frame frameCount:(unsigned int)count atTime:(id)time completionCallbackType:(long long)type completionHandler:(id /* block */)handler;
- (void)prepareWithFrameCount:(unsigned int)count;
- (void)play;
- (void)playAtTime:(id)time;
- (void)pause;
- (void)stop;
- (id)nodeTimeForPlayerTime:(id)time;
- (id)playerTimeForNodeTime:(id)time;
- (BOOL)isPlaying;
- (void)didAttachToEngine:(id)engine;
@end

#endif /* AVAudioPlayerNode_h */
