//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 50.0.6.0.0
//
#ifndef SKOpenGLNode_h
#define SKOpenGLNode_h
@import Foundation;

#include "SKNode.h"

@interface SKOpenGLNode : SKNode

@property struct CGSize { double x0; double x1; } viewportSize;

/* class methods */
+ (id)openGLNodeWithViewportSize:(struct CGSize { double x0; double x1; })size;

/* instance methods */
- (id)init;
- (id)initWithViewportSize:(struct CGSize { double x0; double x1; })size;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (BOOL)needsRenderForTime:(double)time;
- (void)_renderForTime:(double)time;
- (void)renderForTime:(double)time;
@end

#endif /* SKOpenGLNode_h */
