//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 402.23.0.0.0
//
#ifndef _CHSWidgetMetricsCodable_h
#define _CHSWidgetMetricsCodable_h
@import Foundation;

#include "CHSWidgetMetrics.h"

@interface _CHSWidgetMetricsCodable : CHSWidgetMetrics // (Swift)
/* instance methods */
- (id)initWithCoder:(id)coder;
- (id)initWithSize:(struct CGSize { double x0; double x1; })size cornerRadius:(double)radius scaleFactor:(double)factor fontStyle:(long long)style margins:(id)margins supportsDynamicText:(unsigned long long)text;
@end

#endif /* _CHSWidgetMetricsCodable_h */
