//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 402.23.0.0.0
//
#ifndef NSBundle_WidgetKit_h
#define NSBundle_WidgetKit_h
@import Foundation;

@interface NSBundle (WidgetKit)
/* class methods */
+ (id)wk_uniqueWithURL:(id)url;
@end

#endif /* NSBundle_WidgetKit_h */
