//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 143.7.11.0.0
//
#ifndef _TtP10FinanceKit24OrderTrackingXPCProtocol__Protocol_h
#define _TtP10FinanceKit24OrderTrackingXPCProtocol__Protocol_h
@import Foundation;

@protocol FinanceKit.OrderTrackingXPCProtocol 
/* instance methods */
- (void)saveOrderWithSignedArchive:(id)archive completionHandler:(id /* block */)handler;
- (void)containsOrderWithOrderTypeIdentifier:(id)identifier orderIdentifier:(id)identifier updatedDate:(id)date completionHandler:(id /* block */)handler;
- (void)ordersWithFetchType:(id)type completionHandler:(id /* block */)handler;
- (void)isDataAvailableFor:(long long)for completion:(id /* block */)completion;
- (void)insertOrUpdateOrderSyncWithData:(id)data options:(id)options completion:(id /* block */)completion;
- (void)deleteOrderWithOrderTypeIdentifier:(id)identifier orderIdentifier:(id)identifier completionHandler:(id /* block */)handler;
- (void)containsOrderWithOrderTypeIdentifier:(id)identifier orderIdentifier:(id)identifier updatedDate:(id)date completion:(id /* block */)completion;
- (void)setOrderNotificationsEnabled:(BOOL)enabled orderTypeIdentifier:(id)identifier orderIdentifier:(id)identifier completionHandler:(id /* block */)handler;
- (void)setOrderMarkedAsCompleteWithOrderTypeIdentifier:(id)identifier orderIdentifier:(id)identifier newValue:(BOOL)value modificationDate:(id)date completionHandler:(id /* block */)handler;
- (void)updateOrdersShowAsActiveWithNow:(id)now completionHandler:(id /* block */)handler;
- (void)refreshOrderWithOrderTypeIdentifier:(id)identifier orderIdentifier:(id)identifier completionHandler:(id /* block */)handler;
- (void)activeOrdersWithCompletionHandler:(id /* block */)handler;
@end

#endif /* _TtP10FinanceKit24OrderTrackingXPCProtocol__Protocol_h */
