//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 143.7.11.0.0
//
#ifndef FKMapsBrand_h
#define FKMapsBrand_h
@import Foundation;

#include "FKMapsItem.h"
#include "NSCopying-Protocol.h"

@class NSURL;

@interface FKMapsBrand : FKMapsItem<NSCopying>

@property (copy, nonatomic) NSURL *logoURL;

/* instance methods */
- (id)initWithMUID:(unsigned long long)muid resultProviderIdentifier:(int)identifier name:(id)name phoneNumber:(id)number url:(id)url heroImageURL:(id)url heroImageAttributionName:(id)name category:(unsigned long long)category mapsCategoryIdentifier:(id)identifier encodedStylingInfo:(id)info businessChatURL:(id)url lastProcessedDate:(id)date logoURL:(id)url;
- (id)copyWithZone:(struct _NSZone *)zone;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)equal;
@end

#endif /* FKMapsBrand_h */
