//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3762.60.29.0.0
//
#ifndef _TtCV7Network10HTTPFieldsP33_F32FFD35E65B6CA87CB92CAA4C9475458_Storage_h
#define _TtCV7Network10HTTPFieldsP33_F32FFD35E65B6CA87CB92CAA4C9475458_Storage_h
@import Foundation;

#include "_TtCs12_SwiftObject.h"

@interface Network.HTTPFields.(_Storage in _F32FFD35E65B6CA87CB92CAA4C947545) : Swift._SwiftObject { // (Swift)
  /* instance variables */
   fields;
   index;
   lock;
}

@end

#endif /* _TtCV7Network10HTTPFieldsP33_F32FFD35E65B6CA87CB92CAA4C9475458_Storage_h */
