//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3762.60.29.0.0
//
#ifndef nw_listener_inbox_h
#define nw_listener_inbox_h
@import Foundation;

#include "OS_nw_endpoint-Protocol.h"
#include "OS_nw_interface-Protocol.h"
#include "OS_nw_parameters-Protocol.h"
#include "nw_listener_inbox_delegate-Protocol.h"

@class NSString;

@interface nw_listener_inbox : NSObject {
  /* instance variables */
  NSObject<nw_listener_inbox_delegate> *_delegate;
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
  NSString *_description;
  NSObject<OS_nw_parameters> *_parameters;
  int _level;
  unsigned int x :1 _suspended;
}

@property (readonly, nonatomic) NSObject<OS_nw_endpoint> *local_endpoint;
@property (readonly, nonatomic) NSObject<OS_nw_interface> *interface;
@property (nonatomic) BOOL multicast;

/* instance methods */
- (id)start;
- (id)initWithDelegate:(id)delegate;
- (BOOL)suspend;
- (BOOL)isSuspended;
- (BOOL)resume;
- (BOOL)cancel;
@end

#endif /* nw_listener_inbox_h */
