//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3762.60.29.0.0
//
#ifndef NWBonjourBrowseDescriptor_h
#define NWBonjourBrowseDescriptor_h
@import Foundation;

#include "NWBrowseDescriptor.h"

@class NSString;

@interface NWBonjourBrowseDescriptor : NWBrowseDescriptor

@property (readonly, nonatomic) NSString *type;
@property (readonly, nonatomic) NSString *domain;

/* class methods */
+ (unsigned int)descriptorType;
+ (id)descriptorWithType:(id)type domain:(id)domain;

/* instance methods */
- (id)descriptionWithIndent:(int)indent showFullContent:(BOOL)content;
@end

#endif /* NWBonjourBrowseDescriptor_h */
