//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3762.60.29.0.0
//
#ifndef NWConcrete_nw_endpoint_transform_h
#define NWConcrete_nw_endpoint_transform_h
@import Foundation;

#include "NWConcrete_nw_endpoint_handler.h"
#include "OS_nw_endpoint-Protocol.h"
#include "OS_nw_endpoint_transform-Protocol.h"

@class NSString;
@protocol OS_nw_array, OS_xpc_object;

@interface NWConcrete_nw_endpoint_transform : NSObject<OS_nw_endpoint_transform> {
  /* instance variables */
  NSObject<OS_nw_array> *child_endpoint_handlers;
  NSObject<OS_nw_array> *failed_child_endpoint_handlers;
  NSObject<OS_xpc_object> *fallback_modes;
  NSObject<OS_nw_array> *blocked_protocols;
  unsigned int next_child_endpoint_index;
  NWConcrete_nw_endpoint_handler *connected_child;
  NSObject<OS_nw_endpoint> *primary_endpoint;
  void * child_timer;
  unsigned long long last_timeout_ms;
  unsigned int first_protocol;
  unsigned int connected_protocol;
  unsigned int connected_protocol_index;
  BOOL quic_deferred;
  BOOL quic_application_deferred;
  BOOL quic_denied;
  BOOL quic_alternative_present;
  BOOL quic_updated_alternative;
  BOOL quic_speculative_attempt;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)dealloc;
- (void)startWithHandler:(id)handler;
- (void)cancelWithHandler:(id)handler forced:(BOOL)forced;
- (void)updatePathWithHandler:(id)handler;
- (BOOL)applyWithHandler:(id)handler toChildren:(id /* block */)children;
@end

#endif /* NWConcrete_nw_endpoint_transform_h */
