//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3762.60.29.0.0
//
#ifndef NWConcrete_nw_nat64_prefixes_resolver_h
#define NWConcrete_nw_nat64_prefixes_resolver_h
@import Foundation;

#include "NWConcrete_nw_nat64_prefixes_resolver.h"
#include "OS_nw_context-Protocol.h"
#include "OS_nw_nat64_prefixes_resolver-Protocol.h"
#include "OS_nw_parameters-Protocol.h"
#include "OS_nw_path_evaluator-Protocol.h"

@class NSString;
@protocol OS_dispatch_queue;

@interface NWConcrete_nw_nat64_prefixes_resolver : NSObject<OS_nw_nat64_prefixes_resolver> {
  /* instance variables */
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } lock;
  unsigned int ifindex;
  NSObject<OS_nw_parameters> *parameters;
  NSObject<OS_nw_context> *context;
  NWConcrete_nw_nat64_prefixes_resolver *internally_retained_object;
  unsigned int dns_service_id;
  struct _DNSServiceRef_t * dns_service;
  int dns_error;
  id /* block */ update_handler;
  id /* block */ cancel_handler;
  NSObject<OS_dispatch_queue> *client_queue;
  struct in6_addr { union { unsigned char x0[16] unsigned short x1[8] unsigned int x2[4] } x0; } * ipv6_addrs;
  NSObject<OS_nw_path_evaluator> *evaluator;
  int address_count;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
@end

#endif /* NWConcrete_nw_nat64_prefixes_resolver_h */
