//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3762.60.29.0.0
//
#ifndef NWConcrete_nw_socks5_connection_h
#define NWConcrete_nw_socks5_connection_h
@import Foundation;

#include "NWConcrete_nw_connection.h"
#include "NWConcrete_nw_socks5_connection.h"
#include "OS_nw_error-Protocol.h"
#include "OS_nw_establishment_report-Protocol.h"
#include "OS_nw_path_evaluator-Protocol.h"
#include "OS_nw_socks5_connection-Protocol.h"
#include "OS_nw_socks5_server-Protocol.h"

@class NSString;
@protocol OS_dispatch_queue;

@interface NWConcrete_nw_socks5_connection : NSObject<OS_nw_socks5_connection> {
  /* instance variables */
  unsigned long long sc_id;
  NWConcrete_nw_socks5_connection *sc_internally_retained_object;
  NSObject<OS_nw_socks5_server> *sc_parent;
  NWConcrete_nw_connection *sc_in_connection;
  NSObject<OS_dispatch_queue> *sc_queue;
  id /* block */ sc_cancel;
  unsigned char sc_state;
  unsigned char sc_out_address_type;
  NSObject<OS_nw_path_evaluator> *sc_prefer_wifi_path_evaluator;
  int sc_prefer_wifi_previous_path_status;
  void * sc_udp_associate_verification_source;
  unsigned int sc_udp_associate_verification_count;
  union { char *byte_pointer; struct in_addr *ipv4_addr; struct in6_addr *ipv6_addr; char *domain; } sc_out_address;
  unsigned short sc_shoes_request_length_hbo;
  unsigned char sc_out_address_domain_length;
  unsigned long long sc_busy_counter;
  unsigned long long sc_busy_start_time_nanos;
  unsigned long long sc_total_busy_time_nanos;
  unsigned long long sc_start_time_nanos;
  NWConcrete_nw_connection *sc_out_connection;
  NSObject<OS_nw_error> *sc_error;
  unsigned int x :1 sc_out_connection_failed_or_sent_write_close;
  unsigned int x :1 sc_in_connection_failed_or_sent_write_close;
  unsigned int x :1 sc_out_disable_proxy;
  unsigned int x :1 sc_sent_reply;
  unsigned int x :1 sc_has_read_from_in_connection;
  unsigned int x :1 sc_out_udp;
  unsigned int x :1 sc_should_prefer_wifi;
  unsigned int x :1 sc_is_udp_associate;
  unsigned int x :1 sc_processed_udp_associate_request;
  unsigned int x :1 sc_in_connection_send_connected_endpoint;
  unsigned int x :1 sc_in_connection_send_resolved_endpoint;
  NWConcrete_nw_connection *sc_in_udp_associated_tcp_connection;
  NSObject<OS_nw_establishment_report> *sc_out_establishment_report;
  unsigned long long sc_out_connection_bytes_read;
  unsigned long long sc_out_connection_bytes_written;
  unsigned long long sc_in_connection_bytes_read;
  unsigned long long sc_in_connection_bytes_written;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
@end

#endif /* NWConcrete_nw_socks5_connection_h */
