//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3762.60.29.0.0
//
#ifndef NWPBEndpoint_h
#define NWPBEndpoint_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NWPBAddressEndpoint.h"
#include "NWPBHostEndpoint.h"
#include "NWPBInterface.h"
#include "NWPBServiceEndpoint.h"

@class NSData;

@interface NWPBEndpoint : PBCodable<NSCopying>

@property (readonly, nonatomic) BOOL hasAddress;
@property (retain, nonatomic) NWPBAddressEndpoint *address;
@property (readonly, nonatomic) BOOL hasHost;
@property (retain, nonatomic) NWPBHostEndpoint *host;
@property (readonly, nonatomic) BOOL hasService;
@property (retain, nonatomic) NWPBServiceEndpoint *service;
@property (readonly, nonatomic) BOOL hasInterface;
@property (retain, nonatomic) NWPBInterface *interface;
@property (readonly, nonatomic) BOOL hasTxtRecord;
@property (retain, nonatomic) NSData *txtRecord;

/* instance methods */
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)copyTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
@end

#endif /* NWPBEndpoint_h */
