//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3762.60.29.0.0
//
#ifndef NWPBOpenConnection_h
#define NWPBOpenConnection_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "NWPBEndpoint.h"
#include "NWPBParameters.h"

@class NSString;

@interface NWPBOpenConnection : PBCodable<NSCopying>

@property (readonly, nonatomic) BOOL hasEndpoint;
@property (retain, nonatomic) NWPBEndpoint *endpoint;
@property (readonly, nonatomic) BOOL hasParameters;
@property (retain, nonatomic) NWPBParameters *parameters;
@property (readonly, nonatomic) BOOL hasClientUUID;
@property (retain, nonatomic) NSString *clientUUID;

/* instance methods */
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)copyTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
@end

#endif /* NWPBOpenConnection_h */
