//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3762.60.29.0.0
//
#ifndef NWTCPListenerDelegate_Protocol_h
#define NWTCPListenerDelegate_Protocol_h
@import Foundation;

@protocol NWTCPListenerDelegate <NSObject>
/* instance methods */
- (void)handleConnection:(id)connection;
@end

#endif /* NWTCPListenerDelegate_Protocol_h */
