//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3762.60.29.0.0
//
#ifndef NWURLSessionMultipartParser_h
#define NWURLSessionMultipartParser_h
@import Foundation;

#include "NWURLSessionMultipartBoundaryRecognizer.h"
#include "NWURLSessionMultipartHeaderRecognizer.h"
#include "NWURLSessionMultipartPartBoundarySuffixRecognizer.h"
#include "NWURLSessionResponseConsumer-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString;
@protocol OS_dispatch_data, OS_dispatch_queue;

@interface NWURLSessionMultipartParser : NSObject {
  /* instance variables */
  BOOL _isFirstBoundary;
  BOOL _didDeliverComplete;
  int _parserState;
  int _dispositionState;
  NSString *_boundary;
  NSObject<NWURLSessionResponseConsumer> *_responseConsumer;
  NSObject<OS_dispatch_data> *_data;
  NSMutableArray *_parts;
  NWURLSessionMultipartBoundaryRecognizer *_boundaryRecognizer;
  NWURLSessionMultipartHeaderRecognizer *_headerRecognizer;
  NWURLSessionMultipartPartBoundarySuffixRecognizer *_boundarySuffixRecognizer;
  NSMutableDictionary *_headers;
  NSObject<OS_dispatch_queue> *_queue;
  unsigned long long _boundaryPatternSize;
}

/* instance methods */
@end

#endif /* NWURLSessionMultipartParser_h */
