//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2890.4.12.2.3
//
#ifndef CMOdometerSuitabilityManager_h
#define CMOdometerSuitabilityManager_h
@import Foundation;

#include "CMOdometerSuitabilityManagerProxy.h"

@interface CMOdometerSuitabilityManager : NSObject

@property (readonly, nonatomic) CMOdometerSuitabilityManagerProxy *odometerSuitabilityManagerProxy;

/* instance methods */
- (id)init;
- (void)dealloc;
- (void)startOdometerSuitabilityUpdatesWithHandler:(id /* block */)handler;
- (void)stopOdometerSuitabilityUpdates;
@end

#endif /* CMOdometerSuitabilityManager_h */
