//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2890.4.12.2.3
//
#ifndef CMPedometerEvent_h
#define CMPedometerEvent_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSDate;

@interface CMPedometerEvent : NSObject<NSSecureCoding, NSCopying> {
  /* instance variables */
  NSDate *fDate;
  long long fType;
}

@property (readonly, nonatomic) NSDate *date;
@property (readonly, nonatomic) long long type;

/* class methods */
+ (BOOL)supportsSecureCoding;
+ (id)eventStringFromType:(long long)type;

/* instance methods */
- (id)initWithEventDate:(id)date type:(long long)type;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)description;
@end

#endif /* CMPedometerEvent_h */
