//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2890.4.12.2.3
//
#ifndef CMSedentaryTimer_Internal_h
#define CMSedentaryTimer_Internal_h
@import Foundation;

@protocol OS_dispatch_queue;

@interface CMSedentaryTimer_Internal : NSObject {
  /* instance variables */
  NSObject<OS_dispatch_queue> *fClientQueue;
  NSObject<OS_dispatch_queue> *fDaemonQueue;
  void * fLocationdConnection;
}

@property (nonatomic) BOOL timerArmed;

/* instance methods */
- (id)init;
- (void)dealloc;
- (void)_teardown;
- (BOOL)_isActive;
- (void)_handleStartStopTimerResponse:(struct shared_ptr<CLConnectionMessage> { struct CLConnectionMessage * x0; struct __shared_weak_count * x1; })response withHandler:(id /* block */)handler;
- (void)_handleAlarmDataResponse:(struct shared_ptr<CLConnectionMessage> { struct CLConnectionMessage * x0; struct __shared_weak_count * x1; })response withHandler:(id /* block */)handler;
- (void)_registerForAlarmsWithHandler:(id /* block */)handler;
- (BOOL)isTimerArmed;
@end

#endif /* CMSedentaryTimer_Internal_h */
