//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2890.4.12.2.3
//
#ifndef CMSedentaryTimer_h
#define CMSedentaryTimer_h
@import Foundation;

#include "CMSedentaryTimer_Internal.h"

@interface CMSedentaryTimer : NSObject {
  /* instance variables */
  CMSedentaryTimer_Internal *_internal;
}

@property (readonly, nonatomic) CMSedentaryTimer_Internal *_internal;

/* class methods */
+ (BOOL)isAvailable;

/* instance methods */
- (id)init;
- (void)dealloc;
- (BOOL)isActive;
- (void)startTimerWithStartTime:(id)time periodInterval:(double)interval reminderInterval:(double)interval autoReschedule:(BOOL)reschedule handler:(id /* block */)handler;
- (void)stopTimerWithHandler:(id /* block */)handler;
- (void)queryAlarmDataSince:(id)since withHandler:(id /* block */)handler;
- (void)registerForAlarmsWithHandler:(id /* block */)handler;
@end

#endif /* CMSedentaryTimer_h */
