//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 162.13.0.0.0
//
#ifndef _TtC13SoundAnalysis15XPCProxyXPCHost_h
#define _TtC13SoundAnalysis15XPCProxyXPCHost_h
@import Foundation;

#include "_TtP13SoundAnalysis19XPCProxyXPCProtocol_-Protocol.h"

@interface SoundAnalysis.XPCProxyXPCHost : NSObject<SoundAnalysis.XPCProxyXPCProtocol> { // (Swift)
  /* instance variables */
   hosted;
}

/* instance methods */
- (void)xpcSendMessageWithData:(id)data proxy:(id)proxy completionHandler:(id /* block */)handler;
- (id)init;
@end

#endif /* _TtC13SoundAnalysis15XPCProxyXPCHost_h */
