//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 162.13.0.0.0
//
#ifndef SNAnalysisClient_h
#define SNAnalysisClient_h
@import Foundation;

@interface SNAnalysisClient : NSObject { // (Swift)
  /* instance variables */
   connectionToServerGenerator;
   xpcConnectionToServer;
   queue;
   pendingInvalidationHandlers;
}

/* class methods */
+ (id)defaultClient;

/* instance methods */
- (id)init;
- (id)initWithConnectionGenerator:(id /* block */)generator queue:(id)queue;
- (id)initToConnectToMachServiceWithName:(id)name queue:(id)queue;
- (id)createRemoteSystemAudioAnalyzerWithInvalidationHandler:(id /* block */)handler queue:(id)queue error:(id *)error;
@end

#endif /* SNAnalysisClient_h */
