//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 162.13.0.0.0
//
#ifndef SNResultsForwarder_h
#define SNResultsForwarder_h
@import Foundation;

#include "SNResultsObserving-Protocol.h"

@interface SNResultsForwarder : NSObject<SNResultsObserving> { // (Swift)
  /* instance variables */
   completionHandler;
   resultsHandler;
}

/* instance methods */
- (id)init;
- (id)initWithCompletionHandler:(id /* block */)handler resultsHandler:(id /* block */)handler;
- (void)request:(id)request didProduceResult:(id)result;
- (void)request:(id)request didFailWithError:(id)error;
- (void)requestDidComplete:(id)complete;
@end

#endif /* SNResultsForwarder_h */
