//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 162.13.0.0.0
//
#ifndef SNSystemAudioAnalyzerProtocol_Protocol_h
#define SNSystemAudioAnalyzerProtocol_Protocol_h
@import Foundation;

@protocol SNSystemAudioAnalyzerProtocol 
/* instance methods */
- (void)setAudioConfiguration:(id)configuration;
- (BOOL)addRequest:(id)request withObserver:(id)observer error:(id *)error;
- (void)removeRequest:(id)request;
- (void)removeAllRequests;
@end

#endif /* SNSystemAudioAnalyzerProtocol_Protocol_h */
