//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 12563.0.0.0.0
//
#ifndef ABSSource_h
#define ABSSource_h
@import Foundation;

#include "ABSAddressBook.h"
#include "ABSRecord-Protocol.h"
#include "ABSSource.h"

@class CNAccount, CNMutableContainer, NSString;

@interface ABSSource : NSObject<ABSRecord>

@property (nonatomic) int revertedRecordID;
@property (readonly, nonatomic) int id;
@property (readonly, nonatomic) unsigned int type;
@property (weak, nonatomic) ABSAddressBook *addressBook;
@property (weak, nonatomic) ABSSource *source;
@property (readonly, nonatomic) NSString *compositeName;
@property (readonly, nonatomic) CNAccount *account;
@property (retain, nonatomic) CNMutableContainer *cnImpl;
@property (readonly, nonatomic) NSString *CNIdentifierString;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;

/* instance methods */
- (unsigned long long)_cfTypeID;
- (id)initWithMutableContainer:(id)container;
- (id)getAccount;
- (void *)copyValueForProperty:(int)property;
- (BOOL)setValue:(void *)value forProperty:(int)property withError:(struct __CFError * *)error;
- (BOOL)removeProperty:(int)property withError:(id *)error;
- (void)updateAllValuesWithValuesFromContainer:(id)container;
- (void)replaceRecordStorageWithCNObject:(id)cnobject;
@end

#endif /* ABSSource_h */
