//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 12563.0.0.0.0
//
#ifndef CNContactTypeDescription_ABSExtentions_h
#define CNContactTypeDescription_ABSExtentions_h
@import Foundation;

@interface CNContactTypeDescription (ABSExtentions)
/* instance methods */
- (BOOL)absPropertyID:(int *)id;
- (unsigned int)absPropertyType;
- (void *)ABSValueFromCNValue:(id)cnvalue;
- (id)CNValueFromABSValue:(void *)absvalue;
@end

#endif /* CNContactTypeDescription_ABSExtentions_h */
