//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 12563.0.0.0.0
//
#ifndef CNMultiValuePropertyDescription_ABSExtentions_h
#define CNMultiValuePropertyDescription_ABSExtentions_h
@import Foundation;

@interface CNMultiValuePropertyDescription (ABSExtentions)
/* instance methods */
- (void *)ABSValueFromCNValue:(id)cnvalue;
- (id)CNValueFromABSValue:(void *)absvalue;
- (id /* block */)CNLabeledValueFromABSMultiValueTranform;
- (id /* block */)ABSMultiValueLabeledValueFromCNLabeledValueTransform;
- (id /* block */)multiValueTransformWithLabelMapping:(id)mapping valueTransform:(id /* block */)transform;
- (id /* block */)dictionaryBasedMultiValueTransformWithLabelMapping:(id)mapping inputKeys:(id)keys destinationClass:(Class)class valueMapping:(id)mapping;
- (id /* block */)passThroughMultivalueTransformWithLabelMapping:(id)mapping;
- (BOOL)isABSLabeledValueValue:(id)value equalToValue:(id)value;
@end

#endif /* CNMultiValuePropertyDescription_ABSExtentions_h */
