//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef CLRegion_HomeLocation_h
#define CLRegion_HomeLocation_h
@import Foundation;

@interface CLRegion (HomeLocation)
/* instance methods */
- (id)hm_description;
@end

#endif /* CLRegion_HomeLocation_h */
