//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMAccessoryInfoAccount_h
#define HMAccessoryInfoAccount_h
@import Foundation;

@class NSString;

@interface HMAccessoryInfoAccount : NSObject

@property (readonly, copy) NSString *username;
@property (readonly, copy) NSString *aaAltDSID;
@property (readonly, copy) NSString *amsAltDSID;
@property (readonly) BOOL signedIn;

/* instance methods */
- (id)initWithUsername:(id)username aaAltDSID:(id)dsid amsAltDSID:(id)dsid signedIn:(BOOL)in;
- (id)description;
- (id)protoPayload;
- (id)protoData;
- (id)initWithProtoPayload:(id)payload;
- (id)initWithProtoData:(id)data;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
@end

#endif /* HMAccessoryInfoAccount_h */
