//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMBulletinObjectTuple_h
#define HMBulletinObjectTuple_h
@import Foundation;

@class NSString;

@interface HMBulletinObjectTuple : NSObject

@property (readonly, nonatomic) NSString *queryName;
@property (readonly, nonatomic) NSString *uuidString;

/* class methods */
+ (id)tupleWithQueryType:(long long)type uuidString:(id)string;

/* instance methods */
- (id)initWithQueryType:(long long)type uuidString:(id)string;
@end

#endif /* HMBulletinObjectTuple_h */
