//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMCameraSettingsControl_h
#define HMCameraSettingsControl_h
@import Foundation;

#include "HMCameraControl.h"
#include "HMCharacteristic.h"
#include "_HMCameraSettingsControl.h"

@interface HMCameraSettingsControl : HMCameraControl

@property (retain, nonatomic) _HMCameraSettingsControl *settingsControl;
@property (readonly, nonatomic) HMCharacteristic *nightVision;
@property (readonly, nonatomic) HMCharacteristic *currentHorizontalTilt;
@property (readonly, nonatomic) HMCharacteristic *targetHorizontalTilt;
@property (readonly, nonatomic) HMCharacteristic *currentVerticalTilt;
@property (readonly, nonatomic) HMCharacteristic *targetVerticalTilt;
@property (readonly, nonatomic) HMCharacteristic *opticalZoom;
@property (readonly, nonatomic) HMCharacteristic *digitalZoom;
@property (readonly, nonatomic) HMCharacteristic *imageRotation;
@property (readonly, nonatomic) HMCharacteristic *imageMirroring;

/* instance methods */
- (id)initWithSettingsControl:(id)control;
@end

#endif /* HMCameraSettingsControl_h */
