//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMLanguageValueListSetting_h
#define HMLanguageValueListSetting_h
@import Foundation;

#include "HMImmutableSetting.h"

@class NSArray;

@interface HMLanguageValueListSetting : HMImmutableSetting

@property (readonly, copy) NSArray *languageValues;

/* instance methods */
- (id)initWithKeyPath:(id)path readOnly:(BOOL)only languageValues:(id)values;
- (id)initWithProtoPayload:(id)payload;
- (id)protoPayload;
- (id)payloadCopy;
- (id)initWithKeyPath:(id)path readOnly:(BOOL)only payload:(id)payload;
- (id)attributeDescriptions;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)equal;
@end

#endif /* HMLanguageValueListSetting_h */
