//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMLightProfile_h
#define HMLightProfile_h
@import Foundation;

#include "HMAccessoryProfile.h"
#include "HMFLogging-Protocol.h"
#include "HMLightProfileSettings.h"

@class NSString;
@protocol HMLightProfileDelegate;

@interface HMLightProfile : HMAccessoryProfile<HMFLogging>

@property (readonly) NSString *logIdentifier;
@property (readonly) _HMLightProfile *lightProfile;
@property (weak) NSObject<HMLightProfileDelegate> *delegate;
@property (readonly) HMLightProfileSettings *settings;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)logCategory;

/* instance methods */
- (id)initWithLightProfile:(id)profile;
- (BOOL)mergeFromNewObject:(id)object;
- (void)updateSettings:(id)settings withReason:(id)reason;
- (void)setNaturalLightingEnabled:(BOOL)enabled completionHandler:(id /* block */)handler;
- (void)setNaturalLightingEnabled:(BOOL)enabled shouldRetryOnFailure:(BOOL)failure completion:(id /* block */)completion;
- (void)fetchNaturalLightColorTemperatureForBrightness:(long long)brightness completion:(id /* block */)completion;
- (void)fetchSettingsWithCompletion:(id /* block */)completion;
@end

#endif /* HMLightProfile_h */
