//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMLocationEvent_h
#define HMLocationEvent_h
@import Foundation;

#include "HMEvent.h"
#include "NSCopying-Protocol.h"
#include "NSMutableCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class CLRegion, HMFLocationAuthorization;

@interface HMLocationEvent : HMEvent<NSSecureCoding, NSCopying, NSMutableCopying>

@property (readonly) HMFLocationAuthorization *authorization;
@property (nonatomic) long long locationAuthorization;
@property (retain, nonatomic) CLRegion *region;

/* class methods */
+ (id)createWithDictionary:(id)dictionary home:(id)home;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithDict:(id)dict region:(id)region;
- (id)initWithRegion:(id)region;
- (void)_unconfigure;
- (void)__configureWithContext:(id)context eventTrigger:(id)trigger;
- (void)updateRegion:(id)region completionHandler:(id /* block */)handler;
- (void)_retrieveLocationEvent;
- (id)_serializeForAdd;
- (void)_updateFromDictionary:(id)dictionary;
- (void)__locationAuthorizationUpdated:(id)updated;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (BOOL)mergeFromNewObject:(id)object;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
@end

#endif /* HMLocationEvent_h */
