//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMMediaGroupProtoMediaDestinationAggregateData_h
#define HMMediaGroupProtoMediaDestinationAggregateData_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"

@class NSMutableArray;

@interface HMMediaGroupProtoMediaDestinationAggregateData : PBCodable<NSCopying>

@property (retain, nonatomic) NSMutableArray *destinations;
@property (retain, nonatomic) NSMutableArray *destinationControllerDatas;
@property (retain, nonatomic) NSMutableArray *groups;

/* class methods */
+ (Class)destinationType;
+ (Class)destinationControllerDataType;
+ (Class)groupType;

/* instance methods */
- (void)clearDestinations;
- (void)addDestination:(id)destination;
- (unsigned long long)destinationsCount;
- (id)destinationAtIndex:(unsigned long long)index;
- (void)clearDestinationControllerDatas;
- (void)addDestinationControllerData:(id)data;
- (unsigned long long)destinationControllerDatasCount;
- (id)destinationControllerDataAtIndex:(unsigned long long)index;
- (void)clearGroups;
- (void)addGroup:(id)group;
- (unsigned long long)groupsCount;
- (id)groupAtIndex:(unsigned long long)index;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)copyTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
@end

#endif /* HMMediaGroupProtoMediaDestinationAggregateData_h */
