//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMMutableMediaDestination_h
#define HMMutableMediaDestination_h
@import Foundation;

#include "HMMediaDestination.h"

@class NSUUID;

@interface HMMutableMediaDestination : HMMediaDestination

@property (@dynamic) unsigned long long supportedOptions;
@property (copy, @dynamic) NSUUID *audioGroupIdentifier;

/* class methods */
+ (id)logCategory;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* HMMutableMediaDestination_h */
