//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMParsedMediaGroupSettingEventTopic_Protocol_h
#define HMParsedMediaGroupSettingEventTopic_Protocol_h
@import Foundation;

@protocol HMParsedMediaGroupSettingEventTopic 

@property (readonly, nonatomic) NSUUID *homeUUID;
@property (readonly, nonatomic) NSUUID *mediaGroupUUID;
@property (readonly, copy, nonatomic) NSString *mediaGroupSettingKeyPath;
@property (readonly, nonatomic) unsigned long long accessoryEventTopicSuffixID;

@end

#endif /* HMParsedMediaGroupSettingEventTopic_Protocol_h */
