//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMSignificantTimeEvent_h
#define HMSignificantTimeEvent_h
@import Foundation;

#include "HMTimeEvent.h"
#include "NSCopying-Protocol.h"
#include "NSMutableCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSDateComponents, NSString;

@interface HMSignificantTimeEvent : HMTimeEvent<NSSecureCoding, NSCopying, NSMutableCopying>

@property (retain, nonatomic) NSString *significantEvent;
@property (retain, nonatomic) NSDateComponents *offset;

/* class methods */
+ (id)createWithDictionary:(id)dictionary home:(id)home;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithSignificantEvent:(id)event offset:(id)offset;
- (id)initWithDict:(id)dict significantEvent:(id)event offset:(id)offset;
- (id)_serializeForAdd;
- (void)_updateFromDictionary:(id)dictionary;
- (void)updateSignificantEvent:(id)event completionHandler:(id /* block */)handler;
- (void)updateOffset:(id)offset completionHandler:(id /* block */)handler;
- (BOOL)mergeFromNewObject:(id)object;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
@end

#endif /* HMSignificantTimeEvent_h */
