//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 266.1.0.0.0
//
#ifndef MDLVertexDescriptor_h
#define MDLVertexDescriptor_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSMutableArray;

@interface MDLVertexDescriptor : NSObject<NSCopying>

@property (retain, nonatomic) NSMutableArray *attributes;
@property (retain, nonatomic) NSMutableArray *layouts;

/* class methods */
+ (id)_decodeVertexDescriptorAttributesWithCoder:(id)coder;
+ (id)_decodeVertexDescriptorLayoutsWithCoder:(id)coder;
+ (id)decodeVertexDescriptorWithCoder:(id)coder;

/* instance methods */
- (id)init;
- (id)initWithVertexDescriptor:(id)descriptor;
- (id)attributeNamed:(id)named;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)addOrReplaceAttribute:(id)attribute;
- (void)removeAttributeNamed:(id)named;
- (void)reset;
- (void)setPackedStrides;
- (void)setPackedOffsets;
- (void)debugPrintToFile:(struct __sFILE { char * x0; int x1; int x2; short x3; short x4; struct __sbuf { char * x0; int x1; } x5; int x6; void * x7; undefined * x8; undefined * x9; undefined * x10; undefined * x11; struct __sbuf { char * x0; int x1; } x12; struct __sFILEX * x13; int x14; unsigned char x15[3] unsigned char x16[1] struct __sbuf { char * x0; int x1; } x17; int x18; long long x19; } *)file;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)description;
- (void)_encodeVertexDescriptorLayoutsWithCoder:(id)coder;
- (void)_encodeVertexDescriptorAttributesWithCoder:(id)coder;
- (void)encodeVertexDescriptorWithCoder:(id)coder;
@end

#endif /* MDLVertexDescriptor_h */
