//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 813.2.8.0.0
//
#ifndef ProductPageLookupService_Protocol_h
#define ProductPageLookupService_Protocol_h
@import Foundation;

@protocol ProductPageLookupService 
/* instance methods */
- (void)lookupProductWithParametersProductRequest:(id)request reply:(id /* block */)reply;
- (void)lookupProductWithURLProductRequest:(id)request reply:(id /* block */)reply;
@end

#endif /* ProductPageLookupService_Protocol_h */
