//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 146.60.7.1.1
//
#ifndef _TtC19_AppIntents_SwiftUIP33_97ACBAA1CA7D953A93338B906A5780EF24AppViewArchivingDelegate_h
#define _TtC19_AppIntents_SwiftUIP33_97ACBAA1CA7D953A93338B906A5780EF24AppViewArchivingDelegate_h
@import Foundation;

#include "_TtCs12_SwiftObject.h"

@interface _AppIntents_SwiftUI.(AppViewArchivingDelegate in _97ACBAA1CA7D953A93338B906A5780EF) : Swift._SwiftObject { // (Swift)
  /* instance variables */
   allowedImageTypes;
   defaultImageType;
}

@end

#endif /* _TtC19_AppIntents_SwiftUIP33_97ACBAA1CA7D953A93338B906A5780EF24AppViewArchivingDelegate_h */
