//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1299.2.3.1.0
//
#ifndef _LSApplicationProxyForIdentifierQuery_h
#define _LSApplicationProxyForIdentifierQuery_h
@import Foundation;

#include "_LSBundleQuery.h"

@class NSString;

@interface _LSApplicationProxyForIdentifierQuery : _LSBundleQuery

@property (readonly, copy, nonatomic) NSString *identifier;

/* class methods */
+ (id)queryWithIdentifier:(id)identifier;
+ (id)alwaysAllowedBundleIdentifiers;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (void)_enumerateWithXPCConnection:(id)xpcconnection block:(id /* block */)block;
- (BOOL)_requiresDatabaseMappingEntitlement;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
@end

#endif /* _LSApplicationProxyForIdentifierQuery_h */
