//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1299.2.3.1.0
//
#ifndef _LSDModificationPendingSaveToken_h
#define _LSDModificationPendingSaveToken_h
@import Foundation;

#include "_LSPendingSaveToken-Protocol.h"

@class NSMutableArray, NSString, NSUUID;
@protocol {optional<NSError *>=""(?="__null_state_"c"__val_"@"NSError")"__engaged_"B};

@interface _LSDModificationPendingSaveToken : NSObject<_LSPendingSaveToken> {
  /* instance variables */
  NSMutableArray *_waiters;
  NSUUID *_uuid;
  struct optional<NSError *> { union { char __null_state_; NSError *__val_; } x0; BOOL __engaged_; } _saveError;
  struct unfair_lock_mutex { unsigned int _os_unfair_lock_opaque; } _mutex;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUUID:(id)uuid;
- (void)waitForResult:(id /* block */)result;
- (void)saveDidHappen:(BOOL)happen error:(id)error;
@end

#endif /* _LSDModificationPendingSaveToken_h */
