//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1299.2.3.1.0
//
#ifndef _LSDispatchWithTimeoutResult_h
#define _LSDispatchWithTimeoutResult_h
@import Foundation;

@class NSError;

@interface _LSDispatchWithTimeoutResult : NSObject

@property (retain) id result;
@property (retain) NSError *error;

/* instance methods */
@end

#endif /* _LSDispatchWithTimeoutResult_h */
