//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1088.10.0.0.0
//
#ifndef _AVBacklightAssertion_h
#define _AVBacklightAssertion_h
@import Foundation;

#include "AVTimer.h"

@class CSLSBacklightAssertion;

@interface _AVBacklightAssertion : NSObject {
  /* instance variables */
  CSLSBacklightAssertion *_backlightAssertion;
  AVTimer *_timer;
}

/* class methods */
+ (id)sharedInstance;
+ (void)takeAssertion;
+ (void)releaseAssertion;

/* instance methods */
- (void)dealloc;
- (void)_takeAssertion;
- (void)_releaseAssertion;
@end

#endif /* _AVBacklightAssertion_h */
