//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 11207.0.0.0.0
//
#ifndef CTCellularPlanTransferCrossPlatformRequest_h
#define CTCellularPlanTransferCrossPlatformRequest_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"

@class NSString;

@interface CTCellularPlanTransferCrossPlatformRequest : NSObject<NSSecureCoding>

@property (readonly, nonatomic) NSString *phoneNumber;
@property (readonly, nonatomic) NSString *carrierName;
@property (readonly, nonatomic) NSString *mccMnc;
@property (readonly, nonatomic) NSString *gid1;
@property (readonly, nonatomic) NSString *gid2;
@property (readonly, nonatomic) NSString *carrierID;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithPhoneNumber:(id)number carrierName:(id)name mccMnc:(id)mnc gid1:(id)gid1 gid2:(id)gid2;
- (id)initWithPhoneNumber:(id)number carrierName:(id)name mccMnc:(id)mnc gid1:(id)gid1 gid2:(id)gid2 carrierID:(id)id;
- (id)description;
- (BOOL)isEqual:(id)equal;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
@end

#endif /* CTCellularPlanTransferCrossPlatformRequest_h */
