//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 11207.0.0.0.0
//
#ifndef CTEOSFirmwareInfo_h
#define CTEOSFirmwareInfo_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSData, NSNumber;

@interface CTEOSFirmwareInfo : NSObject<NSCopying, NSSecureCoding>

@property (retain, nonatomic) NSData *currentVersion;
@property (retain, nonatomic) NSNumber *userProfiles;
@property (retain, nonatomic) NSData *updateCsn;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)description;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
@end

#endif /* CTEOSFirmwareInfo_h */
