//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 11207.0.0.0.0
//
#ifndef CTXPCServiceCoreTelephonyInternalSettingsInterface_Protocol_h
#define CTXPCServiceCoreTelephonyInternalSettingsInterface_Protocol_h
@import Foundation;

@protocol CTXPCServiceCoreTelephonyInternalSettingsInterface 
/* instance methods */
- (void)setPrefForKey:(id)key heirarchy:(id)heirarchy value:(id)value storage:(id)storage completion:(id /* block */)completion;
- (void)getPrefForKey:(id)key heirarchy:(id)heirarchy storage:(id)storage completion:(id /* block */)completion;
- (void)terminateProcess:(id /* block */)process;
- (void)getRadioPersonality:(id)personality completion:(id /* block */)completion;
@end

#endif /* CTXPCServiceCoreTelephonyInternalSettingsInterface_Protocol_h */
