//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2398.45.8.0.0
//
#ifndef _CLKTimeFormatterSubstringRange_h
#define _CLKTimeFormatterSubstringRange_h
@import Foundation;

@interface _CLKTimeFormatterSubstringRange : NSObject

@property (nonatomic) struct _NSRange { unsigned long long x0; unsigned long long x1; } range;

/* class methods */
+ (id)rangeWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;

/* instance methods */
- (id)initWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (id)substringFromString:(id)string;
@end

#endif /* _CLKTimeFormatterSubstringRange_h */
