//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2000.2.2.0.0
//
#ifndef AWDWatchKitEstablishExtensionConnection_h
#define AWDWatchKitEstablishExtensionConnection_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"

@class NSString;

@interface AWDWatchKitEstablishExtensionConnection : PBCodable<NSCopying> {
  /* instance variables */
  struct { unsigned int x :1 timestamp; unsigned int x :1 connectionType; unsigned int x :1 endToEndTime; unsigned int x :1 timeForExtensionToReceiveAppListener; unsigned int x :1 timeToGetFBSSOpenAppResult; unsigned int x :1 timeToGetSetupDirectXPCActionHandler; unsigned int x :1 timeToReceiveAppListenerConnection; unsigned int x :1 timeToReceiveFirstXPCRequestFromExtension; unsigned int x :1 extensionWasLaunched; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (readonly, nonatomic) BOOL hasAppBundleId;
@property (retain, nonatomic) NSString *appBundleId;
@property (readonly, nonatomic) BOOL hasClientID;
@property (retain, nonatomic) NSString *clientID;
@property (nonatomic) BOOL hasConnectionType;
@property (nonatomic) int connectionType;
@property (nonatomic) BOOL hasEndToEndTime;
@property (nonatomic) unsigned int endToEndTime;
@property (nonatomic) BOOL hasTimeToGetSetupDirectXPCActionHandler;
@property (nonatomic) unsigned int timeToGetSetupDirectXPCActionHandler;
@property (nonatomic) BOOL hasTimeToGetFBSSOpenAppResult;
@property (nonatomic) unsigned int timeToGetFBSSOpenAppResult;
@property (nonatomic) BOOL hasTimeForExtensionToReceiveAppListener;
@property (nonatomic) unsigned int timeForExtensionToReceiveAppListener;
@property (nonatomic) BOOL hasTimeToReceiveAppListenerConnection;
@property (nonatomic) unsigned int timeToReceiveAppListenerConnection;
@property (nonatomic) BOOL hasTimeToReceiveFirstXPCRequestFromExtension;
@property (nonatomic) unsigned int timeToReceiveFirstXPCRequestFromExtension;
@property (nonatomic) BOOL hasExtensionWasLaunched;
@property (nonatomic) BOOL extensionWasLaunched;

/* instance methods */
- (id)connectionTypeAsString:(int)string;
- (int)StringAsConnectionType:(id)type;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)copyTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
@end

#endif /* AWDWatchKitEstablishExtensionConnection_h */
