//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2000.2.2.0.0
//
#ifndef SPNotificationSceneDelegate_h
#define SPNotificationSceneDelegate_h
@import Foundation;

#include "PUICNotificationWindowSceneDelegate.h"
#include "PUICNotificationSceneDelegate-Protocol.h"
#include "SPNotificationSceneResizer-Protocol.h"

@class NSArray, NSString, UISceneConnectionOptions, UISceneSession, UIWindow;

@interface SPNotificationSceneDelegate : PUICNotificationWindowSceneDelegate<PUICNotificationSceneDelegate, SPNotificationSceneResizer>

@property (retain, nonatomic) UIWindow *notificationWindow;
@property (retain) UISceneSession *session;
@property (retain) UISceneConnectionOptions *connectionOptions;
@property (copy, nonatomic) NSString *notifControllerStorageKey;
@property (copy, nonatomic) NSArray *notifications;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)scene:(id)scene willConnectToSession:(id)session options:(id)options;
- (void)sceneDidDisconnect:(id)disconnect;
- (void)sceneDidBecomeActive:(id)active;
- (void)sceneWillResignActive:(id)active;
- (void)sceneWillEnterForeground:(id)foreground;
- (void)sceneDidEnterBackground:(id)background;
- (void)setNotifications:(id)notifications contextObject:(id)object;
- (void)notifyHostOfSceneIntrinsicContentSize;
@end

#endif /* SPNotificationSceneDelegate_h */
