//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2000.2.2.0.0
//
#ifndef WKInterfacePicker_h
#define WKInterfacePicker_h
@import Foundation;

#include "WKInterfaceObject.h"

@interface WKInterfacePicker : WKInterfaceObject
/* instance methods */
- (void)focus;
- (void)resignFocus;
- (void)setSelectedItemIndex:(long long)index;
- (void)setItems:(id)items;
- (void)setCoordinatedAnimations:(id)animations;
- (void)setEnabled:(BOOL)enabled;
@end

#endif /* WKInterfacePicker_h */
