//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2000.2.2.0.0
//
#ifndef WKInterfaceTable_h
#define WKInterfaceTable_h
@import Foundation;

#include "WKInterfaceObject.h"
#include "WKInterfaceController.h"

@class NSDictionary, NSMutableArray;

@interface WKInterfaceTable : WKInterfaceObject

@property (copy, nonatomic) NSDictionary *rowDescriptions;
@property (retain, nonatomic) NSMutableArray *rowControllers;
@property (retain, nonatomic) NSMutableArray *rowControllerProperties;
@property (weak, nonatomic) WKInterfaceController *controller;
@property (readonly, nonatomic) long long numberOfRows;
@property (nonatomic) BOOL curvesAtTop;
@property (nonatomic) BOOL curvesAtBottom;

/* instance methods */
- (void)_setupWithDescription:(id)description forController:(id)controller;
- (void)_getRowControllers:(id)controllers rowControllerProperties:(id)properties forRowTypes:(id)types;
- (void)setNumberOfRows:(long long)rows withRowType:(id)type;
- (void)setRowTypes:(id)types;
- (id)rowControllerAtIndex:(long long)index;
- (void)insertRowsAtIndexes:(id)indexes withRowType:(id)type;
- (void)removeRowsAtIndexes:(id)indexes;
- (void)resequenceRowControllerPropertyIndexes;
- (void)performSegueForRow:(long long)row;
- (void)scrollToRowAtIndex:(long long)index;
@end

#endif /* WKInterfaceTable_h */
