//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 756.0.0.0.0
//
#ifndef SL_OOPASpinnerTitle_h
#define SL_OOPASpinnerTitle_h
@import Foundation;

#include "UIView.h"

@class NSString, UIActivityIndicatorView, UILabel;

@interface SL_OOPASpinnerTitle : UIView {
  /* instance variables */
  UILabel *_titleView;
  UIActivityIndicatorView *_spinner;
}

@property (copy, nonatomic) NSString *title;

/* instance methods */
- (id)init;
- (void)dealloc;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)layoutSubviews;
- (void)startAnimating;
- (void)stopAnimating;
@end

#endif /* SL_OOPASpinnerTitle_h */
