//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 756.0.0.0.0
//
#ifndef SLFacebookSession_h
#define SLFacebookSession_h
@import Foundation;

@interface SLFacebookSession : NSObject
/* class methods */
+ (id)sharedSession;
+ (id)_remoteInterface;

/* instance methods */
- (id)init;
- (id)tokenSecretForEntitledClientWithError:(id *)error;
- (void)testCall;
- (void)injectCompletedUploadWithCompletion:(id /* block */)completion;
- (BOOL)uploadPost:(id)post;
- (BOOL)uploadPost:(id)post forPID:(int)pid;
- (void)uploadPost:(id)post suppressAlerts:(BOOL)alerts withPostCompletion:(id /* block */)completion;
- (void)uploadsInProgress:(id /* block */)progress;
- (void)cancelUploadWithIdentifier:(id)identifier;
- (void)revokeAccessTokenForAppWithID:(id)id;
- (void)revokeAllAccessTokensForDevice;
- (BOOL)uploadProfilePicture:(id)picture error:(id *)error;
- (void)likeURL:(id)url completion:(id /* block */)completion;
- (void)unlikeURL:(id)url completion:(id /* block */)completion;
- (void)fetchLikeStatusForURL:(id)url flags:(unsigned long long)flags completion:(id /* block */)completion;
@end

#endif /* SLFacebookSession_h */
