//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 756.0.0.0.0
//
#ifndef SLGoogleLegacyTokenMigrationRequest_h
#define SLGoogleLegacyTokenMigrationRequest_h
@import Foundation;

@interface SLGoogleLegacyTokenMigrationRequest : NSObject
/* class methods */
+ (id)urlRequestForAuthTokenFromLegacyClientToken:(id)token username:(id)username password:(id)password;
+ (id)urlRequestForAuthCodeFromAuthToken:(id)token clientID:(id)id scope:(id)scope;
@end

#endif /* SLGoogleLegacyTokenMigrationRequest_h */
