//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 756.0.0.0.0
//
#ifndef UIApplication_SLUIApplicationAdditions_h
#define UIApplication_SLUIApplicationAdditions_h
@import Foundation;

@interface UIApplication (SLUIApplicationAdditions)
/* class methods */
+ (void)shouldShowNetworkActivityIndicatorInRemoteApplication:(BOOL)application;
@end

#endif /* UIApplication_SLUIApplicationAdditions_h */
