//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 756.0.0.0.0
//
#ifndef UISearchDisplayDelegate_Protocol_h
#define UISearchDisplayDelegate_Protocol_h
@import Foundation;

@protocol UISearchDisplayDelegate <NSObject>
@optional
/* instance methods */
- (void)searchDisplayControllerWillBeginSearch:(id)search;
- (void)searchDisplayControllerDidBeginSearch:(id)search;
- (void)searchDisplayControllerWillEndSearch:(id)search;
- (void)searchDisplayControllerDidEndSearch:(id)search;
- (void)searchDisplayController:(id)controller didLoadSearchResultsTableView:(id)view;
- (void)searchDisplayController:(id)controller willUnloadSearchResultsTableView:(id)view;
- (void)searchDisplayController:(id)controller willShowSearchResultsTableView:(id)view;
- (void)searchDisplayController:(id)controller didShowSearchResultsTableView:(id)view;
- (void)searchDisplayController:(id)controller willHideSearchResultsTableView:(id)view;
- (void)searchDisplayController:(id)controller didHideSearchResultsTableView:(id)view;
- (BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchString:(id)string;
- (BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchScope:(long long)scope;
@end

#endif /* UISearchDisplayDelegate_Protocol_h */
