//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 45.0.0.0.0
//
#ifndef SwiftData_h
#define SwiftData_h

#import "_$s9SwiftData12ModelContextCN.h"
#import "_$s9SwiftData14ModelContainerCN.h"
#import "_$s9SwiftData26DefaultSerialModelExecutorCN.h"
#import "_$s9SwiftData6SchemaC12RelationshipCN.h"
#import "_$s9SwiftData6SchemaC18CompositeAttributeCN.h"
#import "_$s9SwiftData6SchemaC6EntityCN.h"
#import "_$s9SwiftData6SchemaC9AttributeCN.h"
#import "_$s9SwiftData6SchemaCN.h"
#import "_TtC9SwiftData13CoreDataStore.h"
#import "_TtC9SwiftData14_ModelMetadata.h"
#import "_TtC9SwiftData15PersistentCoder.h"
#import "_TtC9SwiftData16CompositeDecoder.h"
#import "_TtC9SwiftData16CompositeEncoder.h"
#import "_TtC9SwiftData19KnownKeysDictionary.h"
#import "_TtC9SwiftData20ManagedObjectDecoder.h"
#import "_TtC9SwiftData20ManagedObjectEncoder.h"
#import "_TtC9SwiftData22LifecycleNotifications.h"
#import "_TtC9SwiftData24_ModelContainersRegistry.h"
#import "_TtC9SwiftData28CompositeSingleValueDecoding.h"
#import "_TtC9SwiftData28CompositeSingleValueEncoding.h"
#import "_TtC9SwiftData33_SwiftDataContextThreadLocalState.h"
#import "_TtC9SwiftData34PersistentIdentifierImplementation.h"
#import "_TtCC9SwiftData12ModelContextP33_9BAFD8545624C8465B3B73E4060DF56012_UndoPayload.h"
#import "_TtCC9SwiftData12ModelContextP33_9BAFD8545624C8465B3B73E4060DF56024_UndoModifiedDeletedList.h"
#import "_TtCE9SwiftDataCSo9NSRunLoop8Observer.h"

#endif /* SwiftData_h */
