//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2202.0.0.0.0
//
#ifndef __NSOrderedSetReverseEnumerator_h
#define __NSOrderedSetReverseEnumerator_h
@import Foundation;

#include "NSEnumerator.h"

@interface __NSOrderedSetReverseEnumerator : NSEnumerator {
  /* instance variables */
  id _obj;
  unsigned long long _idx;
}

/* instance methods */
- (id)initWithObject:(id)object;
- (void)dealloc;
- (id)nextObject;
@end

#endif /* __NSOrderedSetReverseEnumerator_h */
