//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2202.0.0.0.0
//
#ifndef _CFDragPasteboardStore_h
#define _CFDragPasteboardStore_h
@import Foundation;

#include "_CFPasteboardStore.h"
#include "_CFPasteboardClientInstanceID.h"

@interface _CFDragPasteboardStore : _CFPasteboardStore {
  /* instance variables */
  struct __CFDictionary * _nextUniquingNumbers;
  _CFPasteboardClientInstanceID *_sourceProcessID;
}

/* class methods */
+ (id)dragPasteboard;

/* instance methods */
- (void)dealloc;
- (BOOL)_isManagedPromiseDragForGeneration:(unsigned long long)generation itemIdentifier:(unsigned long long)identifier;
- (void)_onqueue_clearGenerationSpecificData;
- (void)_onqueue_handleNewEntries:(struct __CFArray *)entries forMessage:(id)message shouldInvalidateClientMetadata:(BOOL *)metadata;
- (struct __CFURL *)_createUniqueFileURLInDirectory:(struct __CFURL *)directory withBaseName:(struct __CFString *)name extension:(struct __CFString *)extension locale:(struct __CFLocale *)locale;
- (void)handleUniquePromiseFile:(id)file;
- (void)requestDataForGeneration:(unsigned long long)generation itemIdentifier:(unsigned long long)identifier flavor:(struct __CFString *)flavor inResponseToMessage:(id)message completionHandler:(id /* block */)handler;
@end

#endif /* _CFDragPasteboardStore_h */
