//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3628.0.0.0.0
//
#ifndef CNAPITriageSession_h
#define CNAPITriageSession_h
@import Foundation;

#include "CNAPITriageLogger-Protocol.h"
#include "CNContactFetchRequest.h"

@protocol CNTimeProvider;

@interface CNAPITriageSession : NSObject {
  /* instance variables */
  double _timeSessionBegan;
  double _timeSessionEnded;
  double _clientCalloutTime;
  BOOL _hasClientCalloutTime;
}

@property (readonly) CNContactFetchRequest *request;
@property (readonly) NSObject<CNAPITriageLogger> *logger;
@property (readonly) NSObject<CNTimeProvider> *timeProvider;

/* instance methods */
- (id)init;
- (id)initWithRequest:(id)request;
- (id)initWithRequest:(id)request triageLogger:(id)logger timeProvider:(id)provider;
- (void)open;
- (void)addClientCalloutTime:(double)time;
- (void)close;
- (void)closeWithContacts:(id)contacts;
- (id)normalizeCollectionOfContacts:(id)contacts;
- (void)closeWithError:(id)error;
- (void)closeWithResult:(id)result;
- (void)closeWithContacts:(id)contacts orError:(id)error;
@end

#endif /* CNAPITriageSession_h */
