//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3628.0.0.0.0
//
#ifndef CNContainerRestrictionsDescription_h
#define CNContainerRestrictionsDescription_h
@import Foundation;

#include "CNContainerPropertyDescription.h"

@interface CNContainerRestrictionsDescription : CNContainerPropertyDescription
/* instance methods */
- (int)abPropertyID;
- (BOOL)isConvertibleABValue:(void *)abvalue;
- (void *)ABValueFromCNValue:(id)cnvalue;
- (id)CNValueFromABValue:(void *)abvalue;
- (BOOL)setABValue:(void *)abvalue onABSource:(void *)absource error:(struct __CFError * *)error;
- (id)key;
- (BOOL)isWritable;
- (Class)valueClass;
- (id)CNValueForContainer:(id)container;
- (void)setCNValue:(id)cnvalue onContainer:(id)container;
- (BOOL)isValidValue:(id)value error:(id *)error;
@end

#endif /* CNContainerRestrictionsDescription_h */
