//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3628.0.0.0.0
//
#ifndef CNContactImageFetchRequest_h
#define CNContactImageFetchRequest_h
@import Foundation;

#include "CNContactImageRequest-Protocol.h"

@class NSArray, NSPersistentStoreRequest, NSString;

@interface CNContactImageFetchRequest : NSObject<CNContactImageRequest>

@property (readonly, nonatomic) NSPersistentStoreRequest *persistentStoreRequest;
@property (retain, nonatomic) NSArray *contactIdentifiers;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)recentImagesRequestForContactIdenfitiers:(id)idenfitiers;
+ (id)predicateForImagesMatchingContactIdentifiers:(id)identifiers;

/* instance methods */
- (id)initWithContactIdentifiers:(id)identifiers;
@end

#endif /* CNContactImageFetchRequest_h */
