//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3628.0.0.0.0
//
#ifndef CNContactRelationsDescriptionLabels_h
#define CNContactRelationsDescriptionLabels_h
@import Foundation;

@class NSArray, NSDictionary;

@interface CNContactRelationsDescriptionLabels : NSObject

@property (readonly, nonatomic) NSArray *preferredLanguages;
@property (readonly, nonatomic) NSArray *standardLabels;
@property (readonly, nonatomic) NSArray *standardLocaleSpecificLabels;
@property (readonly, nonatomic) NSArray *extendedLabels;
@property (readonly, nonatomic) NSArray *extendedLocaleSpecificLabels;
@property (readonly, nonatomic) NSDictionary *localizedStringsByLabelKey;

/* instance methods */
- (id)initWithPreferredLanguages:(id)languages standardLabels:(id)labels standardLocaleSpecificLabels:(id)labels extendedLabels:(id)labels extendedLocaleSpecificLabels:(id)labels localizedStringsByLabelKey:(id)key;
@end

#endif /* CNContactRelationsDescriptionLabels_h */
