//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3628.0.0.0.0
//
#ifndef CNExtensionCommand_h
#define CNExtensionCommand_h
@import Foundation;

#include "CNContactsProviderSession.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSString;

@interface CNExtensionCommand : NSObject<NSCopying, NSSecureCoding>

@property (readonly, nonatomic) NSString *commandType;
@property (retain, nonatomic) NSString *bundleIdentifier;
@property (retain, nonatomic) CNContactsProviderSession *session;

/* class methods */
+ (id)new;
+ (id)fetchContainerIdentifier;
+ (id)synchronizeUsingSession:(id)session;
+ (id)fetchEnabled;
+ (id)enable;
+ (id)enableBundleIdentifier:(id)identifier;
+ (id)disable;
+ (id)disableBundleIdentifier:(id)identifier;
+ (id)fetchExtensionItemsCount;
+ (id)fetchExtensionItems;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)init;
- (id)initWithCommandType:(id)type;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
@end

#endif /* CNExtensionCommand_h */
