//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3628.0.0.0.0
//
#ifndef CNMultiValueDiff_h
#define CNMultiValueDiff_h
@import Foundation;

@class NSArray;

@interface CNMultiValueDiff : NSObject

@property (readonly, copy, nonatomic) NSArray *updates;

/* class methods */
+ (id)emptyDiff;
+ (id)diffMultiValue:(id)value toMultiValue:(id)value;

/* instance methods */
- (BOOL)applyToABPerson:(void *)abperson propertyDescription:(id)description isUnified:(BOOL)unified logger:(id)logger error:(id *)error;
- (id)initWithUpdates:(id)updates;
- (id)multiValueByApplyToMultiValue:(id)value withIdentifierMap:(id)map;
- (BOOL)isEmpty;
- (id)description;
@end

#endif /* CNMultiValueDiff_h */
