//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3628.0.0.0.0
//
#ifndef CNReputationResult_h
#define CNReputationResult_h
@import Foundation;

#include "CNReputationHandle.h"

@interface CNReputationResult : NSObject

@property (readonly, copy) CNReputationHandle *handle;
@property (readonly) long long score;

/* class methods */
+ (id)descriptionForScore:(long long)score;

/* instance methods */
- (id)initWithHandle:(id)handle score:(long long)score;
- (id)description;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
@end

#endif /* CNReputationResult_h */
