//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 624.0.100.0.0
//
#ifndef PHAssetCollectionReference_h
#define PHAssetCollectionReference_h
@import Foundation;

#include "PHCollectionReference.h"

@class NSArray;

@interface PHAssetCollectionReference : PHCollectionReference

@property (readonly, copy, nonatomic) NSArray *transientAssetReferences;
@property (readonly, nonatomic) long long assetCollectionType;
@property (readonly, nonatomic) long long assetCollectionSubtype;

/* class methods */
+ (id)representedType;
+ (id)referenceForAssetCollection:(id)collection;

/* instance methods */
- (id)initWithLocalIdentifier:(id)identifier libraryURL:(id)url type:(long long)type subtype:(long long)subtype assetReferences:(id)references transientIdentifier:(id)identifier transientTitle:(id)title;
- (id)initWithLocalIdentifier:(id)identifier libraryURL:(id)url type:(long long)type subtype:(long long)subtype;
- (id)initWithDictionary:(id)dictionary referenceType:(id)type;
- (id)dictionaryForReferenceType:(id)type;
- (BOOL)transient;
- (id)_transientCollectionInLibrary:(id)library;
@end

#endif /* PHAssetCollectionReference_h */
