//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 624.0.100.0.0
//
#ifndef PHCollectionDeleteRequest_h
#define PHCollectionDeleteRequest_h
@import Foundation;

#include "PHTrashableObjectDeleteRequest.h"

@interface PHCollectionDeleteRequest : PHTrashableObjectDeleteRequest
/* instance methods */
- (BOOL)validateForDeleteManagedObject:(id)object error:(id *)error;
- (void)deleteManagedObject:(id)object photoLibrary:(id)library;
@end

#endif /* PHCollectionDeleteRequest_h */
