//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 624.0.100.0.0
//
#ifndef PHMediaResourceRequest_h
#define PHMediaResourceRequest_h
@import Foundation;

#include "PHMediaRequest.h"
#include "PHAssetResource.h"
#include "PHAssetResourceRequest.h"
#include "PHAssetResourceRequestDelegate-Protocol.h"
#include "PHMediaResourceResult.h"

@class NSMutableData, NSString;

@interface PHMediaResourceRequest : PHMediaRequest<PHAssetResourceRequestDelegate> {
  /* instance variables */
  BOOL _networkAccessAllowed;
  long long _downloadIntent;
  long long _downloadPriority;
  BOOL _synchronous;
  PHAssetResourceRequest *_internalRequest;
  NSMutableData *_compositeData;
  PHMediaResourceResult *_dataResult;
}

@property (copy, nonatomic) id /* block */ progressHandler;
@property (readonly, nonatomic) PHAssetResource *resource;
@property (readonly, nonatomic) long long resourceType;
@property (readonly, nonatomic) BOOL wantsURLOnly;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithRequestID:(int)id requestIndex:(unsigned long long)index contextType:(long long)type managerID:(unsigned long long)id asset:(id)asset assetResource:(id)resource networkAccessAllowed:(BOOL)allowed downloadIntent:(long long)intent downloadPriority:(long long)priority wantsURLOnly:(BOOL)urlonly synchronous:(BOOL)synchronous delegate:(id)delegate;
- (BOOL)isSynchronous;
- (void)startRequest;
- (void)cancel;
- (void)handleAvailabilityChangeForResource:(id)resource url:(id)url info:(id)info error:(id)error;
- (void)_reportProgress:(double)progress;
- (void)_handleDidFindFileURL:(id)url;
- (void)_receiveAssetResourceDataPart:(id)part;
- (void)_finishWithError:(id)error;
- (void)assetResourceRequest:(id)request didFinishWithError:(id)error;
- (void)assetResourceRequestDidRequestRetryWithContentEditingInputLoaded:(id)loaded;
@end

#endif /* PHMediaResourceRequest_h */
