//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 624.0.100.0.0
//
#ifndef PLManagedAsset_PHAdoptionUtilities_h
#define PLManagedAsset_PHAdoptionUtilities_h
@import Foundation;

@interface PLManagedAsset (PHAdoptionUtilities)
/* class methods */
+ (id)pl_PHAssetsForManagedAssets:(id)assets photoLibrary:(id)library;

/* instance methods */
- (id)pl_PHAssetFromPhotoLibrary:(id)library;
- (id)pl_PHAssetWithPropertySets:(id)sets photoLibrary:(id)library;
@end

#endif /* PLManagedAsset_PHAdoptionUtilities_h */
