//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1838.60.8.0.0
//
#ifndef NEHotspotHelperCommand_h
#define NEHotspotHelperCommand_h
@import Foundation;

#include "NEHotspotNetwork.h"

@class NSArray;

@interface NEHotspotHelperCommand : NSObject {
  /* instance variables */
  struct __CNPluginCommand * _command;
}

@property (readonly) long long commandType;
@property (readonly) NEHotspotNetwork *network;
@property (readonly) NSArray *networkList;

/* instance methods */
- (id)description;
- (void)dealloc;
- (id)createResponse:(long long)response;
- (id)createTCPConnection:(id)tcpconnection;
- (id)createUDPSession:(id)udpsession;
@end

#endif /* NEHotspotHelperCommand_h */
