//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1838.60.8.0.0
//
#ifndef NEHotspotConfigurationManager_h
#define NEHotspotConfigurationManager_h
@import Foundation;

@interface NEHotspotConfigurationManager : NSObject
/* class methods */
+ (id)sharedManager;

/* instance methods */
- (void)applyConfiguration:(id)configuration completionHandler:(id /* block */)handler;
- (void)removeConfigurationForSSID:(id)ssid;
- (void)removeConfigurationForHS20DomainName:(id)name;
- (void)getConfiguredSSIDsWithCompletionHandler:(id /* block */)handler;
@end

#endif /* NEHotspotConfigurationManager_h */
