//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1838.60.8.0.0
//
#ifndef NEIKEv2TransportClient_h
#define NEIKEv2TransportClient_h
@import Foundation;

#include "NEIKEv2IKESPI.h"
#include "NEIKEv2TransportDelegate-Protocol.h"

@interface NEIKEv2TransportClient : NSObject {
  /* instance variables */
  BOOL _wildcard;
  NEIKEv2IKESPI *_clientSPI;
  NEIKEv2IKESPI *_remoteSPI;
  NSObject<NEIKEv2TransportDelegate> *_delegate;
}

/* instance methods */
- (id)description;
@end

#endif /* NEIKEv2TransportClient_h */
