//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1838.60.8.0.0
//
#ifndef NEIKEv2IKEAuthPacket_h
#define NEIKEv2IKEAuthPacket_h
@import Foundation;

#include "NEIKEv2Packet.h"
#include "NEIKEv2AuthPayload.h"
#include "NEIKEv2ChildSAPayload.h"
#include "NEIKEv2ConfigPayload.h"
#include "NEIKEv2EAPPayload.h"
#include "NEIKEv2InitiatorIdentifierPayload.h"
#include "NEIKEv2InitiatorTrafficSelectorPayload.h"
#include "NEIKEv2ResponderIdentifierPayload.h"
#include "NEIKEv2ResponderTrafficSelectorPayload.h"

@class NSArray;

@interface NEIKEv2IKEAuthPacket : NEIKEv2Packet {
  /* instance variables */
  NEIKEv2ChildSAPayload *_sa;
  NEIKEv2InitiatorIdentifierPayload *_idi;
  NEIKEv2ResponderIdentifierPayload *_idr;
  NSArray *_certificates;
  NSArray *_certificateRequests;
  NEIKEv2AuthPayload *_auth;
  NEIKEv2EAPPayload *_eap;
  NEIKEv2ConfigPayload *_config;
  NEIKEv2InitiatorTrafficSelectorPayload *_tsi;
  NEIKEv2ResponderTrafficSelectorPayload *_tsr;
  NSArray *_vendorIDs;
}

/* class methods */
+ (id)copyTypeDescription;
+ (unsigned long long)exchangeType;

/* instance methods */
- (void)gatherPayloads;
- (void)filloutPayloads;
@end

#endif /* NEIKEv2IKEAuthPacket_h */
