//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1838.60.8.0.0
//
#ifndef NETunnelProviderManager_h
#define NETunnelProviderManager_h
@import Foundation;

#include "NEVPNManager.h"

@class NSArray;

@interface NETunnelProviderManager : NEVPNManager

@property (readonly) long long routingMethod;
@property (copy) NSArray *safariDomains;
@property (copy) NSArray *mailDomains;
@property (copy) NSArray *calendarDomains;
@property (copy) NSArray *contactsDomains;
@property (copy) NSArray *appRules;
@property (copy) NSArray *excludedDomains;
@property (copy) NSArray *associatedDomains;

/* class methods */
+ (id)forPerAppVPN;
+ (void)loadAllFromPreferencesWithCompletionHandler:(id /* block */)handler;

/* instance methods */
- (id)initWithSessionType:(int)type tunnelType:(long long)type;
- (id)init;
- (BOOL)isProtocolTypeValid:(long long)valid;
- (void)additionalSetup;
- (void)loadFromPreferencesWithCompletionHandler:(id /* block */)handler;
- (id)copyAppRules;
- (id)descriptionWithIndent:(int)indent options:(unsigned long long)options;
@end

#endif /* NETunnelProviderManager_h */
