//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1838.60.8.0.0
//
#ifndef NEVPNPluginDriver_Protocol_h
#define NEVPNPluginDriver_Protocol_h
@import Foundation;

@protocol NEVPNPluginDriver <NEPluginDriver>
/* instance methods */
- (void)connectWithParameters:(id)parameters;
- (void)disconnectWithReason:(int)reason;
- (void)attachIPCWithCompletionHandler:(id /* block */)handler;
- (void)setAppUUIDMap:(id)uuidmap;
@end

#endif /* NEVPNPluginDriver_Protocol_h */
