//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1838.60.8.0.0
//
#ifndef NEVPN_h
#define NEVPN_h
@import Foundation;

#include "NEConfigurationLegacySupport-Protocol.h"
#include "NEConfigurationValidating-Protocol.h"
#include "NEPrettyDescription-Protocol.h"
#include "NEVPNProtocol.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSArray;

@interface NEVPN : NSObject<NEConfigurationValidating, NEPrettyDescription, NEConfigurationLegacySupport, NSSecureCoding, NSCopying>

@property (copy) NSArray *exceptionApps;
@property BOOL enabled;
@property BOOL onDemandEnabled;
@property (nonatomic) BOOL disconnectOnDemandEnabled;
@property (nonatomic) BOOL onDemandUserOverrideDisabled;
@property (copy) NSArray *onDemandRules;
@property (copy) NEVPNProtocol *protocol;
@property long long tunnelType;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)init;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)checkValidityAndCollectErrors:(id)errors;
- (id)descriptionWithIndent:(int)indent options:(unsigned long long)options;
- (id)description;
- (id)copyLegacyDictionary;
- (id)initFromLegacyDictionary:(id)dictionary;
- (BOOL)isEnabled;
- (BOOL)isOnDemandEnabled;
- (BOOL)isDisconnectOnDemandEnabled;
- (BOOL)isOnDemandUserOverrideDisabled;
@end

#endif /* NEVPN_h */
