//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1870.2.1.0.0
//
#ifndef CADUnalertedEventsPredicate_EKPredicateEvaluating_h
#define CADUnalertedEventsPredicate_EKPredicateEvaluating_h
@import Foundation;

@interface CADUnalertedEventsPredicate (EKPredicateEvaluating) <EKPredicateEvaluating>
/* instance methods */
- (BOOL)ekPredicateEvaluateWithObject:(id)object;
@end

#endif /* CADUnalertedEventsPredicate_EKPredicateEvaluating_h */
