//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1870.2.1.0.0
//
#ifndef EKCredentials_h
#define EKCredentials_h
@import Foundation;

@class NSString;

@interface EKCredentials : NSObject

@property (readonly, nonatomic) NSString *username;
@property (readonly, nonatomic) NSString *password;

/* class methods */
+ (id)credentialsWithUsername:(id)username password:(id)password;

/* instance methods */
- (id)description;
@end

#endif /* EKCredentials_h */
