//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1870.2.1.0.0
//
#ifndef EKFrozenReminderRecurrenceRule_h
#define EKFrozenReminderRecurrenceRule_h
@import Foundation;

#include "EKFrozenReminderObject.h"

@interface EKFrozenReminderRecurrenceRule : EKFrozenReminderObject
/* class methods */
+ (Class)meltedClass;
+ (int)convertFromReminderKitFrequency:(long long)frequency;
+ (long long)convertToReminderKitFrequency:(int)frequency;
+ (int)convertFromReminderKitWeekday:(long long)weekday;
+ (long long)convertToReminderKitWeekday:(int)weekday;

/* instance methods */
- (id)initWithREMObject:(id)remobject inStore:(id)store;
- (id)initWithREMObject:(id)remobject inStore:(id)store withChanges:(id)changes;
- (id)initWithAlternateUniverseObject:(id)object inEventStore:(id)store withUpdatedChildObjects:(id)objects;
- (id)uniqueIdentifier;
- (id)remObjectID;
- (id)_recurrenceRule;
- (id)addUpdatedRecurrenceRule:(id)rule;
- (id)uuid;
- (id)endDate;
- (unsigned long long)count;
- (int)frequencyRaw;
- (long long)interval;
- (int)firstDayOfTheWeekRaw;
- (long long)ekWeekdayToREMWeekday:(long long)remweekday;
- (long long)remWeekdayToEKWeekday:(long long)ekweekday;
- (id)daysOfTheWeekFromREMRecurrenceRule;
- (id)remDaysOfTheWeekFromEKDaysOfTheWeek:(id)week;
- (id)specifier;
- (void)loadSpecifierDaysOfTheWeek:(id *)week daysOfTheMonth:(id *)month monthsOfTheYear:(id *)year weeksOfTheYear:(id *)year daysOfTheYear:(id *)year setPositions:(id *)positions;
@end

#endif /* EKFrozenReminderRecurrenceRule_h */
