//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1870.2.1.0.0
//
#ifndef EKPredictedLocationOfInterest_h
#define EKPredictedLocationOfInterest_h
@import Foundation;

@class NSString, RTPredictedLocationOfInterest;

@interface EKPredictedLocationOfInterest : NSObject

@property (readonly, nonatomic) RTPredictedLocationOfInterest *rtPredictedLocationOfInterest;
@property (readonly, nonatomic) long long type;
@property (readonly, copy, nonatomic) NSString *customLabel;
@property (readonly, copy, nonatomic) NSString *mapItemName;
@property (readonly, copy, nonatomic) NSString *addressCountryCode;
@property (readonly, copy, nonatomic) NSString *addressThoroughfare;
@property (readonly, copy, nonatomic) NSString *addressLocality;

/* instance methods */
- (id)initWithPredictedLocationOfInterest:(id)interest;
- (id)initWithType:(long long)type customLabel:(id)label mapItemName:(id)name addressCountryCode:(id)code addressThoroughFare:(id)fare addressLocality:(id)locality;
@end

#endif /* EKPredictedLocationOfInterest_h */
