//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1870.2.1.0.0
//
#ifndef EKSerializableObject_h
#define EKSerializableObject_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"

@interface EKSerializableObject : NSObject<NSSecureCoding>
/* class methods */
+ (id)classesForKey;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
@end

#endif /* EKSerializableObject_h */
