//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1870.2.1.0.0
//
#ifndef NSDate_EKEventSuggestions_h
#define NSDate_EKEventSuggestions_h
@import Foundation;

@interface NSDate (EKEventSuggestions)
/* instance methods */
- (id)nextDateMatchingTimeComponents;
- (id)localizedShortTimeInTimeZone:(id)zone;
@end

#endif /* NSDate_EKEventSuggestions_h */
