//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef _WKRemoteObjectRegistry_h
#define _WKRemoteObjectRegistry_h
@import Foundation;

@protocol {HashMap<WTF::String, std::pair<WTF::RetainPtr<id>, WTF::RetainPtr<_WKRemoteObjectInterface>>, WTF::DefaultHash<String>, WTF::HashTraits<String>, WTF::HashTraits<std::pair<WTF::RetainPtr<id>, WTF::RetainPtr<_WKRemoteObjectInterface>>>, WTF::HashTableTraits>="m_impl"{HashTable<WTF::String, WTF::KeyValuePair<WTF::String, std::pair<WTF::RetainPtr<id>, WTF::RetainPtr<_WKRemoteObjectInterface>>>, WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<WTF::String, std::pair<WTF::RetainPtr<id>, WTF::RetainPtr<_WKRemoteObjectInterface>>>>, WTF::DefaultHash<String>, WTF::HashMap<WTF::String, std::pair<WTF::RetainPtr<id>, WTF::RetainPtr<_WKRemoteObjectInterface>>>::KeyValuePairTraits, WTF::HashTraits<String>>=""(?="m_table"^v"m_tableForLLDB"^I)}}, {HashMap<unsigned long long, PendingReply, WTF::DefaultHash<unsigned long long>, WTF::HashTraits<unsigned long long>, WTF::HashTraits<PendingReply>, WTF::HashTableTraits>="m_impl"{HashTable<unsigned long long, WTF::KeyValuePair<unsigned long long, PendingReply>, WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<unsigned long long, PendingReply>>, WTF::DefaultHash<unsigned long long>, WTF::HashMap<unsigned long long, PendingReply>::KeyValuePairTraits, WTF::HashTraits<unsigned long long>>=""(?="m_table"^v"m_tableForLLDB"^I)}}, {RetainPtr<NSMapTable>="m_ptr"^v}, {unique_ptr<WebKit::RemoteObjectRegistry, std::default_delete<WebKit::RemoteObjectRegistry>>="__ptr_"{__compressed_pair<WebKit::RemoteObjectRegistry *, std::default_delete<WebKit::RemoteObjectRegistry>>="__value_"^{RemoteObjectRegistry}}};

@interface _WKRemoteObjectRegistry : NSObject {
  /* instance variables */
  struct RetainPtr<NSMapTable> { void *m_ptr; } _remoteObjectProxies;
  struct HashMap<WTF::String, std::pair<WTF::RetainPtr<id>, WTF::RetainPtr<_WKRemoteObjectInterface>>, WTF::DefaultHash<String>, WTF::HashTraits<String>, WTF::HashTraits<std::pair<WTF::RetainPtr<id>, WTF::RetainPtr<_WKRemoteObjectInterface>>>, WTF::HashTableTraits> { struct HashTable<WTF::String, WTF::KeyValuePair<WTF::String, std::pair<WTF::RetainPtr<id>, WTF::RetainPtr<_WKRemoteObjectInterface>>>, WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<WTF::String, std::pair<WTF::RetainPtr<id>, WTF::RetainPtr<_WKRemoteObjectInterface>>>>, WTF::DefaultHash<String>, WTF::HashMap<WTF::String, std::pair<WTF::RetainPtr<id>, WTF::RetainPtr<_WKRemoteObjectInterface>>>::KeyValuePairTraits, WTF::HashTraits<String>> { union { void *m_table; unsigned int *m_tableForLLDB; } x0; } m_impl; } _exportedObjects;
  struct HashMap<unsigned long long, PendingReply, WTF::DefaultHash<unsigned long long>, WTF::HashTraits<unsigned long long>, WTF::HashTraits<PendingReply>, WTF::HashTableTraits> { struct HashTable<unsigned long long, WTF::KeyValuePair<unsigned long long, PendingReply>, WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<unsigned long long, PendingReply>>, WTF::DefaultHash<unsigned long long>, WTF::HashMap<unsigned long long, PendingReply>::KeyValuePairTraits, WTF::HashTraits<unsigned long long>> { union { void *m_table; unsigned int *m_tableForLLDB; } x0; } m_impl; } _pendingReplies;
}

@property (readonly, nonatomic) void * remoteObjectRegistry;

/* instance methods */
- (void)registerExportedObject:(id)object interface:(id)interface;
- (void)unregisterExportedObject:(id)object interface:(id)interface;
- (id)remoteObjectProxyWithInterface:(id)interface;
- (id)_initWithWebPage:(struct NakedRef<WebKit::WebPage> { struct WebPage * x0; })page;
- (id)_initWithWebPageProxy:(struct NakedRef<WebKit::WebPageProxy> { struct WebPageProxy * x0; })proxy;
- (void)_invalidate;
- (void)_sendInvocation:(id)invocation interface:(id)interface;
- (void)_invokeMethod:(const void *)method;
- (void)_callReplyWithID:(unsigned long long)id blockInvocation:(const void *)invocation;
- (void)_releaseReplyWithID:(unsigned long long)id;
@end

#endif /* _WKRemoteObjectRegistry_h */
