//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef _WKSystemPreferences_h
#define _WKSystemPreferences_h
@import Foundation;

@interface _WKSystemPreferences : NSObject
/* class methods */
+ (BOOL)isCaptivePortalModeEnabled;
+ (void)setCaptivePortalModeEnabled:(BOOL)enabled;
+ (BOOL)isCaptivePortalModeIgnored:(id)ignored;
+ (void)setCaptivePortalModeIgnored:(id)ignored ignore:(BOOL)ignore;
@end

#endif /* _WKSystemPreferences_h */
