//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef _WKWebExtensionLocalization_h
#define _WKWebExtensionLocalization_h
@import Foundation;

@class NSDictionary, NSString;

@interface _WKWebExtensionLocalization : NSObject

@property (copy, nonatomic) NSString *uniqueIdentifier;
@property (copy, nonatomic) NSDictionary *localizationDictionary;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithWebExtension:(struct WebExtension *)extension;
- (id)initWithRegionalLocalization:(id)localization languageLocalization:(id)localization defaultLocalization:(id)localization withBestLocale:(id)locale uniqueIdentifier:(id)identifier;
- (id)localizedDictionaryForDictionary:(id)dictionary;
- (id)localizedStringForKey:(id)key withPlaceholders:(id)placeholders;
- (id)localizedStringForString:(id)string;
@end

#endif /* _WKWebExtensionLocalization_h */
