//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef WKAutocorrectionContext_h
#define WKAutocorrectionContext_h
@import Foundation;

#include "UIWKAutocorrectionContext.h"

@interface WKAutocorrectionContext : UIWKAutocorrectionContext
/* class methods */
+ (id)emptyAutocorrectionContext;
+ (id)autocorrectionContextWithWebContext:(const void *)context;
@end

#endif /* WKAutocorrectionContext_h */
