//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef WKSafeBrowsingWarning_h
#define WKSafeBrowsingWarning_h
@import Foundation;

#include "UIScrollView.h"
#include "UITextViewDelegate-Protocol.h"

@class NSString;
@protocol {CompletionHandler<void (std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&)>="m_function"{Function<void (std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&)>="m_callableWrapper"{unique_ptr<WTF::Detail::CallableWrapperBase<void, std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&>, std::default_delete<WTF::Detail::CallableWrapperBase<void, std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&>>>="__ptr_"{__compressed_pair<WTF::Detail::CallableWrapperBase<void, std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&> *, std::default_delete<WTF::Detail::CallableWrapperBase<void, std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&>>>="__value_"^v}}}}, {RefPtr<const WebKit::SafeBrowsingWarning, WTF::RawPtrTraits<const WebKit::SafeBrowsingWarning>, WTF::DefaultRefDerefTraits<const WebKit::SafeBrowsingWarning>>="m_ptr"^{SafeBrowsingWarning}}, {WeakObjCPtr<UIResponder>="m_weakReference"@}, {WeakObjCPtr<WKSafeBrowsingBox>="m_weakReference"@}, {WeakObjCPtr<WKSafeBrowsingTextView>="m_weakReference"@};

@interface WKSafeBrowsingWarning : UIScrollView<UITextViewDelegate> {
  /* instance variables */
  struct CompletionHandler<void (std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&)> { struct Function<void (std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&)> { struct unique_ptr<WTF::Detail::CallableWrapperBase<void, std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&>, std::default_delete<WTF::Detail::CallableWrapperBase<void, std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&>>> { struct __compressed_pair<WTF::Detail::CallableWrapperBase<void, std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&> *, std::default_delete<WTF::Detail::CallableWrapperBase<void, std::variant<WebKit::ContinueUnsafeLoad, WTF::URL> &&>>> { void *__value_; } __ptr_; } m_callableWrapper; } m_function; } _completionHandler;
  struct RefPtr<const WebKit::SafeBrowsingWarning, WTF::RawPtrTraits<const WebKit::SafeBrowsingWarning>, WTF::DefaultRefDerefTraits<const WebKit::SafeBrowsingWarning>> { struct SafeBrowsingWarning *m_ptr; } _warning;
  struct WeakObjCPtr<WKSafeBrowsingTextView> { id m_weakReference; } _details;
  struct WeakObjCPtr<WKSafeBrowsingBox> { id m_weakReference; } _box;
  struct WeakObjCPtr<UIResponder> { id m_weakReference; } _previousFirstResponder;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame safeBrowsingWarning:(const void *)warning completionHandler:(void *)handler;
- (void)addContent;
- (void)showDetailsClicked;
- (void)updateContentSize;
- (void)layoutText;
- (void)layoutSubviews;
- (BOOL)textView:(id)view shouldInteractWithURL:(id)url inRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range interaction:(long long)interaction;
- (void)didMoveToWindow;
- (void)dealloc;
- (void)goBackClicked;
- (void)clickedOnLink:(id)link;
- (BOOL)forMainFrameNavigation;
@end

#endif /* WKSafeBrowsingWarning_h */
