//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef WKSecurityOrigin_h
#define WKSecurityOrigin_h
@import Foundation;

#include "WKObject-Protocol.h"

@class NSString;
@protocol {ObjectStorage<API::SecurityOrigin>="data"{type="__lx"[48C]}};

@interface WKSecurityOrigin : NSObject<WKObject> {
  /* instance variables */
  struct ObjectStorage<API::SecurityOrigin> { struct type { unsigned char x[48] __lx; } data; } _securityOrigin;
}

@property (readonly, copy, nonatomic) NSString *protocol;
@property (readonly, copy, nonatomic) NSString *host;
@property (readonly, nonatomic) long long port;
@property (readonly) struct Object { undefined * * x0; void * x1; } * _apiObject;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (BOOL)isSameSiteAsOrigin:(id)origin;
- (BOOL)isSameSiteAsURL:(id)url;
@end

#endif /* WKSecurityOrigin_h */
