//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef WKWebPrivacyNotificationListener_h
#define WKWebPrivacyNotificationListener_h
@import Foundation;

@protocol {BlockPtr<void ()>="m_block"@?};

@interface WKWebPrivacyNotificationListener : NSObject {
  /* instance variables */
  struct BlockPtr<void ()> { id /* block */ m_block; } _linkFilteringDataCallback;
}

/* instance methods */
- (id)init;
- (void)listenForLinkFilteringDataChanges:(id /* block */)changes;
- (void)dealloc;
- (void)didUpdate:(id)update;
@end

#endif /* WKWebPrivacyNotificationListener_h */
