//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 125.3.4.0.0
//
#ifndef MTRControllerFactory_h
#define MTRControllerFactory_h
@import Foundation;

@interface MTRControllerFactory : NSObject

@property (readonly, nonatomic) BOOL isRunning;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (BOOL)startup:(id)startup;
- (void)shutdown;
- (id)startControllerOnExistingFabric:(id)fabric;
- (id)startControllerOnNewFabric:(id)fabric;
@end

#endif /* MTRControllerFactory_h */
