//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 125.3.4.0.0
//
#ifndef MTRDeviceControllerExternalCertificateParameters_h
#define MTRDeviceControllerExternalCertificateParameters_h
@import Foundation;

#include "MTRDeviceControllerParameters.h"

@interface MTRDeviceControllerExternalCertificateParameters : MTRDeviceControllerParameters
/* instance methods */
- (id)initWithStorageDelegate:(id)delegate storageDelegateQueue:(id)queue uniqueIdentifier:(id)identifier ipk:(id)ipk vendorID:(id)id operationalKeypair:(id)keypair operationalCertificate:(id)certificate intermediateCertificate:(id)certificate rootCertificate:(id)certificate;
@end

#endif /* MTRDeviceControllerExternalCertificateParameters_h */
