//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 125.3.4.0.0
//
#ifndef MTRThreadNetworkDiagnosticsClusterNeighborTableStruct_h
#define MTRThreadNetworkDiagnosticsClusterNeighborTableStruct_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSNumber;

@interface MTRThreadNetworkDiagnosticsClusterNeighborTableStruct : NSObject<NSCopying>

@property (copy, nonatomic) NSNumber *extAddress;
@property (copy, nonatomic) NSNumber *age;
@property (copy, nonatomic) NSNumber *rloc16;
@property (copy, nonatomic) NSNumber *linkFrameCounter;
@property (copy, nonatomic) NSNumber *mleFrameCounter;
@property (copy, nonatomic) NSNumber *lqi;
@property (copy, nonatomic) NSNumber *averageRssi;
@property (copy, nonatomic) NSNumber *lastRssi;
@property (copy, nonatomic) NSNumber *frameErrorRate;
@property (copy, nonatomic) NSNumber *messageErrorRate;
@property (copy, nonatomic) NSNumber *rxOnWhenIdle;
@property (copy, nonatomic) NSNumber *fullThreadDevice;
@property (copy, nonatomic) NSNumber *fullNetworkData;
@property (copy, nonatomic) NSNumber *isChild;

/* instance methods */
- (id)init;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
@end

#endif /* MTRThreadNetworkDiagnosticsClusterNeighborTableStruct_h */
